Repository ElektraInitiative/libelektra, pull requests merged in 2018-09, with the labels that each got.

#2154 doc: Add text about Jenkins + Docker
  doc/BUILDSERVER.md
  doc/news/_preparation_next_release.md
  scripts/docker/README.md
Labels: enhancement, ready to merge

#2221 Test: Exclude Ruby Instead of Semlock Plugin
  doc/news/_preparation_next_release.md
  tests/kdb/testkdb_allplugins.cpp
Labels: bug, ready to merge

#2223 CFramework: Compare Values of Meta Keys
  doc/TESTING.md
  doc/news/_preparation_next_release.md
  src/plugins/yanlr/yanlr/list-list_map-mixed_scalars.h
  tests/cframework/tests.h
Labels: enhancement, ready to merge

#2228 Haskell: Fix Compilation of Spec Translator
  doc/news/_preparation_next_release.md
  src/libs/typesystem/libfa/CMakeLists.txt
  src/libs/typesystem/specelektra/Elektra/Parse.hs
  src/libs/typesystem/spectranslator/Elektra/Parsers.hs
Labels: bug, build, ready to merge

#2198 Integrate the OpmphmPredictor
  benchmarks/opmphm.c
  doc/news/_preparation_next_release.md
  scripts/docker/debian/stretch/Dockerfile
  scripts/run_icheck
  src/include/kdbopmphmpredictor.h
  src/include/kdbprivate.h
  src/include/kdbproposal.h
  src/libs/elektra/keyset.c
  src/libs/elektra/opmphmpredictor.c
  tests/ctest/test_opmphm_predictor.c
  tests/icheck.suppression
Labels: ready to merge

#2217 cmake: add -Werror to a build job
  cmake/ElektraCompiling.cmake
  cmake/Modules/FindIconv.cmake
  cmake/Modules/FindPluginprocess.cmake
  cmake/Modules/SafeCheckSymbolExists.cmake
  doc/news/_preparation_next_release.md
  scripts/jenkins/Jenkinsfile
  src/include/CMakeLists.txt
  src/plugins/jni/CMakeLists.txt
  tests/cframework/CMakeLists.txt
Labels: build, low priority, ready to merge

#2225 YAMBi: YAML Plugin Based on Parser Generated by Bison
  .travis.yml
  doc/man/man7/elektra-plugins.7
  doc/news/_preparation_next_release.md
  src/plugins/README.md
  src/plugins/cpptemplate/cpptemplate.hpp
  src/plugins/csvstorage/CMakeLists.txt
  src/plugins/rename/CMakeLists.txt
  src/plugins/yajl/CMakeLists.txt
  src/plugins/yambi/CMakeLists.txt
  src/plugins/yambi/README.md
  src/plugins/yambi/convert.cpp
  src/plugins/yambi/convert.hpp
  src/plugins/yambi/driver.cpp
  src/plugins/yambi/driver.hpp
  src/plugins/yambi/input.cpp
  src/plugins/yambi/input.hpp
  src/plugins/yambi/lexer.cpp
  src/plugins/yambi/lexer.hpp
  src/plugins/yambi/parser.ypp
  src/plugins/yambi/symbol.hpp
  src/plugins/yambi/testmod_yambi.cpp
  src/plugins/yambi/yambi.cpp
  src/plugins/yambi/yambi.hpp
  src/plugins/yambi/yambi/comment.yaml
  src/plugins/yambi/yambi/double_quoted_scalar.hpp
  src/plugins/yambi/yambi/double_quoted_scalar.yaml
  src/plugins/yambi/yambi/list-list_map-mixed_scalars.hpp
  src/plugins/yambi/yambi/list-list_map-mixed_scalars.yaml
  src/plugins/yambi/yambi/list-plain_scalars.hpp
  src/plugins/yambi/yambi/list-plain_scalars.yaml
  src/plugins/yambi/yambi/map-list-plain_scalars.hpp
  src/plugins/yambi/yambi/map-list-plain_scalars.yaml
  src/plugins/yambi/yambi/map-map-plain_scalars.hpp
  src/plugins/yambi/yambi/map-map-plain_scalars.yaml
  src/plugins/yambi/yambi/map-null.hpp
  src/plugins/yambi/yambi/map-null.yaml
  src/plugins/yambi/yambi/map-plain_scalar.hpp
  src/plugins/yambi/yambi/map-plain_scalar.yaml
  src/plugins/yambi/yambi/map-plain_scalars.hpp
  src/plugins/yambi/yambi/map-plain_scalars.yaml
  src/plugins/yambi/yambi/null.hpp
  src/plugins/yambi/yambi/null.yaml
  src/plugins/yambi/yambi/plain_scalar-word_chars.hpp
  src/plugins/yambi/yambi/plain_scalar-word_chars.yaml
  src/plugins/yambi/yambi/plain_scalar-word_chars_space.hpp
  src/plugins/yambi/yambi/plain_scalar-word_chars_space.yaml
  src/plugins/yambi/yambi/single_quoted_scalar.hpp
  src/plugins/yambi/yambi/single_quoted_scalar.yaml
  src/plugins/yanlr/CMakeLists.txt
  src/plugins/yanlr/README.md
  src/plugins/yanlr/YAML.g4
  src/plugins/yanlr/yaml_lexer.cpp
  src/plugins/yanlr/yaml_lexer.hpp
  tests/cframework/tests.c
  tests/cframework/tests.h
  tests/shell/check_oclint.sh
  tests/shell/check_real_world.sh
Labels: enhancement, ready to merge

#2232 Travis: Print CMake Configuration
  .travis.yml
  doc/news/_preparation_next_release.md
  src/bindings/gi/lua/CMakeLists.txt
  src/bindings/io/ev/CMakeLists.txt
  src/bindings/jna/CMakeLists.txt
  src/bindings/swig/lua/CMakeLists.txt
  src/plugins/mmapstorage/CMakeLists.txt
  src/plugins/mmapstorage/mmapstorage.c
  src/tools/gen/CMakeLists.txt
  src/tools/race/CMakeLists.txt
Labels: build, enhancement, ready to merge

#2234 Doc: News: prepare next release update
  doc/news/_preparation_next_release.md
Labels: ready to merge

#2242 Travis: Use Latest Version of Xcode
  .travis.yml
  doc/news/_preparation_next_release.md
Labels: build, enhancement, ready to merge

#2078 passwd: properly set feature flags
  doc/news/_preparation_next_release.md
  scripts/jenkins/Jenkinsfile
  src/plugins/passwd/CMakeLists.txt
  src/plugins/passwd/README.md
  src/plugins/passwd/hasfgetpwent.c
  src/plugins/passwd/hasputpwent.c
  src/plugins/passwd/passwd.c
  src/plugins/passwd/testmod_passwd.c
Labels: enhancement, ready to merge

#2233 network: Changed to allow non-numerical hosts
  doc/news/_preparation_next_release.md
  src/include/CMakeLists.txt
  src/include/kdbconfig.h.in
  src/plugins/ipaddr/test_ipaddr.h
  src/plugins/network/README.md
  src/plugins/network/network.c
Labels: ready to merge

#2244 Travis: Exclude Most Plugins in Job `🍏 Clang ASAN`
  .travis.yml
  doc/news/_preparation_next_release.md
Labels: build, enhancement, ready to merge

#2255 Documentation: Add List of Available Packages
  doc/INSTALL.md
  doc/news/_preparation_next_release.md
  src/bindings/cpp/tests/CMakeLists.txt
Labels: enhancement, proposal, ready to merge, usability

#2245 Travis: Fix Compilation With Clang 7
  doc/news/_preparation_next_release.md
  src/bindings/cpp/tests/CMakeLists.txt
Labels: build, enhancement, ready to merge

#2247 Terminate gpg-agent after unit test is done
  doc/news/_preparation_next_release.md
  src/plugins/crypto/test_internals.h
  src/plugins/fcrypt/testmod_fcrypt.c
  src/plugins/gpgme/testmod_gpgme.c
Labels: ready to merge
