Repository ElektraInitiative/libelektra, pull requests merged in 2018-10, with the labels that each got.

#2250 YAMBi: Execute Unit Tests Again
  doc/news/_preparation_next_release.md
  src/plugins/yambi/README.md
  src/plugins/yambi/driver.cpp
  src/plugins/yambi/input.cpp
  src/plugins/yambi/input.hpp
  src/plugins/yambi/testmod_yambi.cpp
Labels: bug, build, ready to merge

#2262 mmapstorage: change unlinking approach
  doc/news/_preparation_next_release.md
  src/include/kdbprivate.h
  src/libs/elektra/keyset.c
  src/plugins/mmapstorage/README.md
  src/plugins/mmapstorage/internal.h
  src/plugins/mmapstorage/mmapstorage.c
  src/plugins/mmapstorage/testmod_mmapstorage.c
Labels: ready to merge

#2263 Travis: Mitigate Timeout Problems
  .travis.yml
  doc/news/_preparation_next_release.md
Labels: build, enhancement, ready to merge

#2251 YAwn: Initial Version of Storage Plugin
  cmake/Modules/FindYAEP.cmake
  cmake/Modules/LibAddPlugin.cmake
  doc/man/man7/elektra-plugins.7
  doc/news/_preparation_next_release.md
  scripts/docker/alpine/3.8/Dockerfile
  scripts/jenkins/Jenkinsfile
  src/plugins/README.md
  src/plugins/yambi/CMakeLists.txt
  src/plugins/yawn/CMakeLists.txt
  src/plugins/yawn/README.md
  src/plugins/yawn/convert.cpp
  src/plugins/yawn/convert.hpp
  src/plugins/yawn/error_listener.cpp
  src/plugins/yawn/error_listener.hpp
  src/plugins/yawn/input.cpp
  src/plugins/yawn/input.hpp
  src/plugins/yawn/lexer.cpp
  src/plugins/yawn/lexer.hpp
  src/plugins/yawn/listener.cpp
  src/plugins/yawn/listener.hpp
  src/plugins/yawn/location.hpp
  src/plugins/yawn/position.hpp
  src/plugins/yawn/testmod_yawn.cpp
  src/plugins/yawn/token.cpp
  src/plugins/yawn/token.hpp
  src/plugins/yawn/walk.cpp
  src/plugins/yawn/walk.hpp
  src/plugins/yawn/yaml.bnf
  src/plugins/yawn/yawn.cpp
  src/plugins/yawn/yawn.hpp
  src/plugins/yawn/yawn/comment.yaml
  src/plugins/yawn/yawn/double_quoted_scalar.hpp
  src/plugins/yawn/yawn/double_quoted_scalar.yaml
  src/plugins/yawn/yawn/list-list_map-mixed_scalars.hpp
  src/plugins/yawn/yawn/list-list_map-mixed_scalars.yaml
  src/plugins/yawn/yawn/list-plain_scalars.hpp
  src/plugins/yawn/yawn/list-plain_scalars.yaml
  src/plugins/yawn/yawn/map-list-plain_scalars.hpp
  src/plugins/yawn/yawn/map-list-plain_scalars.yaml
  src/plugins/yawn/yawn/map-map-plain_scalars.hpp
  src/plugins/yawn/yawn/map-map-plain_scalars.yaml
  src/plugins/yawn/yawn/map-null.hpp
  src/plugins/yawn/yawn/map-null.yaml
  src/plugins/yawn/yawn/map-plain_scalar.hpp
  src/plugins/yawn/yawn/map-plain_scalar.yaml
  src/plugins/yawn/yawn/map-plain_scalars.hpp
  src/plugins/yawn/yawn/map-plain_scalars.yaml
  src/plugins/yawn/yawn/null.hpp
  src/plugins/yawn/yawn/null.yaml
  src/plugins/yawn/yawn/plain_scalar-word_chars.hpp
  src/plugins/yawn/yawn/plain_scalar-word_chars.yaml
  src/plugins/yawn/yawn/plain_scalar-word_chars_space.hpp
  src/plugins/yawn/yawn/plain_scalar-word_chars_space.yaml
  src/plugins/yawn/yawn/single_quoted_scalar.hpp
  src/plugins/yawn/yawn/single_quoted_scalar.yaml
  tests/sanitizer.blacklist
  tests/shell/check_oclint.sh
Labels: enhancement, ready to merge

#2266 cmake: add dependency from plugin tests to plugins
  cmake/Modules/LibAddPlugin.cmake
  doc/news/_preparation_next_release.md
Labels: ready to merge

#2240 Style: Reformat CMake Code With cmake-format 0.4.3
  .travis.yml
  benchmarks/CMakeLists.txt
  cmake/CMakeLists.txt
  cmake/ElektraCompiling.cmake
  cmake/ElektraCoverage.cmake
  cmake/ElektraUninstall.cmake
  cmake/Modules/FindHaskell.cmake
  cmake/Modules/FindIconv.cmake
  cmake/Modules/FindLibGcrypt.cmake
  cmake/Modules/FindLibGpgme.cmake
  cmake/Modules/FindLibOpenSSL.cmake
  cmake/Modules/FindLua.cmake
  cmake/Modules/FindPython2Libs.cmake
  cmake/Modules/LibAddHaskellPlugin.cmake
  cmake/Modules/LibAddMacros.cmake
  cmake/Modules/LibAddPlugin.cmake
  doc/news/_preparation_next_release.md
  scripts/docker/debian/sid/Dockerfile
  scripts/vagrant/ubuntu/artful32/Vagrantfile
  src/bindings/gi/CMakeLists.txt
  src/bindings/jna/CMakeLists.txt
  src/libs/notification/tests/CMakeLists.txt
  src/plugins/CMakeLists.txt
  src/plugins/date/CMakeLists.txt
  src/plugins/dbusrecv/CMakeLists.txt
  src/plugins/lua/CMakeLists.txt
  src/plugins/python2/CMakeLists.txt
  src/plugins/range/CMakeLists.txt
  src/plugins/resolver/CMakeLists.txt
  tests/ctest/CMakeLists.txt
  tests/shell/shell_recorder/tutorial_wrapper/CMakeLists.txt
Labels: build, enhancement, ready to merge

#2267 Travis: Use Compiler Switch `-Werror` for GCC Jobs
  .travis.yml
  doc/news/_preparation_next_release.md
  examples/kdbset.c
  examples/namespace.c
  src/bindings/intercept/env/benchmarks/CMakeLists.txt
  src/bindings/intercept/fs/CMakeLists.txt
  src/plugins/crypto/test_internals.h
  src/plugins/csvstorage/CMakeLists.txt
  src/plugins/curlget/CMakeLists.txt
  src/plugins/fcrypt/testmod_fcrypt.c
  src/plugins/gpgme/testmod_gpgme.c
  src/plugins/keytometa/testmod_keytometa.c
  src/plugins/lineendings/CMakeLists.txt
  tests/abi/testabi_ks.c
Labels: build, enhancement, ready to merge

#2268 Jenkins: Add `-Werror` to Build Jobs
  doc/news/_preparation_next_release.md
  scripts/jenkins/Jenkinsfile
  src/bindings/swig/ruby/CMakeLists.txt
  src/include/CMakeLists.txt
  src/include/kdbconfig.h.in
  src/include/kdbtypes.h
  src/libs/pluginprocess/pluginprocess.c
  src/plugins/mmapstorage/mmapstorage.c
  src/plugins/mmapstorage/testmod_mmapstorage.c
  src/plugins/mmapstorage/testmod_mmapstorage_crc.c
  src/plugins/ruby/CMakeLists.txt
  tests/ctest/test_opmphm_predictor.c
Labels: build, enhancement, ready to merge

#2276 fcrypt, crypto, gpgme: refactor shared gpgagent shutdown code
  doc/news/_preparation_next_release.md
  src/plugins/crypto/gpgagent_teardown.h
  src/plugins/crypto/test_internals.h
  src/plugins/fcrypt/testmod_fcrypt.c
  src/plugins/gpgme/testmod_gpgme.c
Labels: ready to merge

#2282 JNA: Fix Crash in Unit Test
  doc/news/_preparation_next_release.md
  src/bindings/jna/CMakeLists.txt
  src/bindings/jna/libelektra4j/pom.xml.in
Labels: bug, build, ready to merge

#2283 Directory Value: Improve Performance
  doc/news/_preparation_next_release.md
  src/plugins/directoryvalue/README.md
  src/plugins/directoryvalue/directoryvalue_delegate.cpp
Labels: enhancement, ready to merge

#2286 Ruby plugin: fix docu for Ruby plugin
  doc/news/_preparation_next_release.md
  src/plugins/ruby/README.md
Labels: ready to merge

#2285 Ruby bindings: kdb, do not use private headers
  doc/news/_preparation_next_release.md
  src/bindings/swig/ruby/kdb.i
Labels: enhancement, ready to merge

#2288 KeySet: Fix Warnings About Truncated Output
  doc/news/_preparation_next_release.md
  src/libs/elektra/CMakeLists.txt
  src/libs/elektra/keyset.c
Labels: build, enhancement, ready to merge
