Repository ElektraInitiative/libelektra, pull requests merged in 2018-02, with the labels that each got.

#1817 Travis: Install Old Version of Qt on macOS
  .travis.yml
  cmake/Modules/LibAddPlugin.cmake
  cmake/Modules/LibFindMacros.cmake
  src/bindings/gsettings/CMakeLists.txt
  src/bindings/swig/python/CMakeLists.txt
  src/bindings/swig/python2/CMakeLists.txt
  src/bindings/swig/ruby/CMakeLists.txt
  src/libs/tools/src/plugins.cpp
  src/plugins/fcrypt/README.md
  src/plugins/haskell/README.md
  src/plugins/ruby/README.md
Labels: bug, build, ready to merge

#828 Internalnotification Plugin
  doc/news/_preparation_next_release.md
  doc/tutorials/notifications.md
  src/bindings/io/doc/io_doc.c
  src/bindings/io/uv/README.md
  src/include/CMakeLists.txt
  src/include/kdbio.h
  src/include/kdbioprivate.h
  src/include/kdbiotest.h
  src/include/kdbnotification.h
  src/include/kdbnotificationplugin.h
  src/include/kdbprivate.h
  src/libs/CMakeLists.txt
  src/libs/io/io.c
  src/libs/notification/CMakeLists.txt
  src/libs/notification/elektra-notification.pc.in
  src/libs/notification/example/CMakeLists.txt
  src/libs/notification/example/example_notification.c
  src/libs/notification/notification.c
  src/libs/notification/tests/CMakeLists.txt
  src/libs/notification/tests/testlib_notification.c
  src/plugins/README.md
  src/plugins/internalnotification/CMakeLists.txt
  src/plugins/internalnotification/README.md
  src/plugins/internalnotification/internalnotification.c
  src/plugins/internalnotification/internalnotification.h
  src/plugins/internalnotification/testmod_internalnotification.c
  src/plugins/list/README.md
  src/plugins/list/list.c
Labels: ready to merge

#1818 Various Small Fixes
  .travis.yml
  doc/COMPILE.md
  doc/news/_preparation_next_release.md
  src/plugins/crypto/CMakeLists.txt
  src/plugins/ini/README.md
  src/plugins/ini/inih-r29/inih.c
  src/plugins/multifile/CMakeLists.txt
Labels: bug, build, enhancement, ready to merge, usability

#1829 Fix Various Minor Problems
  .travis.yml
  doc/TESTING.md
  doc/help/kdb-complete.md
  doc/man/kdb-complete.1
  doc/news/_preparation_next_release.md
  doc/tutorials/cascading.md
  doc/tutorials/validation.md
  scripts/sed
  src/bindings/cpp/tests/testcpp_kdb.cpp
  src/error/exporterrors.cpp
  src/libs/notification/tests/CMakeLists.txt
  src/libs/notification/tests/testlib_notification.c
  src/plugins/base64/base64.c
  src/plugins/yamlcpp/README.md
  src/plugins/yamlcpp/read.cpp
  src/plugins/yamlcpp/write.cpp
  src/tools/qt-gui/CMakeLists.txt
  tests/shell/shell_recorder/listtest.esr
  tests/shell/shell_recorder/profiletest.esr
  tests/shell/shell_recorder/shell_recorder.sh
Labels: bug, build, enhancement, ready to merge, usability
