Repository ElektraInitiative/libelektra, pull requests merged in 2018-07, with the labels that each got.

#2117 Semlock: Disable Plugin Test
  .travis.yml
  doc/news/_preparation_next_release.md
  tests/kdb/testkdb_allplugins.cpp
Labels: bug, build, work in progress

#2120 Build: Support Environment Variables in `add_plugintest`
  .cmake-format.yaml
  cmake/Modules/LibAddPlugin.cmake
  doc/news/_preparation_next_release.md
Labels: build, enhancement, ready to merge

#2123 Opmphm Predictor update + some benchmark update
  benchmarks/opmphm.c
  doc/news/_preparation_next_release.md
  src/include/kdbopmphmpredictor.h
  src/include/kdbprivate.h
  src/libs/elektra/keyset.c
  src/libs/elektra/opmphmpredictor.c
  tests/ctest/test_opmphm_predictor.c
Labels: ready to merge

#2119 CFramework: Support Comparison of Empty Key Sets
  doc/news/_preparation_next_release.md
  tests/cframework/tests.h
Labels: bug, enhancement, ready to merge

#2122 Plugins: Yan LR & YAML Smith
  .travis.yml
  cmake/Modules/FindANTLR4Cpp.cmake
  cmake/Modules/LibAddPlugin.cmake
  doc/man/man7/elektra-plugins.7
  doc/markdownlinkconverter/elektraSpecialCharacters.sty
  doc/news/_preparation_next_release.md
  src/plugins/README.md
  src/plugins/yamlcpp/yamlcpp.cpp
  src/plugins/yamlsmith/CMakeLists.txt
  src/plugins/yamlsmith/README.md
  src/plugins/yamlsmith/testmod_yamlsmith.c
  src/plugins/yamlsmith/yamlsmith.cpp
  src/plugins/yamlsmith/yamlsmith.hpp
  src/plugins/yanlr/CMakeLists.txt
  src/plugins/yanlr/README.md
  src/plugins/yanlr/YAML.g4
  src/plugins/yanlr/YAML.tokens
  src/plugins/yanlr/error_listener.cpp
  src/plugins/yanlr/error_listener.hpp
  src/plugins/yanlr/listener.cpp
  src/plugins/yanlr/listener.hpp
  src/plugins/yanlr/testmod_yanlr.c
  src/plugins/yanlr/yaml_lexer.cpp
  src/plugins/yanlr/yaml_lexer.hpp
  src/plugins/yanlr/yanlr.cpp
  src/plugins/yanlr/yanlr.hpp
  src/plugins/yanlr/yanlr/comment.yaml
  src/plugins/yanlr/yanlr/double_quoted_scalar.h
  src/plugins/yanlr/yanlr/double_quoted_scalar.yaml
  src/plugins/yanlr/yanlr/list-list_map-mixed_scalars.h
  src/plugins/yanlr/yanlr/list-list_map-mixed_scalars.yaml
  src/plugins/yanlr/yanlr/list-plain_scalars.h
  src/plugins/yanlr/yanlr/list-plain_scalars.yaml
  src/plugins/yanlr/yanlr/map-list-plain_scalars.h
  src/plugins/yanlr/yanlr/map-list-plain_scalars.yaml
  src/plugins/yanlr/yanlr/map-map-plain_scalars.h
  src/plugins/yanlr/yanlr/map-map-plain_scalars.yaml
  src/plugins/yanlr/yanlr/map-null.h
  src/plugins/yanlr/yanlr/map-null.yaml
  src/plugins/yanlr/yanlr/map-plain_scalar.h
  src/plugins/yanlr/yanlr/map-plain_scalar.yaml
  src/plugins/yanlr/yanlr/map-plain_scalars.h
  src/plugins/yanlr/yanlr/map-plain_scalars.yaml
  src/plugins/yanlr/yanlr/null.h
  src/plugins/yanlr/yanlr/null.yaml
  src/plugins/yanlr/yanlr/plain_scalar-word_chars.h
  src/plugins/yanlr/yanlr/plain_scalar-word_chars.yaml
  src/plugins/yanlr/yanlr/plain_scalar-word_chars_space.h
  src/plugins/yanlr/yanlr/plain_scalar-word_chars_space.yaml
  src/plugins/yanlr/yanlr/single_quoted_scalar.h
  src/plugins/yanlr/yanlr/single_quoted_scalar.yaml
  tests/shell/check_oclint.sh
Labels: enhancement, ready to merge

#2127 YAJL: Use Logger Instead of `printf` Statements
  doc/news/_preparation_next_release.md
  src/plugins/yajl/yajl.h.in
  src/plugins/yajl/yajl_gen.c
  src/plugins/yajl/yajl_gen_close.c
  src/plugins/yajl/yajl_gen_open.c
  src/plugins/yajl/yajl_parse.c
Labels: enhancement, ready to merge

#2128 YAML Smith: Fix Scalar Only Export
  doc/news/_preparation_next_release.md
  src/plugins/yamlsmith/README.md
  src/plugins/yamlsmith/yamlsmith.cpp
Labels: bug, ready to merge

#2125 YAML CPP: Do Not Add Intermediate Keys
  LICENSE.md
  doc/news/_preparation_next_release.md
  src/plugins/yamlcpp/README.md
  src/plugins/yamlcpp/read.cpp
  src/plugins/yamlcpp/yamlcpp/nested_block_mapping.h
  src/plugins/yamlcpp/yamlcpp/nested_mixed_mapping.h
  src/plugins/yamlcpp/yamlcpp/nested_sequences.h
Labels: enhancement, ready to merge

#2138 Travis: Add Unique Name to Each Build Job
  .travis.yml
  doc/news/_preparation_next_release.md
Labels: build, enhancement, ready to merge

#2137 Documentation: Add Array Tutorial
  doc/help/elektra-introduction.md
  doc/man/man7/elektra-introduction.7
  doc/news/_preparation_next_release.md
  doc/tutorials/README.md
  doc/tutorials/arrays.md
  scripts/sed
  tests/shell/shell_recorder/tutorial_wrapper/CMakeLists.txt
Labels: enhancement, usability

#2134 Directory Value: Add Leafs For Empty & Null Keys
  doc/news/_preparation_next_release.md
  src/plugins/directoryvalue/directoryvalue.c
  src/plugins/yajl/README.md
  src/plugins/yajl/yajl_gen.c
  src/plugins/yajl/yajl_gen_close.c
  src/plugins/yajl/yajl_gen_open.c
  src/plugins/yajl/yajl_parse.c
  src/plugins/yamlcpp/CMakeLists.txt
  src/plugins/yamlcpp/README.md
Labels: bug, enhancement, ready to merge, usability

#2115 Typechecker improvements
  doc/news/_preparation_next_release.md
  src/libs/typesystem/specelektra/Elektra/GhcPluginExtras.hs
  src/libs/typesystem/specelektra/Elektra/Normalize.hs
  src/libs/typesystem/specelektra/Elektra/Parse.hs
  src/libs/typesystem/specelektra/Elektra/Range.hs
  src/libs/typesystem/specelektra/Elektra/RegexType.hs
  src/libs/typesystem/specelektra/Elektra/RegexTypeChecker.hs
  src/libs/typesystem/specelektra/Elektra/Solve.hs
  src/libs/typesystem/specelektra/Elektra/Types.hs
  src/libs/typesystem/specelektra/specelektra.cabal.in
  src/libs/typesystem/spectranslator/Elektra/Parsers.hs
  src/libs/typesystem/spectranslator/Elektra/SpecParser.hs
  src/libs/typesystem/spectranslator/Elektra/SpecTranslator.hs
  src/libs/typesystem/spectranslator/Elektra/Specifications.hs
  src/libs/typesystem/spectranslator/spectranslator.cabal.in
  src/plugins/regexdispatcher/Elektra/DefaultDispatcher.hs
  src/plugins/regexdispatcher/Elektra/Dispatch.hs
  src/plugins/regexdispatcher/Elektra/EnumDispatcher.hs
  src/plugins/regexdispatcher/Elektra/RangeDispatcher.hs
  src/plugins/regexdispatcher/Elektra/RegexDispatcher.hs
  src/plugins/regexdispatcher/Elektra/ValidationDispatcher.hs
  src/plugins/regexdispatcher/regexdispatcher.cabal.in
  src/plugins/regexdispatcher/testmod_regexdispatcher.c
  src/plugins/typechecker/Elektra/Typechecker.hs.in
  src/plugins/typechecker/README.md
  src/plugins/typechecker/testmod_typechecker.c
  src/plugins/typechecker/typechecker/prelude.ini
Labels: ready to merge
