Repository ElektraInitiative/libelektra, pull requests merged in 2018-03, with the labels that each got.

#1831 Improve CMake Code of (Markdown) Shell Recorder
  .travis.yml
  cmake/Modules/LibAddPlugin.cmake
  cmake/Modules/LibAddTest.cmake
  doc/help/kdb-global-umount.md
  doc/man/kdb-global-umount.1
  doc/news/_preparation_next_release.md
  src/libs/tools/tests/CMakeLists.txt
  src/plugins/base64/CMakeLists.txt
  src/plugins/blockresolver/CMakeLists.txt
  src/plugins/boolean/CMakeLists.txt
  src/plugins/cachefilter/CMakeLists.txt
  src/plugins/cachefilter/README.md
  src/plugins/camel/CMakeLists.txt
  src/plugins/conditionals/CMakeLists.txt
  src/plugins/conditionals/README.md
  src/plugins/csvstorage/CMakeLists.txt
  src/plugins/dini/CMakeLists.txt
  src/plugins/directoryvalue/CMakeLists.txt
  src/plugins/enum/CMakeLists.txt
  src/plugins/hosts/CMakeLists.txt
  src/plugins/ini/CMakeLists.txt
  src/plugins/ipaddr/CMakeLists.txt
  src/plugins/line/CMakeLists.txt
  src/plugins/mathcheck/CMakeLists.txt
  src/plugins/mini/CMakeLists.txt
  src/plugins/mozprefs/CMakeLists.txt
  src/plugins/multifile/CMakeLists.txt
  src/plugins/range/CMakeLists.txt
  src/plugins/tcl/CMakeLists.txt
  src/plugins/template/CMakeLists.txt
  src/plugins/template/README.md
  src/plugins/type/CMakeLists.txt
  src/plugins/xerces/CMakeLists.txt
  src/plugins/yajl/CMakeLists.txt
  src/plugins/yamlcpp/CMakeLists.txt
  tests/shell/shell_recorder/CMakeLists.txt
  tests/shell/shell_recorder/tutorial_wrapper/CMakeLists.txt
Labels: build, enhancement, ready to merge, usability

#1834 Travis: Add ASAN Enabled GCC Build for Linux
  .travis.yml
  cmake/ElektraCompiling.cmake
  src/plugins/yamlcpp/CMakeLists.txt
Labels: build, enhancement, low priority, ready to merge

#1841 Compiler Warnings: Add Virtual Destructors
  .travis.yml
  doc/news/_preparation_next_release.md
  src/bindings/cpp/include/kdbvalue.hpp
  src/libs/tools/include/plugindatabase.hpp
  src/plugins/python2/CMakeLists.txt
Labels: bug, build, enhancement, low priority, ready to merge

#1833 I/O Bindings for glib
  doc/news/_preparation_next_release.md
  src/bindings/README.md
  src/bindings/io/CMakeLists.txt
  src/bindings/io/glib/CMakeLists.txt
  src/bindings/io/glib/README.md
  src/bindings/io/glib/elektra-io-glib.pc.in
  src/bindings/io/glib/example/CMakeLists.txt
  src/bindings/io/glib/example/exampleio_glib.c
  src/bindings/io/glib/io_glib.c
  src/bindings/io/glib/testio_glib.c
  src/bindings/io/test/test_fd.c
  src/bindings/io/test/test_idle.c
  src/include/CMakeLists.txt
  src/include/kdbio.h
  src/include/kdbio_glib.h
  src/libs/io/io.c
  tests/valgrind.suppression
Labels: ready to merge

#1847 Crypto/fcrypt: add doc for enums
  src/plugins/crypto/crypto.h
  src/plugins/crypto/gpg.c
  src/plugins/fcrypt/fcrypt.c
Labels: ready to merge

#1848 Markdown Shell Recorder: Print Path to Test File
  doc/news/_preparation_next_release.md
  tests/shell/shell_recorder/tutorial_wrapper/markdown_shell_recorder.sh
Labels: enhancement, low priority, ready to merge, usability

#1854 Travis: Fix Haskell Build Job
  .travis.yml
Labels: build, enhancement, low priority, ready to merge

#1814 Opmphm optimization
  benchmarks/opmphm.c
  doc/news/_preparation_next_release.md
  scripts/configure-debian-optimizations
  src/include/CMakeLists.txt
  src/include/kdbconfig.h.in
  src/include/kdbopmphm.h
  src/libs/elektra/keyset.c
  src/libs/elektra/opmphm.c
  tests/ctest/test_opmphm.c
Labels: ready to merge

#1860 Cmake update
  doc/COMPILE.md
  doc/todo/FUTURE
  examples/external/cmake/CMakeLists.txt
Labels: ready to merge

#1875 "io-glib" binding: add supression rules for glib 2.42
  tests/valgrind.suppression
Labels: ready to merge
