Repository ElektraInitiative/libelektra, pull requests merged in 2018-11, with the labels that each got.

#2291 Build: Various Minor Enhancements
  .travis.yml
  doc/news/_preparation_next_release.md
  doc/todo/RELEASE
  scripts/CMakeLists.txt
  scripts/run_all
  scripts/run_all.in
  scripts/run_checkshell.in
  scripts/run_nocheckshell.in
  scripts/sed
  src/plugins/mmapstorage/README.md
  tests/CMakeLists.txt
  tests/README.md
  tests/shell/CMakeLists.txt
  tests/shell/check_formatting.sh
  tests/shell/check_get_set.sh
  tests/shell/check_oclint.sh
  tests/shell/run_all.sh
Labels: build, enhancement, ready to merge

#2292 Alpine Linux: Enable CMake Option `ENABLE_KDB_TESTING`
  doc/news/_preparation_next_release.md
  scripts/jenkins/Jenkinsfile
  src/plugins/ini/README.md
  src/plugins/yamlcpp/README.md
  tests/shell/shell_recorder/shell_recorder.sh
Labels: build, enhancement, ready to merge

#2295 Docker: Download YAEP from Main Repository
  doc/news/_preparation_next_release.md
  scripts/docker/alpine/3.8/Dockerfile
  scripts/docker/debian/stretch/Dockerfile
Labels: build, enhancement, low priority, ready to merge

#2294 Test: Use Latest Released Version of Google Test
  doc/news/_preparation_next_release.md
  scripts/docker/alpine/3.8/Dockerfile
  scripts/docker/debian/jessie/Dockerfile
  scripts/docker/debian/sid/Dockerfile
  scripts/docker/debian/stretch/Dockerfile
  scripts/docker/debian/stretch/Dockerfile.doc
  scripts/docker/debian/stretch/Dockerfile.i386
  scripts/docker/debian/stretch/Dockerfile.minimal
  scripts/docker/homepage/backend/Dockerfile
  scripts/docker/homepage/frontend/Dockerfile
  scripts/docker/ubuntu/xenial/Dockerfile
  scripts/docker/webui/base/Dockerfile
  scripts/vagrant/ubuntu/artful32/Vagrantfile
  src/bindings/cpp/tests/CMakeLists.txt
  tests/CMakeLists.txt
Labels: build, enhancement, low priority, ready to merge

#2237 doc: improved plugins.md
  doc/news/_preparation_next_release.md
  doc/tutorials/plugins.md
  src/plugins/doc/doc.h
Labels: ready to merge

#2300 Array: Change Behavior of `elektraArrayValidateBaseNameString` Slightly
  doc/news/_preparation_next_release.md
  src/libs/ease/array.c
  src/plugins/directoryvalue/directoryvalue_delegate.cpp
  src/plugins/yamlcpp/write.cpp
  tests/ctest/test_array.c
Labels: enhancement, proposal, ready to merge, usability
