Repository ElektraInitiative/libelektra, pull requests merged in 2018-08, with the labels that each got.

#2144 Travis: Use Environment Variables to Specify Build Configuration
  .travis.yml
  doc/news/_preparation_next_release.md
Labels: build, enhancement, ready to merge

#2143 jenkins: add email notifications
  doc/news/_preparation_next_release.md
  scripts/jenkins/Jenkinsfile
Labels: build, ready to merge

#2140 YAML CPP: Add Basic Support for Empty Array Fields
  doc/news/_preparation_next_release.md
  scripts/docker/alpine/3.8/Dockerfile
  scripts/jenkins/Jenkinsfile
  src/plugins/directoryvalue/directoryvalue.c
  src/plugins/yamlcpp/README.md
  src/plugins/yamlcpp/write.cpp
Labels: enhancement, ready to merge

#2121 Added Tutorial for java binding
  doc/news/_preparation_next_release.md
  doc/tutorials/README.md
  doc/tutorials/java-kdb.md
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/KeySet.java
Labels: ready to merge

#2148 Fix Crypto Library Detection & Disable JNI Plugin
  .travis.yml
  cmake/Modules/FindLibGcrypt.cmake
  cmake/Modules/FindLibOpenSSL.cmake
  doc/news/_preparation_next_release.md
  src/plugins/crypto/CMakeLists.txt
  src/plugins/crypto/compile_gcrypt.c
  src/plugins/curlget/CMakeLists.txt
  src/plugins/gitresolver/CMakeLists.txt
  src/plugins/jni/CMakeLists.txt
  src/tools/rest-backend/CMakeLists.txt
  tests/shell/check_kdb_internal_check.sh
Labels: bug, build, enhancement, ready to merge

#2147 improve email message
  doc/news/_preparation_next_release.md
  scripts/jenkins/Jenkinsfile
Labels: build, ready to merge

#2153 Template for C++ Based Plugins
  doc/man/man7/elektra-plugins.7
  doc/news/_preparation_next_release.md
  doc/todo/PLUGINS
  doc/tutorials/export.md
  doc/tutorials/import.md
  doc/tutorials/plugins.md
  scripts/copy-template
  scripts/sed
  src/error/specification
  src/plugins/README.md
  src/plugins/cpptemplate/CMakeLists.txt
  src/plugins/cpptemplate/README.md
  src/plugins/cpptemplate/cpptemplate.cpp
  src/plugins/cpptemplate/cpptemplate.hpp
  src/plugins/cpptemplate/cpptemplate_delegate.cpp
  src/plugins/cpptemplate/cpptemplate_delegate.hpp
  src/plugins/cpptemplate/testmod_cpptemplate.cpp
  src/plugins/doc/README.md
  src/plugins/typechecker/README.md
  tests/shell/check_oclint.sh
Labels: enhancement, ready to merge, usability

#2149 Pluginprocess improvements
  cmake/ElektraCompiling.cmake
  doc/news/_preparation_next_release.md
  src/bindings/haskell/src/Elektra/PluginProcess.chs
  src/include/kdbpluginprocess.h
  src/libs/pluginprocess/CMakeLists.txt
  src/libs/pluginprocess/pluginprocess.c
  src/libs/pluginprocess/tests/CMakeLists.txt
  src/libs/pluginprocess/tests/testlib_pluginprocess.c
  src/plugins/doc/doc.h
  src/plugins/haskell/haskell.c.in
  src/plugins/typechecker/Elektra/Typechecker.hs.in
  tests/cframework/tests.c
Labels: ready to merge

#2158 Detect nftw
  doc/news/_preparation_next_release.md
  scripts/jenkins/Jenkinsfile
  tests/cframework/CMakeLists.txt
Labels: build, enhancement, low priority, ready to merge

#2156 ASAN: Do not Explicitly Link ASAN Library on macOS
  cmake/ElektraCompiling.cmake
  doc/news/_preparation_next_release.md
  doc/tutorials/plugins.md
  src/bindings/gi/CMakeLists.txt
Labels: build, enhancement, ready to merge

#2159 CFramework: Improve Detection of `ftw.h`
  doc/news/_preparation_next_release.md
  tests/cframework/CMakeLists.txt
Labels: build, enhancement, ready to merge

#2165 Tests: Exit Test Programm in `exit_if_fail` If Check Fails
  doc/news/_preparation_next_release.md
  src/bindings/cpp/tests/tests.hpp
  src/plugins/cpptemplate/README.md
Labels: bug, build, ready to merge

#2167 Travis: Improve Runtime of ASAN Build Jobs
  .travis.yml
  doc/markdownlinkconverter/elektraSpecialCharacters.sty
  doc/news/_preparation_next_release.md
Labels: build, enhancement, ready to merge

#2175 pluginprocess: use pipes instead of named pipes
  doc/news/_preparation_next_release.md
  src/libs/pluginprocess/pluginprocess.c
  src/libs/pluginprocess/tests/testlib_pluginprocess.c
  src/plugins/dump/dump.cpp
Labels: ready to merge

#2174 YAML CPP: Add Meta Data for Arrays Inside Arrays
  .travis.yml
  doc/news/_preparation_next_release.md
  src/bindings/swig/ruby/CMakeLists.txt
  src/plugins/ruby/CMakeLists.txt
  src/plugins/yamlcpp/read.cpp
  src/plugins/yamlcpp/yamlcpp/nested_sequences.h
  src/plugins/yamlcpp/yamlcpp/nested_sequences.yaml
Labels: bug, ready to merge

#2173 Test: Add C++ Version of `compare_keyset`
  doc/news/_preparation_next_release.md
  src/bindings/cpp/tests/tests.hpp
Labels: enhancement, ready to merge

#2171 csvstorage fix export
  doc/news/_preparation_next_release.md
  src/plugins/csvstorage/csvstorage.c
  src/plugins/csvstorage/csvstorage/exporttest.csv
  src/plugins/csvstorage/testmod_csvstorage.c
Labels: ready to merge

#2181 Directory Value: Support Nested Arrays
  doc/news/_preparation_next_release.md
  src/bindings/cpp/include/key.hpp
  src/bindings/cpp/tests/tests.hpp
  src/plugins/directoryvalue/CMakeLists.txt
  src/plugins/directoryvalue/README.md
  src/plugins/directoryvalue/directoryvalue.c
  src/plugins/directoryvalue/directoryvalue.cpp
  src/plugins/directoryvalue/directoryvalue.h
  src/plugins/directoryvalue/directoryvalue.hpp
  src/plugins/directoryvalue/directoryvalue/arrays.hpp
  src/plugins/directoryvalue/directoryvalue/arrays_get.hpp
  src/plugins/directoryvalue/directoryvalue/arrays_set.hpp
  src/plugins/directoryvalue/directoryvalue/empty.hpp
  src/plugins/directoryvalue/directoryvalue/extended_get.hpp
  src/plugins/directoryvalue/directoryvalue/extended_set.hpp
  src/plugins/directoryvalue/directoryvalue/simple_get.hpp
  src/plugins/directoryvalue/directoryvalue/simple_set.hpp
  src/plugins/directoryvalue/directoryvalue_delegate.cpp
  src/plugins/directoryvalue/directoryvalue_delegate.hpp
  src/plugins/directoryvalue/testmod_directoryvalue.c
  src/plugins/directoryvalue/testmod_directoryvalue.cpp
  src/plugins/mini/README.md
  src/plugins/yajl/README.md
  src/plugins/yamlcpp/README.md
  src/plugins/yamlsmith/README.md
  src/plugins/yamlsmith/yamlsmith.cpp
Labels: enhancement, ready to merge

#2183 C++: Add Method `delBaseName`
  doc/news/_preparation_next_release.md
  src/bindings/cpp/include/key.hpp
  src/plugins/directoryvalue/directoryvalue_delegate.cpp
Labels: enhancement, ready to merge, usability

#2187 Markdown Shell Recorder: Improve Bourne Shell Compatibility
  doc/news/_preparation_next_release.md
  scripts/docker/alpine/3.8/Dockerfile
  src/plugins/type/README.md
  tests/shell/shell_recorder/tutorial_wrapper/markdown_shell_recorder.sh
Labels: enhancement, ready to merge

#2194 typechecker-finalizations
  doc/news/_preparation_next_release.md
  scripts/generate-haskell-dependencies
  scripts/generate-haskell-dependencies.hs
  src/bindings/haskell/README.md
  src/plugins/regexdispatcher/Elektra/DefaultDispatcher.hs
  src/plugins/regexdispatcher/Elektra/RangeDispatcher.hs
Labels: ready to merge

#1783 Process Plugin
  cmake/Modules/LibAddPlugin.cmake
  doc/news/_preparation_next_release.md
  src/error/specification
  src/libs/invoke/invoke.c
  src/plugins/README.md
  src/plugins/process/CMakeLists.txt
  src/plugins/process/README.md
  src/plugins/process/process.c
  src/plugins/process/process.h
  src/plugins/process/testmod_process.c
  src/plugins/python/python.cpp
  tests/cframework/tests.c
  tests/kdb/testkdb_allplugins.cpp
Labels: ready to merge

#2193 jenkins: build artifacts everywhere
  doc/news/_preparation_next_release.md
  scripts/jenkins/Jenkinsfile
Labels: build, ready to merge

#2208 Stricter cleanup
  doc/news/_preparation_next_release.md
  scripts/jenkins/Jenkinsfile.daily
Labels: build, low priority, ready to merge
