Repository ElektraInitiative/libelektra, pull requests merged in 2018-04, with the labels that each got.

#1893 Benchmarks: opmphm: add time benchmarks for opmphm, binary search and hsearch
  benchmarks/README.md
  benchmarks/opmphm.c
Labels: ready to merge

#1896 haskell:Check GHC version in cmake
  doc/news/_preparation_next_release.md
  src/bindings/haskell/CMakeLists.txt
  src/bindings/haskell/README.md
Labels: ready to merge

#1863 fix #1821
  doc/news/_preparation_next_release.md
  src/plugins/spec/spec.c
Labels: ready to merge

#1910 Add Jenkinsfile.daily
  doc/news/_preparation_next_release.md
  scripts/jenkins/Jenkinsfile.daily
Labels: ready to merge

#1917 Shell Recorder: Fix Test Issues of PR #1915
  .github/ISSUE_TEMPLATE.md
  doc/help/kdb-cp.md
  doc/help/kdb-get.md
  doc/help/kdb-mv.md
  doc/man/kdb-cp.1
  doc/man/kdb-get.1
  doc/man/kdb-mv.1
  doc/news/_preparation_next_release.md
  doc/tutorials/cascading.md
  doc/tutorials/validation.md
  src/plugins/blockresolver/README.md
  src/plugins/haskell/testmod_haskell.c
  src/plugins/ini/README.md
  src/tools/kdb/cmdline.cpp
  src/tools/kdb/cmdline.hpp
  src/tools/kdb/cp.cpp
  src/tools/kdb/get.cpp
  src/tools/kdb/mv.cpp
  tests/shell/include_common.sh.in
  tests/shell/shell_recorder/shell_recorder.sh
  tests/shell/shell_recorder/tutorial_wrapper/SyntaxCheck.md
Labels: bug, build, ready to merge, usability

#1918 Xerces: Remove Plugin on ASAN Enabled GCC Build
  .travis.yml
  doc/news/_preparation_next_release.md
  src/plugins/xerces/CMakeLists.txt
Labels: build, enhancement, low priority, ready to merge

#1927 build: Rewrite Jenkinsfile.daily
  scripts/jenkins/Jenkinsfile.daily
Labels: build, ready to merge

#1933 Fix ctest and add parallel
  cmake/Modules/LibAddPlugin.cmake
  cmake/Modules/LibAddTest.cmake
  doc/TESTING.md
  doc/news/_preparation_next_release.md
  scripts/run_all
  scripts/run_memcheck
  scripts/run_nokdbtests
  src/bindings/gi/lua/CMakeLists.txt
  src/bindings/gi/python/CMakeLists.txt
  src/bindings/glib/tests/CMakeLists.txt
  src/bindings/haskell/CMakeLists.txt
  src/bindings/io/doc/CMakeLists.txt
  src/bindings/io/glib/CMakeLists.txt
  src/bindings/io/uv/CMakeLists.txt
  src/bindings/swig/lua/tests/CMakeLists.txt
  src/bindings/swig/python/tests/CMakeLists.txt
  src/bindings/swig/python2/tests/CMakeLists.txt
  src/bindings/swig/ruby/tests/CMakeLists.txt
  src/libs/notification/tests/CMakeLists.txt
  src/tools/web/CMakeLists.txt
  tests/CMakeLists.txt
  tests/shell/CMakeLists.txt
  tests/shell/shell_recorder/CMakeLists.txt
Labels: build, ready to merge

#1939 YAML CPP: Use Bash to Convert Hex Value
  src/plugins/yamlcpp/README.md
Labels: build, enhancement, low priority, ready to merge

#1923 Tests: Enable Tests on ASAN Linux Builds
  doc/GIT.md
  tests/shell/CMakeLists.txt
  tests/shell/shell_recorder/CMakeLists.txt
Labels: bug, build, ready to merge

#1940 Shell Recorder: Minor Enhancements
  .github/ISSUE_TEMPLATE.md
  .travis.yml
  doc/COMPILE.md
  doc/news/_preparation_next_release.md
  doc/tutorials/cascading.md
  doc/tutorials/validation.md
  scripts/configure-mingw-w64
  src/libs/elektra/mount.c
  src/plugins/CMakeLists.txt
  tests/shell/include_common.sh.in
  tests/shell/shell_recorder/README.md
  tests/shell/shell_recorder/shell_recorder.sh
  tests/shell/shell_recorder/tutorial_wrapper/SyntaxCheck.md
  tests/shell/shell_recorder/tutorial_wrapper/markdown_shell_recorder.sh
Labels: bug, build, enhancement, ready to merge
