Repository ElektraInitiative/libelektra, pull requests merged in 2018-06, with the labels that each got.

#2036 Fix homepage builds
  doc/news/_preparation_next_release.md
  doc/todo/TESTING
  scripts/docker/homepage/backend/Dockerfile
  src/plugins/ni/CMakeLists.txt
  tests/shell/shell_recorder/tutorial_wrapper/CMakeLists.txt
Labels: build, ready to merge

#2040 Redo docker readme
  doc/news/_preparation_next_release.md
  scripts/docker/README.md
  scripts/docker/legacy/Dockerfile
  scripts/docker/legacy/README.md
  scripts/docker/legacy/buildelektra.sh
Labels: low priority, ready to merge, usability

#2044 build: Implement debian-stable-multiconf
  doc/news/_preparation_next_release.md
  scripts/jenkins/Jenkinsfile
Labels: build, ready to merge

#2038 Markdown Shell Recorder: Support Empty `#>` directive
  .travis.yml
  doc/news/_preparation_next_release.md
  src/plugins/ni/CMakeLists.txt
  src/plugins/ni/README.md
  src/plugins/yamlcpp/write.cpp
  tests/shell/shell_recorder/shell_recorder.sh
  tests/shell/shell_recorder/tutorial_wrapper/markdown_shell_recorder.sh
Labels: bug, enhancement, ready to merge

#2045 doc: implement debian-stable-full-ini
  doc/BUILDSERVER.md
  doc/news/_preparation_next_release.md
  scripts/jenkins/Jenkinsfile
Labels: build, ready to merge

#2049 Add no kdb
  doc/BUILDSERVER.md
  doc/news/_preparation_next_release.md
  scripts/jenkins/Jenkinsfile
Labels: build

#2051 build: port mingw-64 build job
  cmake/ElektraCompiling.cmake
  doc/BUILDSERVER.md
  doc/news/_preparation_next_release.md
  scripts/docker/debian/stretch/Dockerfile
  scripts/jenkins/Jenkinsfile
Labels: build, ready to merge

#2048 build: Port no-optimizations build job
  doc/BUILDSERVER.md
  doc/news/_preparation_next_release.md
  scripts/jenkins/Jenkinsfile
Labels: build, ready to merge

#1944 Regexdispatcher
  .travis.yml
  cmake/Modules/LibAddHaskellPlugin.cmake
  doc/METADATA.ini
  doc/news/_preparation_next_release.md
  src/bindings/haskell/CMakeLists.txt
  src/bindings/haskell/libelektra-haskell.cabal.in
  src/bindings/haskell/src/Elektra/Invoke.chs
  src/bindings/haskell/src/Elektra/Key.chs
  src/bindings/haskell/src/Elektra/Plugin.chs
  src/bindings/haskell/src/Elektra/PluginProcess.chs
  src/include/kdbpluginprocess.h
  src/libs/pluginprocess/pluginprocess.c
  src/libs/typesystem/libfa/FiniteAutomata.chs
  src/libs/typesystem/spectranslator/Elektra/Parsers.hs
  src/libs/typesystem/spectranslator/Elektra/SpecParser.hs
  src/libs/typesystem/spectranslator/Elektra/SpecTranslator.hs
  src/libs/typesystem/spectranslator/Elektra/Specifications.hs
  src/plugins/README.md
  src/plugins/regexdispatcher/CMakeLists.txt
  src/plugins/regexdispatcher/Elektra/Dispatch.hs
  src/plugins/regexdispatcher/Elektra/EnumDispatcher.hs
  src/plugins/regexdispatcher/Elektra/Parsers.hs
  src/plugins/regexdispatcher/Elektra/Range.hs
  src/plugins/regexdispatcher/Elektra/RangeDispatcher.hs
  src/plugins/regexdispatcher/Elektra/RegexDispatcher.hs
  src/plugins/regexdispatcher/Elektra/ValidationDispatcher.hs
  src/plugins/regexdispatcher/README.md
  src/plugins/regexdispatcher/Setup.hs
  src/plugins/regexdispatcher/regexdispatcher.cabal.in
  src/plugins/regexdispatcher/testmod_regexdispatcher.c
  src/plugins/typechecker/CMakeLists.txt
  src/plugins/typechecker/Elektra/Typechecker.hs.in
  src/plugins/typechecker/README.md
  src/plugins/typechecker/sandbox/sandbox.cabal
  src/plugins/typechecker/testmod_typechecker.c
  src/plugins/typechecker/typechecker/prelude.ini
Labels: ready to merge

#2058 Release: Improve Structure of Release Notes
  doc/METADATA.ini
  doc/help/kdb-change-resolver-symlink.md
  doc/help/kdb-change-storage-symlink.md
  doc/man/man1/kdb-change-resolver-symlink.1
  doc/man/man1/kdb-change-storage-symlink.1
  doc/news/_preparation_next_release.md
  doc/todo/NEWS.md
  scripts/fix-spelling
  src/plugins/typechecker/README.md
Labels: enhancement, low priority, proposal, ready to merge, usability

#2039 kdb-set: add line about negative values to usage text
  doc/help/kdb-set.md
  doc/help/kdb.md
  doc/news/_preparation_next_release.md
  src/tools/kdb/set.hpp
Labels: ready to merge

#2055 Haskell build fixes
  .travis.yml
  cmake/ElektraCache.cmake
  cmake/Modules/LibAddBinding.cmake
  cmake/Modules/LibAddHaskellPlugin.cmake
  cmake/Modules/LibAddPlugin.cmake
  doc/news/_preparation_next_release.md
  src/bindings/haskell/CMakeLists.txt
  src/bindings/haskell/README.md
  src/libs/elektra/CMakeLists.txt
  src/plugins/regexdispatcher/regexdispatcher.cabal.in
  src/plugins/typechecker/CMakeLists.txt
Labels: ready to merge

#2060 jenkins: port xdg build to new system
  doc/BUILDSERVER.md
  doc/news/_preparation_next_release.md
  scripts/jenkins/Jenkinsfile
Labels: build, ready to merge

#2069 shared-only-test-fix
  doc/news/_preparation_next_release.md
  tests/shell/CMakeLists.txt
  tests/shell/check_kdb_internal_check.sh
  tests/shell/include_common.sh.in
Labels: ready to merge

#2047 build: port i386 job to new build system
  doc/BUILDSERVER.md
  doc/news/_preparation_next_release.md
  scripts/docker/debian/stretch/Dockerfile.i386
  scripts/jenkins/Jenkinsfile
Labels: build, ready to merge

#2046 Add static and full builds
  doc/BUILDSERVER.md
  doc/news/_preparation_next_release.md
  scripts/jenkins/Jenkinsfile
  tests/shell/check_kdb_internal_check.sh
  tests/shell/include_common.sh.in
Labels: build, ready to merge

#2079 network: fix getaddrinfo call
  doc/news/_preparation_next_release.md
  src/plugins/network/network.c
Labels: bug, ready to merge

#2082 Add regex tests + fix musl fstab issues
  doc/news/_preparation_next_release.md
  scripts/reformat-source
  src/plugins/fstab/fstab/fstab-write
  src/plugins/fstab/testmod_fstab.c
  tests/cframework/tests.c
  tests/cframework/tests.h
Labels: bug, enhancement, ready to merge

#2084 Build: Do Not Install Google Test
  doc/news/_preparation_next_release.md
  tests/CMakeLists.txt
Labels: bug, build, ready to merge

#2072 Opmphm Build Prediction Preparements
  benchmarks/opmphm.c
  doc/news/_preparation_next_release.md
  src/include/kdbopmphm.h
  src/include/kdbopmphmpredictor.h
  src/include/kdbprivate.h
  src/libs/elektra/keyset.c
  src/libs/elektra/opmphm.c
  src/libs/elektra/opmphmpredictor.c
  tests/ctest/CMakeLists.txt
  tests/ctest/test_ks_opmphm.c
  tests/ctest/test_opmphm.c
  tests/ctest/test_opmphm_predictor.c
Labels: ready to merge

#2085 crypto, fcrypt: check gpg availability in unit tests
  doc/news/_preparation_next_release.md
  src/plugins/crypto/common_gpg_tests.c
  src/plugins/crypto/gpg.c
  src/plugins/crypto/gpg.h
  src/plugins/crypto/test_internals.h
  src/plugins/fcrypt/testmod_fcrypt.c
Labels: ready to merge

#2094 Fix archivation
  doc/news/_preparation_next_release.md
  scripts/jenkins/Jenkinsfile
Labels: ready to merge, urgent

#2090 fcrypt: consider the environment (TMPDIR) when looking for the tempor…
  doc/news/_preparation_next_release.md
  src/plugins/fcrypt/README.md
  src/plugins/fcrypt/fcrypt.c
Labels: ready to merge

#2056 tests: Properly remove temporary test home dir
  cmake/ElektraCompiling.cmake
  doc/news/_preparation_next_release.md
  tests/cframework/CMakeLists.txt
  tests/cframework/tests.c
Labels: enhancement, ready to merge

#2066 CCode Updates & Other Minor Enhancements
  .cmake-format.yaml
  .travis.yml
  cmake/Modules/LibAddTest.cmake
  doc/help/kdb-find.md
  doc/help/kdb-ls.md
  doc/man/man1/kdb-find.1
  doc/man/man1/kdb-ls.1
  doc/news/_preparation_next_release.md
  src/bindings/cpp/include/key.hpp
  src/bindings/cpp/tests/tests.hpp
  src/plugins/boolean/README.md
  src/plugins/ccode/CMakeLists.txt
  src/plugins/ccode/README.md
  src/plugins/ccode/ccode.c
  src/plugins/ccode/ccode.cpp
  src/plugins/ccode/ccode.h
  src/plugins/ccode/ccode.hpp
  src/plugins/ccode/coder.cpp
  src/plugins/ccode/coder.hpp
  src/plugins/ccode/testmod_ccode.c
  src/plugins/ccode/testmod_ccode.cpp
  src/plugins/constants/README.md
  src/plugins/csvstorage/README.md
  src/plugins/hexnumber/README.md
  src/plugins/internalnotification/README.md
  src/plugins/mini/mini.c
  src/plugins/mini/testmod_mini.c
  src/plugins/rename/CMakeLists.txt
  src/plugins/rename/README.md
  src/plugins/ruby/README.md
  src/plugins/simpleini/README.md
  src/plugins/tcl/CMakeLists.txt
  src/plugins/tcl/README.md
  src/plugins/tcl/action.cpp
  src/plugins/tcl/action.hpp
  src/plugins/tcl/printer.cpp
  src/plugins/tcl/printer.hpp
  src/plugins/tcl/tcl.cpp
  src/plugins/tcl/tcl.hpp
  src/plugins/type/CMakeLists.txt
  src/plugins/uname/README.md
  src/plugins/xerces/README.md
  tests/shell/check_oclint.sh
  tests/shell/shell_recorder/shell_recorder.sh
  tests/shell/shell_recorder/tutorial_wrapper/CMakeLists.txt
  tests/shell/shell_recorder/tutorial_wrapper/markdown_shell_recorder.sh
Labels: bug, enhancement, ready to merge

#2098 jenkins: strip top level of coverage
  cmake/ElektraCache.cmake
  doc/news/_preparation_next_release.md
Labels: ready to merge

#2108 travis-ci: bump macOS/Xcode versions
  .travis.yml
  doc/news/_preparation_next_release.md
Labels: ready to merge

#2107 Elektra Web 1.6
  doc/news/_preparation_next_release.md
  scripts/docker/web/elektrad-demo/Dockerfile
  scripts/docker/web/elektrad-demo/realworld.ini
  src/tools/web/client/package.json
  src/tools/web/client/src/actions/kdb.js
  src/tools/web/client/src/actions/utils.js
  src/tools/web/client/src/components/ErrorSnackbar.jsx
  src/tools/web/client/src/components/InstanceError.jsx
  src/tools/web/client/src/components/Menu.jsx
  src/tools/web/client/src/components/NotificationSnackbar.jsx
  src/tools/web/client/src/components/TreeItem/ArrayIcon.jsx
  src/tools/web/client/src/components/TreeItem/dialogs/AddDialog.jsx
  src/tools/web/client/src/components/TreeItem/dialogs/SettingsDialog.jsx
  src/tools/web/client/src/components/TreeItem/fields/SimpleTextField.jsx
  src/tools/web/client/src/components/TreeItem/fields/validateType.js
  src/tools/web/client/src/components/TreeItem/index.js
  src/tools/web/client/src/components/TreeSearch.jsx
  src/tools/web/client/src/components/TreeView.jsx
  src/tools/web/client/src/components/pages/Configuration.jsx
  src/tools/web/client/src/containers/ConnectedTreeItem.js
  src/tools/web/client/src/containers/ConnectedTreeView.js
  src/tools/web/client/src/css/treeview.css
  src/tools/web/client/src/reducers/error.js
  src/tools/web/client/src/reducers/kdb.js
  src/tools/web/client/src/reducers/ls.js
  src/tools/web/client/src/undo.js
  src/tools/web/elektrad/package.json
  src/tools/web/kdb.js
  src/tools/web/webd/package.json
Labels: ready to merge

#2102 Build: Add Support for C++ Tests to LibAddPlugin
  .cmake-format.yaml
  cmake/Modules/LibAddPlugin.cmake
  doc/news/_preparation_next_release.md
  src/plugins/ccode/CMakeLists.txt
  src/plugins/type/CMakeLists.txt
Labels: build, enhancement, ready to merge
