Repository ElektraInitiative/libelektra, pull requests merged in 2018-05, with the labels that each got.

#1953 Require Swig Bindings for Plugins & Minor Fixes for GCC 8
  .travis.yml
  cmake/Modules/LibAddBinding.cmake
  doc/news/_preparation_next_release.md
  src/libs/elektra/plugin.c
  src/libs/tools/src/plugindatabase.cpp
  src/plugins/crypto/botan_operations.cpp
  src/plugins/directoryvalue/directoryvalue.c
  src/plugins/lua/CMakeLists.txt
  src/plugins/python/CMakeLists.txt
  src/plugins/python2/CMakeLists.txt
  src/plugins/yamlcpp/yamlcpp.cpp
  src/tools/kdb/cmdline.cpp
  src/tools/qt-gui/src/confignode.cpp
  src/tools/qt-gui/src/guibackend.cpp
  src/tools/rest-backend/authentication_application.cpp
  src/tools/rest-backend/benchmarks/benchmark_kdbrest_elektra.cpp
  src/tools/rest-backend/config.cpp
  src/tools/rest-backend/conversion_application.cpp
  src/tools/rest-backend/database_application.cpp
  src/tools/rest-backend/main.cpp
  src/tools/rest-backend/model_user.hpp
  src/tools/rest-backend/root_application.cpp
  src/tools/rest-backend/service_config.cpp
  src/tools/rest-backend/service_convert.cpp
  src/tools/rest-backend/tests/test_model_pluginformat.cpp
  src/tools/rest-backend/tests/test_model_user.cpp
  src/tools/rest-backend/tests/test_service_storageengine.cpp
  src/tools/rest-backend/user_application.cpp
Labels: build, enhancement, ready to merge, usability

#1866 Prepare Jenkinsfile
  doc/GIT.md
  scripts/docker/Dockerfile
  scripts/docker/README.md
  scripts/docker/buildelektra.sh
  scripts/docker/debian/jessie/Dockerfile
  scripts/docker/debian/sid/Dockerfile
  scripts/docker/debian/stretch/Dockerfile
  scripts/docker/debian/stretch/Dockerfile.doc
  scripts/docker/debian/stretch/Dockerfile.minimal
  scripts/docker/jenkinsnode/Dockerfile
  scripts/docker/jenkinsnode/README.md
  scripts/docker/jenkinsnode/run-make
  scripts/docker/jenkinsnode/run-make-env
  scripts/docker/jenkinsnode/run-nice
  scripts/docker/ubuntu/xenial/Dockerfile
  scripts/jenkins/Jenkinsfile
Labels: build, ready to merge

#1958 scripts: fixes for dev env
  scripts/include-common
  scripts/list-tools.in
  scripts/run_dev_env
Labels: ready to merge

#1970 Build: Fix Detection of Botan, Libgcrypt, LibGit2 and OpenSSL
  doc/news/_preparation_next_release.md
  src/plugins/crypto/compile_botan.cpp
  src/plugins/crypto/compile_gcrypt.c
  src/plugins/crypto/compile_openssl.c
  src/plugins/gitresolver/gitresolver_test.c
Labels: bug, build, enhancement, ready to merge

#1971 crypto: fix OpenSSL related linker warning
  src/plugins/crypto/openssl_operations.c
Labels: ready to merge

#1978 Tools: Disable Warning About Virtual Destructors
  src/libs/tools/src/CMakeLists.txt
  src/libs/tools/tests/CMakeLists.txt
Labels: bug, build

#1965 Add package builds
  doc/INSTALL.md
  doc/news/_preparation_next_release.md
  scripts/docker/debian/stretch/Dockerfile
  scripts/jenkins/Jenkinsfile
Labels: build, ready to merge

#1979 Shell Recorder: Always Remove Protocol File
  doc/news/_preparation_next_release.md
  tests/shell/shell_recorder/README.md
  tests/shell/shell_recorder/shell_recorder.sh
Labels: build, enhancement

#1967 Travis: Enable All Bindings
  .travis.yml
  doc/news/_preparation_next_release.md
  scripts/jenkins/Jenkinsfile
  src/bindings/cpp/tests/testcpp_key.cpp
  src/bindings/swig/python/CMakeLists.txt
  src/bindings/swig/python2/CMakeLists.txt
  src/bindings/swig/ruby/CMakeLists.txt
  src/plugins/python/CMakeLists.txt
  src/plugins/python2/CMakeLists.txt
  src/plugins/ruby/CMakeLists.txt
Labels: build, enhancement, ready to merge

#1988 Improve coverage generation
  scripts/jenkins/Jenkinsfile
  scripts/jenkins/Jenkinsfile.daily
Labels: build, enhancement, ready to merge

#2000 build: Add icheck
  doc/GIT.md
  scripts/docker/debian/stretch/Dockerfile
  scripts/jenkins/Jenkinsfile
  scripts/run_icheck
Labels: build, ready to merge

#1997 mINI: Require `ccode` Plugin Instead of `code`
  doc/news/_preparation_next_release.md
  src/plugins/mini/README.md
Labels: bug, build, ready to merge

#1993 Build: Check Formatting of CMake Code & Travis Updates
  .travis.yml
  doc/CODING.md
  doc/news/_preparation_next_release.md
  tests/shell/check_formatting.sh
Labels: build, enhancement, ready to merge

#1989 crypto: utilize libinvoke for Base64 encoding/decoding
  doc/news/_preparation_next_release.md
  src/plugins/base64/base64.c
  src/plugins/base64/base64_functions.c
  src/plugins/base64/base64_functions.h
  src/plugins/base64/contract.h
  src/plugins/base64/testmod_base64.c
  src/plugins/crypto/CMakeLists.txt
  src/plugins/crypto/botan_operations.cpp
  src/plugins/crypto/gcrypt_operations.c
  src/plugins/crypto/helper.c
  src/plugins/crypto/helper.h
  src/plugins/crypto/openssl_operations.c
Labels: ready to merge

#1996 Check Bashisms: Fix Interoperability of Script
  doc/news/_preparation_next_release.md
  scripts/docker/buildelektra.sh
  scripts/reformat-cmake
  scripts/vagrant/buildelektra.sh
  src/plugins/ini/crash_test/crash_test.md
  tests/shell/CMakeLists.txt
  tests/shell/check_bashisms.sh
Labels: bug, build, ready to merge

#1998 Add jenkinsfile homepage
  scripts/docker/debian/stretch/Dockerfile.doc
  scripts/docker/homepage/backend/Dockerfile
  scripts/docker/homepage/frontend/Dockerfile
  scripts/jenkins/Jenkinsfile
  src/tools/rest-backend/run.sh
Labels: build, ready to merge

#2002 Markdown Shell Recorder: Add Partial Support for Indented Code Blocks
  doc/help/kdb-ls.md
  doc/man/man1/kdb-ls.1
  doc/news/_preparation_next_release.md
  tests/shell/shell_recorder/tutorial_wrapper/CMakeLists.txt
  tests/shell/shell_recorder/tutorial_wrapper/markdown_shell_recorder.sh
Labels: build, enhancement, usability

#2005 Markdown Shell Recorder: Support Indented Code Blocks
  doc/news/_preparation_next_release.md
  tests/shell/shell_recorder/tutorial_wrapper/SyntaxCheck.md
  tests/shell/shell_recorder/tutorial_wrapper/markdown_shell_recorder.sh
Labels: bug, build, enhancement, ready to merge

#2011 Reformat CMake: Ensure `cmake-format` Works
  doc/news/_preparation_next_release.md
  scripts/reformat-cmake
Labels: bug, build, enhancement, ready to merge, usability

#2012 build: prune docker daily
  scripts/jenkins/Jenkinsfile.daily
Labels: build, ready to merge

#2010 Add doc icheck update
  doc/news/_preparation_next_release.md
Labels: enhancement, ready to merge

#2018 Qt-GUI: Support Qt 5.11
  .travis.yml
  doc/news/_preparation_next_release.md
  src/tools/qt-gui/CMakeLists.txt
Labels: bug, build, enhancement, ready to merge

#2019 Travis: Use Latest Version of GCC and Clang
  .travis.yml
  doc/news/_preparation_next_release.md
  src/libs/notification/tests/CMakeLists.txt
Labels: bug, build, ready to merge

#2023 Daily jenkinsfile update
  doc/GIT.md
  doc/news/_preparation_next_release.md
  scripts/jenkins/Jenkinsfile.daily
Labels: build, ready to merge

#1856 list: fix for #1855
  doc/news/_preparation_next_release.md
  src/plugins/list/README.md
  src/plugins/list/list.c
  src/plugins/list/testmod_list.c
Labels: ready to merge

#1877 logging plugins: add option for logging on pregetstorage
  doc/news/_preparation_next_release.md
  doc/tutorials/README.md
  doc/tutorials/notifications.md
  src/plugins/journald/README.md
  src/plugins/journald/journald.c
  src/plugins/logchange/README.md
  src/plugins/logchange/logchange.c
  src/plugins/syslog/README.md
  src/plugins/syslog/log.h
  src/plugins/syslog/syslog.c
Labels: ready to merge

#2033 Debian: Add Attribution Info for DownloadProject
  debian/copyright
Labels: build, enhancement, ready to merge

#2004 Haskell cmake improvements
  .travis.yml
  cmake/Modules/FindHaskell.cmake
  cmake/Modules/LibAddHaskellPlugin.cmake
  doc/news/_preparation_next_release.md
  scripts/docker/debian/jessie/Dockerfile
  scripts/docker/debian/sid/Dockerfile
  scripts/docker/debian/stretch/Dockerfile
  scripts/docker/jenkinsnode/Dockerfile
  scripts/generate-haskell-dependencies
  scripts/generate-haskell-dependencies.hs
  src/bindings/haskell/CMakeLists.txt
  src/bindings/haskell/README.md
  src/bindings/haskell/libelektra-haskell.cabal.in
  src/libs/CMakeLists.txt
  src/libs/typesystem/libfa/libfa.cabal.in
  src/libs/typesystem/specelektra/Elektra/RegexTypeChecker.hs
  src/libs/typesystem/specelektra/specelektra.cabal.in
  src/libs/typesystem/spectranslator/spectranslator.cabal.in
  src/plugins/haskell/Setup.hs.in
  src/plugins/haskell/haskell.cabal.in
  src/plugins/typechecker/CMakeLists.txt
  src/plugins/typechecker/Elektra/Typechecker.hs.in
  src/plugins/typechecker/README.md
  src/plugins/typechecker/sandbox/sandbox.cabal.in
  src/plugins/typechecker/typechecker.cabal.in
  tests/shell/check_bashisms.sh
Labels: ready to merge

#2003 Jenkinsfile misc
  cmake/ElektraCache.cmake
  doc/BUILDSERVER.md
  doc/COMPILE.md
  doc/GIT.md
  doc/TESTING.md
  doc/news/_preparation_next_release.md
  doc/todo/TESTING
  scripts/docker/debian/jessie/Dockerfile
  scripts/docker/debian/sid/Dockerfile
  scripts/docker/debian/stretch/Dockerfile
  scripts/docker/debian/stretch/Dockerfile.doc
  scripts/docker/debian/stretch/Dockerfile.minimal
  scripts/docker/homepage/backend/Dockerfile
  scripts/docker/homepage/frontend/Dockerfile
  scripts/docker/ubuntu/xenial/Dockerfile
  scripts/jenkins/Jenkinsfile
  src/bindings/swig/lua/CMakeLists.txt
  src/plugins/lua/CMakeLists.txt
  src/plugins/range/CMakeLists.txt
  src/plugins/xerces/CMakeLists.txt
  tests/shell/check_formatting.sh
  tests/shell/check_kdb_internal_check.sh
Labels: build, ready to merge
