Repository ElektraInitiative/libelektra, pull requests merged in 2019-07, with the labels that each got.

#2818 Fixed Typos in `cassandra.ini` (Updated Version of PR #2495)
  doc/news/_preparation_next_release.md
  examples/spec/cassandra.ini
Labels: cm2019s, enhancement, work in progress

#2822 cache: fix GCC ASAN Build Warnings, closes #2820
  doc/news/_preparation_next_release.md
  src/plugins/cache/cache.c
Labels: ready to merge

#2830 Shell Tests: Improve Support for Space Chars in Directory Paths
  doc/news/_preparation_next_release.md
  tests/shell/check_real_world.sh
  tests/shell/check_resolver.sh
  tests/shell/check_spec.sh
  tests/shell/include_common.sh.in
Labels: bug, lang/shell, ready to merge

#2829 UBSan: Fix Implicit Type Conversions
  doc/news/_preparation_next_release.md
  src/libs/elektra/kdb.c
  src/libs/elektra/keymeta.c
  src/libs/elektra/keyname.c
  src/libs/elektra/keyset.c
  src/libs/elektra/keyvalue.c
  src/plugins/base64/base64_functions.c
  src/plugins/filecheck/filecheck.c
Labels: enhancement, lang/c, ready to merge

#2828 Yan LR: Fix End Position of Map Start Tokens
  doc/news/_preparation_next_release.md
  src/plugins/yanlr/yaml_lexer.cpp
Labels: bug, lang/cpp, ready to merge

#2824 Enable PROCGETSTORAGE on CACHE_HIT
  doc/news/_preparation_next_release.md
  src/libs/elektra/kdb.c
Labels: ready to merge

#2819 Docker: Add Images for Debian buster
  doc/news/_preparation_next_release.md
  scripts/docker/debian/buster/Dockerfile
  scripts/docker/debian/buster/doc.Dockerfile
  scripts/docker/debian/buster/i386.Dockerfile
  scripts/docker/debian/buster/minimal.Dockerfile
  scripts/docker/debian/stretch/doc.Dockerfile
  scripts/docker/debian/stretch/i386.Dockerfile
  scripts/docker/debian/stretch/minimal.Dockerfile
  scripts/jenkins/Jenkinsfile
  src/plugins/yamlcpp/CMakeLists.txt
  src/plugins/yanlr/CMakeLists.txt
  tests/sanitizer.blacklist
Labels: enhancement, ready to merge

#2340 tests: check getenv
  doc/news/_preparation_next_release.md
  tests/shell/include_common.sh.in
Labels: ready to merge
