Repository ElektraInitiative/libelektra, pull requests merged in 2019-09, with the labels that each got.

#2923 Link checker: deduplicate links
  doc/news/_preparation_next_release.md
  scripts/link-checker
  tests/linkchecker.whitelist
Labels: ready to merge

#2921 kdb check: added checks for kdbCommit
  doc/news/_preparation_next_release.md
  src/libs/tools/include/plugin.hpp
  src/libs/tools/src/plugin.cpp
  src/plugins/blockresolver/blockresolver.c
  src/plugins/curlget/curlget.c
  src/plugins/gitresolver/gitresolver.c
  src/plugins/multifile/multifile.c
  src/plugins/resolver/contract.h
Labels: ready to merge

#2931 Tcl: Fix Name of Boost Include Directory
  doc/news/_preparation_next_release.md
  src/plugins/tcl/CMakeLists.txt
Labels: bug, build, lang/cmake, ready to merge

#2929 Check Formatting: Change Code Difference Detection
  doc/news/_preparation_next_release.md
  tests/shell/check_formatting.sh
Labels: bug, lang/shell, ready to merge

#2933 Minor changes to codegen
  cmake/ElektraConfig.cmake.in
  doc/help/elektra-highlevel-gen.md
  doc/help/kdb-gen-highlevel.md
  doc/man/man1/kdb-gen-highlevel.1
  doc/man/man7/elektra-highlevel-gen.7
  doc/man/man7/elektra-plugins.7
  doc/news/_preparation_next_release.md
  doc/tutorials/application-integration.md
  src/tools/kdb/gen/highlevel/enums.cpp
  src/tools/kdb/gen/highlevel/enums.hpp
  src/tools/kdb/gen/highlevel/highlevel.cpp
Labels: ready to merge

#2936 Restyled: Check Formatting of Markdown Code
  .restyled.yaml
  doc/news/_preparation_next_release.md
Labels: enhancement

#2934 Build: Fix Format Specifier for `st_size` on macOS
  .cirrus.yml
  doc/news/_preparation_next_release.md
  src/include/CMakeLists.txt
Labels: bug, build, lang/c, lang/cmake

#2942 Minor documentation updates
  cmake/ElektraConfig.cmake.in
  doc/help/elektra-highlevel-gen.md
  doc/news/_preparation_next_release.md
Labels: ready to merge

#2946 ksAppendKey: fix deletion on resizing
  doc/news/_preparation_next_release.md
  src/libs/elektra/keyset.c
Labels: ready to merge

#2935 CMake: Simplify Code for Shell Tests & Shell Recorder
  doc/news/_preparation_next_release.md
  tests/CMakeLists.txt
  tests/shell/CMakeLists.txt
  tests/shell/external/CMakeLists.txt
  tests/shell/include_common.sh.in
  tests/shell/shell_recorder/CMakeLists.txt
  tests/shell/shell_recorder/shell_recorder.sh
Labels: build, cleanup, lang/cmake, lang/shell, ready to merge

#2930 Rust KeySet Binding
  doc/news/_preparation_next_release.md
  src/bindings/rust/CMakeLists.txt
  src/bindings/rust/Cargo.toml
  src/bindings/rust/README.md
  src/bindings/rust/elektra/Cargo.toml.in
  src/bindings/rust/elektra/src/key.rs
  src/bindings/rust/elektra/src/keybuilder.rs
  src/bindings/rust/elektra/src/keyset.rs
  src/bindings/rust/elektra/src/lib.rs
  src/bindings/rust/elektra/src/readable.rs
  src/bindings/rust/elektra/src/readonly.rs
  src/bindings/rust/elektra/src/writable.rs
  src/bindings/rust/example/Cargo.lock
  src/bindings/rust/example/Cargo.toml.in
  src/bindings/rust/example/src/bin/key.rs
  src/bindings/rust/example/src/bin/keyset.rs
Labels: ready to merge

#2940 Scripts: Remove YAML Benchmark Script
  doc/news/2019-08-06_0.9.0.md
  doc/news/_preparation_next_release.md
  scripts/CMakeLists.txt
  scripts/benchmark-yaml.in
Labels: cleanup, lang/shell, ready to merge

#2966 News: Fix Broken Links
  doc/man/man7/elektra-highlevel-gen.7
  doc/news/2014-11-04_0.8.9.md
  doc/news/2016-02-16_0.8.15.md
  doc/news/2018-08-18_0.8.24.md
  doc/news/2018-11-18_0.8.25.md
  doc/news/2019-02-26_0.8.26.md
  doc/news/2019-08-06_0.9.0.md
  doc/news/_preparation_next_release.md
Labels: cleanup, lang/markdown, ready to merge

#2968 Camel: Remove Plugin
  .travis.yml
  doc/images/flamegraph.svg
  doc/images/plugins.dot
  doc/images/plugins.png
  doc/man/man7/elektra-plugins.7
  doc/news/2017-10-31_0.8.20.md
  doc/news/2017-12-22_0.8.21.md
  doc/news/2019-02-26_0.8.26.md
  doc/news/_preparation_next_release.md
  doc/tutorials/profiling.md
  scripts/cmake/Modules/FindYAEP.cmake
  scripts/deploy/website
  scripts/docker/ubuntu/disco/Dockerfile
  scripts/docker/website/backend/Dockerfile
  scripts/docker/website/frontend/Dockerfile
  src/plugins/README.md
  src/plugins/camel/CMakeLists.txt
  src/plugins/camel/README.md
  src/plugins/camel/camel.c
  src/plugins/camel/camel.h
  src/plugins/camel/camel/camel.abnf
  src/plugins/camel/camel/simple.yaml
  src/plugins/camel/testmod_camel.c
  tests/shell/check_oclint.sh
Labels: cleanup, lang/c, ready to merge

#2945 Rust KDB Binding
  doc/news/_preparation_next_release.md
  src/bindings/README.md
  src/bindings/rust/README.md
  src/bindings/rust/elektra/src/kdb.rs
  src/bindings/rust/elektra/src/lib.rs
  src/bindings/rust/example/src/bin/kdb.rs
Labels: ready to merge

#2975 Plugins: Unify Name of Configuration Check Function
  doc/man/man7/elektra-plugins.7
  doc/news/_preparation_next_release.md
  doc/tutorials/plugins.md
  src/plugins/README.md
  src/plugins/c/c.c
  src/plugins/c/c.h
  src/plugins/cpptemplate/cpptemplate.cpp
  src/plugins/cpptemplate/cpptemplate.hpp
  src/plugins/multifile/multifile.c
  src/plugins/multifile/multifile.h
  src/plugins/process/process.c
  src/plugins/process/process.h
  src/plugins/reference/reference.h
  src/plugins/specload/specload.c
  src/plugins/specload/specload.h
  src/plugins/specload/testmod_specload.c
  src/plugins/template/template.c
  src/plugins/template/template.h
Labels: cleanup, lang/c, ready to merge

#2974 opts: remove -h as help mode option
  doc/decisions/highlevel_help_message.md
  doc/news/_preparation_next_release.md
  doc/tutorials/command-line-options.md
  src/libs/opts/opts.c
  src/plugins/gopts/gopts.c
  src/tools/kdb/gen/highlevel/highlevel.cpp
  tests/ctest/test_opts.c
Labels: ready to merge

#2972 Jenkins: Do Not Auto Cancel `master` Build Jobs
  doc/news/_preparation_next_release.md
  scripts/jenkins/Jenkinsfile
Labels: continuous integration, enhancement, lang/groovy, ready to merge

#2977 Documentation: Update Restrictions of Yan LR
  doc/news/_preparation_next_release.md
  src/plugins/specload/testmod_specload.c
  src/plugins/yanlr/README.md
Labels: enhancement, lang/markdown, ready to merge

#2985 Fix Spelling: Move Script to Correct Location
  doc/man/man7/elektra-plugins.7
  doc/news/_preparation_next_release.md
  scripts/dev/fix-spelling
Labels: bug, cleanup, ready to merge

#3000 spec: minor change to error handling
  doc/news/_preparation_next_release.md
  src/plugins/spec/spec.c
Labels: ready to merge

#2998 Metadata: Remove Outdated Information
  doc/METADATA.ini
  doc/news/_preparation_next_release.md
  doc/tutorials/highlevel-bindings.md
  src/tools/website-frontend/Gruntfile.js
Labels: cleanup, ready to merge

#2950 Error improvements
  doc/decisions/error_codes.md
  doc/news/_preparation_next_release.md
  scripts/docker/webui/elektrad-demo/realworld.ini
  src/include/kdbmacros.h
  src/libs/elektra/kdb.c
  src/plugins/augeas/README.md
  src/plugins/crypto/README.md
  src/plugins/dump/dump.cpp
  src/plugins/error/README.md
  src/plugins/network/network.c
  src/plugins/path/path.c
  src/plugins/python/python.cpp
  src/plugins/type/README.md
  src/plugins/type/type.c
  src/plugins/validation/validation.c
  src/plugins/yajl/README.md
Labels: ready to merge

#2854 Jna error code and plugin usage
  doc/news/_preparation_next_release.md
  src/bindings/jna/CMakeLists.txt
  src/bindings/jna/README.md
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/Elektra.java
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/KDB.java
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/Key.java
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/KeyNameIterator.java
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/KeySet.java
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/KeySetIterator.java
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/KeyUtils.java
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/Plugin.java
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/PluginLoader.java
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/exception/ConflictingStateException.java
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/exception/InstallationException.java
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/exception/InterfaceException.java
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/exception/InternalException.java
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/exception/KDBException.java
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/exception/LogicalException.java
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/exception/OutOfMemoryException.java
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/exception/PermanentException.java
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/exception/PluginMisbehaviorException.java
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/exception/ResourceException.java
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/exception/SemanticValidationException.java
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/exception/SyntacticValidationException.java
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/exception/ValidationException.java
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/exception/mapper/ExceptionMapperService.java
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/exception/model/WarningEntry.java
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/plugin/Echo.java
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/plugin/ExceptionTest.java
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/plugin/NativePlugin.java
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/plugin/PropertiesStorage.java
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/plugin/Return.java
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/plugin/Template.java
  src/bindings/jna/libelektra4j/src/test/java/org/libelektra/AllTests.java
  src/bindings/jna/libelektra4j/src/test/java/org/libelektra/ExceptionMapperIT.java
  src/bindings/jna/libelektra4j/src/test/java/org/libelektra/ExceptionMapperTest.java
  src/bindings/jna/libelektra4j/src/test/java/org/libelektra/KDBExceptionTest.java
  src/bindings/jna/libelektra4j/src/test/java/org/libelektra/KDBTest.java
  src/bindings/jna/libelektra4j/src/test/java/org/libelektra/KeySetTest.java
  src/bindings/jna/libelektra4j/src/test/java/org/libelektra/KeyTest.java
  src/bindings/jna/libelektra4j/src/test/java/org/libelektra/PluginLoaderIT.java
  src/bindings/jna/libelektra4j/src/test/java/org/libelektra/exception/model/WarningEntryTest.java
Labels: ready to merge

#1950 rest-frontend: add PID file config setting
  doc/decisions/README.md
  doc/decisions/array.md
  doc/decisions/boolean.md
  doc/decisions/cmake_plugins.md
  doc/decisions/cmake_spec.md
  doc/decisions/elektra_web_pubsub.md
  doc/decisions/global_validation.md
  doc/decisions/holes.md
  doc/decisions/internal_cache.md
  doc/decisions/null_pointer_checks.md
  doc/decisions/plugin_variants.md
  doc/decisions/rest_api_documentation.md
  doc/decisions/unit_testing.md
  doc/man/man1/kdb-run-website-frontend.1
  doc/news/2019-08-06_0.9.0.md
  doc/news/_preparation_next_release.md
  doc/tutorials/storage-plugins.md
  src/plugins/yamlcpp/README.md
  src/tools/website-frontend/README.md
  src/tools/website-frontend/run.sh
Labels: ready to merge

#3013 CMake: Print Warning About Missing Man Pages
  doc/news/_preparation_next_release.md
  scripts/cmake/Modules/LibAddMacros.cmake
Labels: enhancement, lang/cmake, ready to merge

#2978 doc: Fix typos in documentation
  doc/news/_preparation_next_release.md
  examples/ksIterate.c
  src/libs/elektra/kdb.c
  src/libs/elektra/key.c
  src/libs/elektra/keymeta.c
  src/libs/elektra/keyname.c
  src/libs/elektra/keyset.c
Labels: ready to merge

#3012 Yajl: Support Elektra booleans
  doc/news/_preparation_next_release.md
  src/plugins/yajl/README.md
  src/plugins/yajl/testmod_yajl.c
  src/plugins/yajl/yajl_gen.c
  src/plugins/yajl/yajl_parse.c
Labels: ready to merge

#3010 Kdb showmeta
  doc/help/kdb-showmeta.md
  doc/man/man1/kdb-showmeta.1
  doc/news/_preparation_next_release.md
  src/tools/kdb/factory.hpp
  src/tools/kdb/showmeta.cpp
  src/tools/kdb/showmeta.hpp
  tests/shell/shell_recorder/tutorial_wrapper/CMakeLists.txt
Labels: ready to merge
