Repository ElektraInitiative/libelektra, pull requests merged in 2019-05, with the labels that each got.

#2641 Documentation: Add Benchmark & Profiling Tutorial
  benchmarks/README.md
  benchmarks/data/test.yaml
  benchmarks/plugingetset.c
  doc/images/qcachegrind.png
  doc/markdownlinkconverter/elektraSpecialCharacters.sty
  doc/news/_preparation_next_release.md
  doc/tutorials/README.md
  doc/tutorials/benchmarking.md
  doc/tutorials/profiling.md
  scripts/CMakeLists.txt
  scripts/benchmark-yaml.in
  scripts/docker/debian/sid/Dockerfile
  scripts/jenkins/Jenkinsfile
Labels: enhancement, lang/shell, ready to merge

#2649 YAML Smith: Fix Conversion of Keys with Common Prefix
  doc/news/_preparation_next_release.md
  src/plugins/yamlsmith/README.md
  src/plugins/yamlsmith/yamlsmith.cpp
Labels: bug, lang/cpp, ready to merge

#2650 YAML CPP: Improve Support for Mixed Data
  doc/news/_preparation_next_release.md
  src/error/specification
  src/plugins/directoryvalue/directoryvalue.cpp
  src/plugins/yamlcpp/read.cpp
  src/plugins/yamlcpp/testmod_yamlcpp.cpp
  src/plugins/yamlcpp/yamlcpp.cpp
  src/plugins/yamlcpp/yamlcpp/mixed.h
  src/plugins/yamlcpp/yamlcpp/mixed.yaml
Labels: bug, enhancement, lang/cpp, ready to merge

#2651 YAwn: Support Elektra’s Boolean Data Type
  doc/news/_preparation_next_release.md
  src/plugins/yawn/README.md
  src/plugins/yawn/listener.cpp
Labels: enhancement, lang/cpp, ready to merge

#2652 YAMBi: Support Elektra’s Boolean Data Type
  doc/news/_preparation_next_release.md
  src/plugins/yambi/README.md
  src/plugins/yambi/driver.cpp
Labels: enhancement, lang/cpp, ready to merge

#2653 Yan LR: Support Elektra’s Boolean Data Type
  doc/news/_preparation_next_release.md
  src/plugins/yanlr/README.md
  src/plugins/yanlr/listener.cpp
Labels: enhancement, lang/cpp, ready to merge

#2655 YAML Smith: Support Elektra’s Boolean Data Type
  doc/news/_preparation_next_release.md
  src/plugins/yamlsmith/README.md
  src/plugins/yamlsmith/yamlsmith.cpp
Labels: enhancement, lang/cpp, ready to merge

#2654 YAy PEG: Support Elektra’s Boolean Data Type
  doc/news/_preparation_next_release.md
  src/plugins/yaypeg/README.md
  src/plugins/yaypeg/listener.cpp
Labels: enhancement, lang/cpp, ready to merge

#2659 Website: Fix Convert Engine Test
  doc/news/_preparation_next_release.md
  src/tools/rest-backend/tests/test_service_convertengine.cpp
Labels: bug, build, lang/cpp, ready to merge

#2661 error: removed `ingroup` metadata
  doc/decisions/README.md
  doc/decisions/ingroup_removal.md
  doc/dev/error-handling.md
  doc/news/_preparation_next_release.md
  src/bindings/cpp/examples/cpp_example_userio.cpp
  src/bindings/cpp/include/kdbio.hpp
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/Key.java
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/KeyUtils.java
  src/error/exporterrors.cpp
  src/libs/elektra/kdb.c
  src/plugins/augeas/README.md
  src/plugins/conditionals/README.md
  src/plugins/crypto/README.md
  src/plugins/doc/doc.c
  src/plugins/mathcheck/README.md
  src/plugins/yambi/README.md
  src/plugins/yanlr/README.md
  src/plugins/yawn/README.md
  src/plugins/yaypeg/README.md
  src/tools/kdb/coloredkdbio.hpp
  src/tools/web/kdb.js
  tests/cframework/tests.c
Labels: ready to merge

#2662 Yan LR: Fix Conversion of Empty Values
  doc/news/_preparation_next_release.md
  src/plugins/yanlr/README.md
  src/plugins/yanlr/listener.cpp
  src/plugins/yanlr/yaml_lexer.cpp
  src/plugins/yanlr/yanlr/map-null.hpp
Labels: bug, enhancement, lang/cpp, ready to merge

#2663 YAMBi: Fix Conversion of Empty Values
  doc/news/_preparation_next_release.md
  src/plugins/yambi/driver.cpp
  src/plugins/yambi/lexer.cpp
  src/plugins/yambi/yambi/map-null.hpp
Labels: bug, enhancement, lang/cpp, ready to merge

#2664 YAwn: Fix Conversion of Empty Values
  doc/news/_preparation_next_release.md
  src/plugins/yawn/lexer.cpp
  src/plugins/yawn/listener.cpp
  src/plugins/yawn/yawn/map-null.hpp
Labels: bug, enhancement, lang/cpp, ready to merge

#2665 YAy PEG: Convert Empty YAML Values to Null Keys
  doc/news/_preparation_next_release.md
  src/plugins/yaypeg/listener.cpp
  src/plugins/yaypeg/yaypeg/map-null.hpp
Labels: enhancement, lang/cpp, ready to merge

#2411 Plugins: semlock: remove it
  .travis.yml
  doc/news/_preparation_next_release.md
  doc/todo/PLUGINS
  doc/todo/TESTING
  scripts/build-homepage
  scripts/docker/homepage/backend/Dockerfile
  scripts/docker/homepage/frontend/Dockerfile
  src/plugins/README.md
  src/plugins/semlock/CMakeLists.txt
  src/plugins/semlock/README.md
  src/plugins/semlock/semlock.c
  src/plugins/semlock/semlock.h
  src/plugins/semlock/testmod_semlock.c
  tests/shell/check_kdb_internal_check.sh
  tests/valgrind.suppression
Labels: ready to merge

#2666 Python Tutorial: Alpine Linux instruction for Python bindings
  doc/INSTALL.md
  doc/news/_preparation_next_release.md
  doc/tutorials/python-kdb.md
Labels: cm2019s, enhancement, ready to merge

#2675 Cirrus: Add Link Checker Build Job
  .cirrus.yml
  doc/help/elektra-namespaces.md
  doc/markdownlinkconverter/elektraSpecialCharacters.sty
  doc/markdownlinkconverter/markdownlinkconverter.c
  doc/news/2014-06-21_0.8.6.md
  doc/news/2014-07-28_0.8.7.md
  doc/news/2016-06-14_0.8.17.md
  doc/news/2017-03-18_lcdproc.md
  doc/news/2017-12-22_0.8.21.md
  doc/news/2018-03-27_0.8.22.md
  doc/news/2018-05-13_0.8.23.md
  doc/news/_preparation_next_release.md
  doc/tutorials/profiling.md
  doc/tutorials/storage-plugins.md
  scripts/docker/cirrus/Dockerfile
  scripts/link-checker
Labels: enhancement, lang/c, lang/shell, ready to merge

#2667 Benchmark: Extend YAML Benchmark Script
  benchmarks/data/test.yaml
  doc/news/_preparation_next_release.md
  doc/tutorials/benchmarking.md
  doc/tutorials/profiling.md
  scripts/benchmark-yaml.in
  scripts/generate-yaml
Labels: lang/python, lang/shell, ready to merge

#2679 Travis: Ignore Warnings Reported by GCC 9.1
  .travis.yml
  README.md
  doc/WHY.md
  doc/news/2014-07-28_0.8.7.md
  doc/news/2016-02-16_0.8.15.md
  doc/news/2016-06-14_0.8.17.md
  doc/news/_preparation_next_release.md
  doc/tutorials/README.md
  doc/tutorials/application-integration.md
Labels: bug, build, ready to merge

#2493 CM: Fix Typo
  doc/tutorials/validation.md
Labels: cm2019s, enhancement

#2683 Travis: Fix Warnings Reported by GCC 9
  .travis.yml
  doc/COMPILE.md
  doc/news/_preparation_next_release.md
  src/bindings/cpp/include/kdbvalue.hpp
  src/plugins/mini/testmod_mini.c
Labels: bug, build, lang/c, lang/cpp, ready to merge

#2689 Documentation: Explain How to Format C/C++ Code With Clang-Format
  doc/CODING.md
  doc/markdownlinkconverter/elektraSpecialCharacters.sty
  doc/news/_preparation_next_release.md
  scripts/reformat-source
Labels: enhancement, ready to merge

#2691 Include Common: Fix Broken Shell Variables
  doc/news/_preparation_next_release.md
  tests/shell/include_common.sh.in
Labels: bug, lang/shell, ready to merge

#2693 Shell Recorder: Fix Incorrect CMake Command Arguments
  doc/help/kdb-get.md
  doc/man/man1/kdb-get.1
  doc/news/_preparation_next_release.md
  tests/shell/shell_recorder/tutorial_wrapper/CMakeLists.txt
Labels: build, lang/cmake, ready to merge

#2658 WIP: Yajl: Empty arrays with metakey
  doc/news/_preparation_next_release.md
  src/plugins/yajl/testmod_yajl.c
  src/plugins/yajl/yajl_gen.c
  src/plugins/yajl/yajl_parse.c
Labels: cm2019s, enhancement, lang/c, ready to merge

#2684 error: splitted error_message document, added error message format
  doc/decisions/README.md
  doc/decisions/error_codes.md
  doc/decisions/error_message_format.md
  doc/decisions/ingroup_removal.md
  doc/news/_preparation_next_release.md
Labels: ready to merge

#2703 disable cache plugin, add regression tests
  doc/news/_preparation_next_release.md
  src/libs/elektra/mount.c
  src/plugins/cache/shelltests.md
  tests/shell/shell_recorder/tutorial_wrapper/CMakeLists.txt
Labels: ready to merge

#2701 Yajl: Remove additional dirdata entry in arrays
  doc/news/_preparation_next_release.md
  src/plugins/yajl/README.md
  src/plugins/yajl/testmod_yajl.c
  src/plugins/yajl/yajl_parse.c
Labels: cm2019s, enhancement, lang/c

#2549 WIP: Hexcolor plugin
  doc/METADATA.ini
  doc/news/_preparation_next_release.md
  src/error/specification
  src/plugins/README.md
  src/plugins/rgbcolor/CMakeLists.txt
  src/plugins/rgbcolor/README.md
  src/plugins/rgbcolor/rgbcolor.c
  src/plugins/rgbcolor/rgbcolor.h
  src/plugins/rgbcolor/testmod_rgbcolor.c
Labels: cm2019s, enhancement, lang/c, ready to merge

#2687 Added tutorial for newcomers contributing to libelektra using CLion
  .github/CONTRIBUTING.md
  doc/news/_preparation_next_release.md
  doc/tutorials/contributing-clion.md
Labels: cm2019s, enhancement

#2714 YAy PEG: Convert Empty File to Empty Parent Key
  doc/news/_preparation_next_release.md
  src/plugins/yaypeg/listener.cpp
  src/plugins/yaypeg/listener.hpp
  src/plugins/yaypeg/testmod_yaypeg.cpp
  src/plugins/yaypeg/walk.cpp
  src/plugins/yaypeg/yaypeg/null.hpp
Labels: enhancement, lang/cpp, ready to merge

#2713 YAwn: Convert Empty File to Empty Parent Key
  doc/news/_preparation_next_release.md
  src/plugins/yawn/CMakeLists.txt
  src/plugins/yawn/listener.cpp
  src/plugins/yawn/listener.hpp
  src/plugins/yawn/testmod_yawn.cpp
  src/plugins/yawn/walk.cpp
  src/plugins/yawn/yaml.bnf
  src/plugins/yawn/yawn/null.hpp
Labels: enhancement, lang/cpp, ready to merge

#2711 Yan LR: Convert Empty File to Empty Parent Key
  doc/news/_preparation_next_release.md
  src/plugins/yanlr/YAML.g4
  src/plugins/yanlr/error_listener.cpp
  src/plugins/yanlr/listener.cpp
  src/plugins/yanlr/listener.hpp
  src/plugins/yanlr/testmod_yanlr.cpp
  src/plugins/yanlr/yanlr/null.hpp
Labels: enhancement, lang/cpp, ready to merge

#2712 YAMBi: Convert Empty File to Empty Parent Key
  doc/news/_preparation_next_release.md
  src/plugins/yambi/driver.cpp
  src/plugins/yambi/driver.hpp
  src/plugins/yambi/parser.ypp
  src/plugins/yambi/testmod_yambi.cpp
  src/plugins/yambi/yambi/null.hpp
Labels: enhancement, lang/cpp, ready to merge

#2704 Error message implementation
  doc/decisions/error_message_format.md
  doc/help/kdb.md
  doc/news/_preparation_next_release.md
  doc/tutorials/validation.md
  src/bindings/cpp/README.md
  src/bindings/cpp/examples/cpp_example_io.cpp
  src/bindings/cpp/examples/cpp_example_userio.cpp
  src/bindings/cpp/include/kdbexcept.hpp
  src/bindings/cpp/include/kdbio.hpp
  src/libs/tools/include/toolexcept.hpp
  src/plugins/augeas/README.md
  src/plugins/conditionals/README.md
  src/plugins/cpptype/README.md
  src/plugins/crypto/README.md
  src/plugins/mathcheck/README.md
  src/plugins/mini/README.md
  src/plugins/network/README.md
  src/plugins/reference/README.md
  src/plugins/yambi/README.md
  src/plugins/yanlr/README.md
  src/plugins/yawn/README.md
  src/plugins/yaypeg/README.md
  src/tools/kdb/check.cpp
  src/tools/kdb/coloredkdbio.hpp
  src/tools/kdb/complete.cpp
  src/tools/kdb/convert.cpp
  src/tools/kdb/editor.cpp
  src/tools/kdb/export.cpp
  src/tools/kdb/find.cpp
  src/tools/kdb/fstab.cpp
  src/tools/kdb/gen.cpp
  src/tools/kdb/get.cpp
  src/tools/kdb/globalumount.cpp
  src/tools/kdb/import.cpp
  src/tools/kdb/ls.cpp
  src/tools/kdb/main.cpp
  src/tools/kdb/metaget.cpp
  src/tools/kdb/metals.cpp
  src/tools/kdb/metaremove.cpp
  src/tools/kdb/metaset.cpp
  src/tools/kdb/mountbase.cpp
  src/tools/kdb/mv.cpp
  src/tools/kdb/set.cpp
  src/tools/kdb/set.hpp
  src/tools/kdb/test.cpp
  src/tools/kdb/umount.cpp
  src/tools/qt-gui/src/treeviewmodel.cpp
  src/tools/web/kdb.js
  tests/kdb/testkdb_conflict.cpp
  tests/kdb/testkdb_simple.cpp
  tests/shell/check_error.sh
  tests/shell/shell_recorder/shell_recorder.sh
Labels: ready to merge

#2719 YAML Benchmark Script: Export Result in JSON Format
  doc/news/_preparation_next_release.md
  scripts/benchmark-yaml.in
  scripts/docker/debian/sid/Dockerfile
  scripts/generate-yaml
Labels: enhancement, lang/shell, ready to merge

#2682 Error categorization guidelines & design decision splitup
  doc/decisions/error_codes.md
  doc/dev/README.md
  doc/dev/error-categorization.md
  doc/news/_preparation_next_release.md
Labels: ready to merge

#2728 Documentation: Explain How to Format Markdown Code With Prettier
  doc/CODING.md
  doc/news/_preparation_next_release.md
  scripts/sed
Labels: enhancement, ready to merge

#2731 Documentation: Explain How to Format Shell Code With shfmt
  doc/CODING.md
  doc/news/_preparation_next_release.md
Labels: enhancement, ready to merge

#2721 doc: added section on elektraPluginGetGlobalKeySet to plugin tutorial
  doc/news/_preparation_next_release.md
  doc/tutorials/plugins.md
Labels: ready to merge

#2734 Reformat All: Support Spaces Inside Format Script Paths
  doc/news/_preparation_next_release.md
  scripts/reformat-all
Labels: enhancement, lang/shell, ready to merge
