Repository ElektraInitiative/libelektra, pull requests merged in 2019-01, with the labels that each got.

#2311 Network: Port Check Extension
  doc/METADATA.ini
  doc/news/_preparation_next_release.md
  src/error/specification
  src/plugins/network/README.md
  src/plugins/network/network.c
  src/plugins/network/network.h
  src/plugins/network/testmod_network.c
Labels: enhancement, ready to merge

#2319 Cirrus CI: Test Elektra on FreeBSD
  .cirrus.yml
  .github/ISSUE_TEMPLATE.md
  README.md
  doc/news/_preparation_next_release.md
  doc/todo/NEWS.md
  src/plugins/camel/camel.c
  src/plugins/csvstorage/README.md
  src/plugins/directoryvalue/README.md
  src/plugins/line/line.c
  src/plugins/mini/README.md
  src/plugins/mini/mini.c
  src/plugins/network/network.h
  src/plugins/resolver/filename.c
  tests/shell/shell_recorder/shell_recorder.sh
Labels: build, enhancement, ready to merge

#2314 YAy PEG: New Plugin Based on PEGTL
  .travis.yml
  cmake/Modules/FindAugeas.cmake
  cmake/Modules/FindLua.cmake
  cmake/Modules/FindPEGTL.cmake
  doc/CODING.md
  doc/news/2018-11-18_0.8.25.md
  doc/news/_preparation_next_release.md
  scripts/docker/debian/sid/Dockerfile
  scripts/docker/debian/stretch/Dockerfile
  scripts/vagrant/ubuntu/artful32/Vagrantfile
  src/plugins/README.md
  src/plugins/yawn/README.md
  src/plugins/yaypeg/CMakeLists.txt
  src/plugins/yaypeg/README.md
  src/plugins/yaypeg/convert.cpp
  src/plugins/yaypeg/convert.hpp
  src/plugins/yaypeg/listener.cpp
  src/plugins/yaypeg/listener.hpp
  src/plugins/yaypeg/parser.hpp
  src/plugins/yaypeg/state.cpp
  src/plugins/yaypeg/state.hpp
  src/plugins/yaypeg/testmod_yaypeg.cpp
  src/plugins/yaypeg/walk.cpp
  src/plugins/yaypeg/walk.hpp
  src/plugins/yaypeg/yaypeg.cpp
  src/plugins/yaypeg/yaypeg.hpp
  src/plugins/yaypeg/yaypeg/comment.yaml
  src/plugins/yaypeg/yaypeg/double_quoted_scalar.hpp
  src/plugins/yaypeg/yaypeg/double_quoted_scalar.yaml
  src/plugins/yaypeg/yaypeg/list-list_map-mixed_scalars.hpp
  src/plugins/yaypeg/yaypeg/list-list_map-mixed_scalars.yaml
  src/plugins/yaypeg/yaypeg/list-plain_scalars.hpp
  src/plugins/yaypeg/yaypeg/list-plain_scalars.yaml
  src/plugins/yaypeg/yaypeg/map-list-plain_scalars.hpp
  src/plugins/yaypeg/yaypeg/map-list-plain_scalars.yaml
  src/plugins/yaypeg/yaypeg/map-map-plain_scalars.hpp
  src/plugins/yaypeg/yaypeg/map-map-plain_scalars.yaml
  src/plugins/yaypeg/yaypeg/map-null.hpp
  src/plugins/yaypeg/yaypeg/map-null.yaml
  src/plugins/yaypeg/yaypeg/map-plain_scalar.hpp
  src/plugins/yaypeg/yaypeg/map-plain_scalar.yaml
  src/plugins/yaypeg/yaypeg/map-plain_scalars.hpp
  src/plugins/yaypeg/yaypeg/map-plain_scalars.yaml
  src/plugins/yaypeg/yaypeg/null.hpp
  src/plugins/yaypeg/yaypeg/null.yaml
  src/plugins/yaypeg/yaypeg/plain_scalar-word_chars.hpp
  src/plugins/yaypeg/yaypeg/plain_scalar-word_chars.yaml
  src/plugins/yaypeg/yaypeg/plain_scalar-word_chars_space.hpp
  src/plugins/yaypeg/yaypeg/plain_scalar-word_chars_space.yaml
  src/plugins/yaypeg/yaypeg/single_quoted_scalar.hpp
  src/plugins/yaypeg/yaypeg/single_quoted_scalar.yaml
  src/tools/gen/support/__init__.pyc
  src/tools/gen/support/c.pyc
  src/tools/gen/support/cpp.pyc
  src/tools/gen/support/elektra_gen.pyc
  src/tools/gen/support/gen.pyc
  src/tools/gen/support/util.pyc
  tests/shell/check_oclint.sh
Labels: enhancement, ready to merge

#2308 MemCheck: fix detection of memory problems
  cmake/ElektraCache.cmake
  doc/news/_preparation_next_release.md
  scripts/CMakeLists.txt
  scripts/jenkins/Jenkinsfile
  scripts/run_memcheck
  scripts/run_memcheck.in
  scripts/run_nokdbtests
  scripts/run_nokdbtests.in
  src/libs/pluginprocess/tests/testlib_pluginprocess.c
  tests/CMakeLists.txt
  tests/valgrind.suppression
Labels: ready to merge

#2325 Jenkins: Add Status Badge to ReadMe
  README.md
  doc/news/_preparation_next_release.md
Labels: enhancement, low priority, ready to merge

#2324 MSR Tests & Cirrus CI Updates
  .cirrus.yml
  .travis.yml
  doc/help/kdb-complete.md
  doc/help/kdb-find.md
  doc/help/kdb-ls.md
  doc/news/_preparation_next_release.md
  doc/tutorials/cascading.md
  doc/tutorials/validation.md
  scripts/check-env-dep
  scripts/docker/debian/stretch/Dockerfile
  scripts/mount-list-all-files
  src/plugins/conditionals/README.md
  src/plugins/dini/README.md
  src/plugins/enum/README.md
  src/plugins/hosts/CMakeLists.txt
  src/plugins/ini/README.md
  src/plugins/line/README.md
  src/plugins/mathcheck/README.md
  src/plugins/mozprefs/README.md
  src/plugins/yajl/README.md
  tests/shell/run_all.sh
  tests/shell/shell_recorder/tutorial_wrapper/README.md
Labels: enhancement, ready to merge

#2326 YAy PEG: Fix Grammar Rule `ns_plain_first`
  README.md
  doc/news/_preparation_next_release.md
  doc/todo/NEWS.md
  src/plugins/yaypeg/parser.hpp
Labels: bug, ready to merge

#2307 Global plugins: global keyset handle
  doc/decisions/global_plugins.md
  doc/news/_preparation_next_release.md
  src/include/kdbplugin.h
  src/include/kdbprivate.h
  src/libs/elektra/global.c
  src/libs/elektra/kdb.c
  src/libs/elektra/mount.c
  src/libs/plugin/plugin.c
  src/plugins/doc/doc.c
  src/plugins/doc/doc.h
  tests/icheck.suppression
Labels: ready to merge

#2327 Documentation fix for elektraMetaArrayToKS
  doc/news/_preparation_next_release.md
  src/libs/meta/meta.c
Labels: ready to merge

#2329 Network: Add Markdown Shell Recorder Test for Plugin
  .cirrus.yml
  .travis.yml
  README.md
  doc/Doxyfile
  doc/man/man1/kdb-complete.1
  doc/man/man1/kdb-find.1
  doc/man/man1/kdb-ls.1
  doc/man/man7/elektra-plugins.7
  doc/news/_preparation_next_release.md
  src/plugins/ipaddr/test_ipaddr.h
  src/plugins/network/CMakeLists.txt
  src/plugins/network/README.md
  src/plugins/network/network.c
  src/plugins/process/README.md
Labels: bug, build, enhancement, ready to merge

#2335 Cirrus: Also Test Elektra on FreeBSD 12
  .cirrus.yml
  doc/news/_preparation_next_release.md
  src/plugins/range/CMakeLists.txt
Labels: build, enhancement, ready to merge

#2331 High Level API: Minor Mini Updates to Documentation
  doc/news/_preparation_next_release.md
  doc/tutorials/plugins.md
  examples/highlevel/README.md
  examples/highlevel/application.c
  scripts/sed
  src/error/specification
  src/libs/highlevel/README.md
  src/plugins/reference/README.md
  src/plugins/reference/examples/alternative/README.md
  src/plugins/reference/examples/complex/README.md
Labels: enhancement, low priority, ready to merge

#768 GNOME Integration: decision to GSettings values
  doc/decisions/gsettings_values.md
Labels: proposal, work in progress

#1056 #682 Added turkish translation for i18n.
  src/tools/qt-gui/qml/i18n/lang_tr_TR.ts
Labels: help wanted, work in progress

#2343 Travis: Include IO GLIB Binding in Build Again
  .travis.yml
  doc/news/_preparation_next_release.md
  examples/CMakeLists.txt
  src/bindings/io/glib/CMakeLists.txt
Labels: bug, build, ready to merge

#2337 Global KeySet: improvements
  doc/decisions/README.md
  doc/decisions/global_keyset.md
  doc/decisions/global_plugins.md
  doc/news/_preparation_next_release.md
  src/include/kdbprivate.h
  src/libs/elektra/backend.c
  src/libs/elektra/kdb.c
  src/libs/elektra/mount.c
  src/libs/elektra/plugin.c
  src/libs/plugin/plugin.c
  src/plugins/doc/doc.h
  src/plugins/list/list.c
  tests/ctest/test_backend.c
Labels: ready to merge

#2346 Augeas: Change Default Prefix on macOS
  .cirrus.yml
  cmake/Modules/FindAugeas.cmake
  doc/news/_preparation_next_release.md
Labels: enhancement, ready to merge, usability
