Repository ElektraInitiative/libelektra, pull requests merged in 2019-11, with the labels that each got.

#3125 SWIG performance
  doc/news/_preparation_next_release.md
  src/bindings/cpp/include/key.hpp
  src/bindings/swig/common.i
  src/bindings/swig/lua/kdb.i
  src/bindings/swig/python/kdb.i
Labels: ready to merge

#3095 Remove ksLookup features
  doc/news/_preparation_next_release.md
  src/bindings/glib/gelektra-kdb.h
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/KeySet.java
  src/bindings/rust/elektra/src/keyset.rs
  src/include/kdb.h.in
  src/libs/elektra/kdbenum.c
  src/libs/elektra/keyset.c
  src/libs/elektra/symbols.map
  src/plugins/c/c.c
  src/tools/kdb/get.cpp
  tests/abi/testabi_ks.c
  tests/ctest/test_order.c
Labels: ready to merge

#3126 Style: Unify Names of Reformat Scripts
  doc/CODING.md
  doc/news/2018-11-18_0.8.25.md
  doc/news/2019-02-26_0.8.26.md
  doc/news/2019-08-06_0.9.0.md
  doc/news/_preparation_next_release.md
  scripts/dev/reformat-c
  scripts/dev/reformat-shell
  scripts/generate-yaml
  tests/shell/check_bashisms.sh
  tests/shell/check_formatting.sh
Labels: enhancement, lang/shell, ready to merge

#3145 error-doc: Added information on how warnings are stored
  doc/dev/error-handling.md
  doc/news/_preparation_next_release.md
Labels: ready to merge

#3144 bindings-tutorial: Fix TODO and added subtyping information
  doc/news/_preparation_next_release.md
  doc/tutorials/language-bindings.md
Labels: ready to merge

#3149 Docker: Add Dockerfile for Arch Linux
  doc/news/_preparation_next_release.md
  scripts/docker/arch/Dockerfile
Labels: enhancement, lang/shell, ready to merge

#3150 gopts: increase test timeout
  doc/news/_preparation_next_release.md
  src/plugins/gopts/CMakeLists.txt
Labels: ready to merge

#3153 Cleanup commented KeySet abi testcases
  doc/news/_preparation_next_release.md
  tests/abi/testabi_ks.c
Labels: ready to merge

#3137 crypto: handle return code of execv in the gpg module
  doc/news/_preparation_next_release.md
  src/plugins/crypto/gpg.c
Labels: ready to merge

#3154 Cirrus: Add Job to Check Man Pages And PDF Documentation
  .cirrus.yml
  doc/man/man1/kdb-run-elektrad.1
  doc/man/man1/kdb-run-web.1
  doc/man/man1/kdb-run-website-backend.1
  doc/man/man1/kdb-run-website-frontend.1
  doc/markdownlinkconverter/elektraSpecialCharacters.sty
  doc/news/_preparation_next_release.md
  doc/tutorials/mount.md
  scripts/cmake/ElektraManPage.cmake
  scripts/docker/cirrus/Dockerfile
  src/plugins/yajl/CMakeLists.txt
Labels: continuous integration, documentation, enhancement, lang/shell, ready to merge

#3136 mmapstorage: store the OPMPHM
  doc/news/_preparation_next_release.md
  doc/todo/TESTING
  scripts/jenkins/Jenkinsfile
  src/include/kdbopmphm.h
  src/include/kdbopmphmpredictor.h
  src/libs/elektra/kdb.c
  src/libs/elektra/opmphm.c
  src/libs/elektra/opmphmpredictor.c
  src/plugins/mmapstorage/internal.h
  src/plugins/mmapstorage/mmapstorage.c
  src/plugins/mmapstorage/testmod_mmapstorage.c
  tests/shell/run_all.sh
Labels: ready to merge

#3166 Documentation: Fix Broken Link
  doc/news/_preparation_next_release.md
  src/plugins/yanlr/README.md
  tests/linkchecker.whitelist
Labels: documentation, enhancement, lang/markdown, ready to merge

#3163 Close 2925: Add merge driver for release notes
  doc/news/.gitattributes
  doc/news/_preparation_next_release.md
Labels: ready to merge

#3142 Improvements for exposed meta keyset
  doc/news/_preparation_next_release.md
  examples/keyMetaKeySet.c
  examples/ksNew.c
  src/include/kdbprivate.h
  src/libs/elektra/key.c
  src/libs/elektra/keyhelpers.c
  src/libs/elektra/keymeta.c
  src/libs/elektra/keyset.c
  src/libs/elektra/symbols.map
  src/libs/versions.def
  tests/abi/testabi_ks.c
  tests/ctest/test_ks.c
Labels: ready to merge, urgent

#3175 Shell Recorder: Always Print Protocol for Failed Tests
  doc/news/_preparation_next_release.md
  tests/shell/shell_recorder/shell_recorder.sh
Labels: enhancement, lang/shell, ready to merge, usability

#3165 Rust: Rewrite KDBError
  doc/news/_preparation_next_release.md
  src/bindings/rust/README.md
  src/bindings/rust/elektra/src/kdb.rs
  src/bindings/rust/elektra/src/keyset.rs
  src/bindings/rust/elektra/src/lib.rs
  src/bindings/rust/example/src/bin/kdb.rs
Labels: ready to merge

#3168 GLIB changes
  doc/news/_preparation_next_release.md
  src/bindings/glib/gelektra-key.c
  src/bindings/glib/gelektra-keyset.c
  src/bindings/glib/gelektra-keyset.h
  src/bindings/glib/tests/testglib_keyset.c
  src/bindings/gsettings/elektrasettingsbackend.c
Labels: ready to merge

#3184 CMake: Update Man Pages With Addition Only Updates
  doc/news/_preparation_next_release.md
  scripts/cmake/ElektraManPage.cmake
Labels: bug, build, documentation, lang/cmake, ready to merge

#3183 Fix memleak
  benchmarks/CMakeLists.txt
  benchmarks/memoryleak.c
  doc/news/_preparation_next_release.md
  src/libs/elektra/kdb.c
Labels: ready to merge

#3198 Cirrus: Fix Build Problems
  .cirrus.yml
  .restyled.yaml
  doc/CODING.md
  doc/CONTRACT.ini
  doc/decisions/holes.md
  doc/news/2014-12-02_0.8.10.md
  doc/news/_preparation_next_release.md
  doc/tutorials/highlevel.md
  scripts/dev/fix-spelling
  scripts/dev/reformat-markdown
  scripts/docker/debian/sid/Dockerfile
  scripts/sed
  src/plugins/yamlcpp/CMakeLists.txt
  src/tools/web/client/src/components/TreeItem/fields/SimpleTextField.jsx
  src/tools/web/client/src/containers/ConnectedConfigurationPage.js
  src/tools/web/client/src/containers/ConnectedCreateInstanceCard.js
  src/tools/web/client/src/containers/ConnectedErrorSnackbar.js
  src/tools/web/client/src/containers/ConnectedHomePage.js
  src/tools/web/client/src/containers/ConnectedInstanceCard.js
  src/tools/web/client/src/containers/ConnectedMenu.js
  src/tools/web/client/src/containers/ConnectedTreeItem.js
  src/tools/web/client/src/containers/ConnectedTreeSearch.js
  src/tools/web/client/src/containers/ConnectedTreeView.js
  src/tools/website-frontend/public/vendor/asciinema/asciinema-player.js
  src/tools/website-frontend/resources/assets/js/config/http.js
  tests/linkchecker.whitelist
  tests/shell/check_spelling.sh
  tests/shell/shell_recorder/tutorial_wrapper/CMakeLists.txt
Labels: bug, continuous integration, documentation, lang/cmake, lang/markdown, lang/shell, lang/web, ready to merge

#3179 keyLock and keyIsLocked
  doc/news/_preparation_next_release.md
  src/include/kdb.h.in
  src/include/kdbprivate.h
  src/libs/elektra/kdbenum.c
  src/libs/elektra/key.c
  src/libs/elektra/keyhelpers.c
  src/libs/elektra/keyset.c
  src/libs/elektra/proposal.c
  src/libs/elektra/symbols.map
  src/libs/proposal/proposal.c
  src/libs/proposal/symbols.map
  tests/ctest/test_key.c
Labels: ready to merge

#3209 Merge
  doc/help/kdb-cmerge.md
  doc/help/kdb-install-config-file.md
  doc/man/man1/kdb-cmerge.1
  doc/man/man1/kdb-install-config-file.1
  doc/news/_preparation_next_release.md
  doc/tutorials/cmerge.md
  doc/tutorials/install-config-files.md
  scripts/kdb/cmerge-config-files
  scripts/kdb/install-config-file
  src/include/kdbmerge.h
  src/libs/merge/CMakeLists.txt
  src/libs/merge/kdbmerge.c
  src/libs/merge/symbols.map
  src/tools/kdb/cmerge.cpp
  src/tools/kdb/cmerge.hpp
  src/tools/kdb/external.cpp
  tests/ctest/CMakeLists.txt
  tests/ctest/test_cmerge.c
  tests/shell/check_bashisms.sh
  tests/shell/include_common.sh.in
  tests/shell/shell_recorder/tutorial_wrapper/CMakeLists.txt
Labels: lang/c, lang/shell, ready to merge

#3200 Testing documentation
  doc/TESTING.md
  doc/news/_preparation_next_release.md
Labels: documentation, ready to merge

#3221 Merge: Always initialize LibGit
  doc/news/_preparation_next_release.md
  src/libs/merge/CMakeLists.txt
  src/libs/merge/kdbmerge.c
  tests/ctest/CMakeLists.txt
  tests/shell/shell_recorder/tutorial_wrapper/CMakeLists.txt
Labels: lang/c, ready to merge

#3216 Merge docu
  doc/help/elektra-cmerge-strategy.md
  doc/help/kdb-cmerge-config-files
  doc/help/kdb-cmerge.md
  doc/man/man1/kdb-cmerge.1
  doc/man/man7/elektra-cmerge-strategy.7
  doc/news/_preparation_next_release.md
  doc/tutorials/cmerge.md
  doc/tutorials/install-config-files.md
Labels: ready to merge

#3224 tests: run cmake twice
  doc/news/2018-08-18_0.8.24.md
  doc/news/_preparation_next_release.md
  scripts/CMakeLists.txt
  scripts/dev/CMakeLists.txt
  scripts/dev/run_all.in
  scripts/dev/run_checkshell.in
  scripts/dev/run_memcheck.in
  scripts/dev/run_nocheckshell.in
  scripts/dev/run_nokdbtests.in
  scripts/run_memcheck.in
  tests/CMakeLists.txt
Labels: ready to merge

#3191 Kdb import export provider
  doc/help/kdb-editor.md
  doc/help/kdb-export.md
  doc/help/kdb-import.md
  doc/man/man1/kdb-editor.1
  doc/man/man1/kdb-export.1
  doc/man/man1/kdb-import.1
  doc/news/_preparation_next_release.md
  src/tools/kdb/editor.cpp
  src/tools/kdb/export.cpp
  src/tools/kdb/import.cpp
Labels: ready to merge

#3194 Out of memory error template. Approach #2
  doc/news/_preparation_next_release.md
  src/include/kdberrors.h
  src/include/kdbmacros.h
  src/libs/elektra/errors.c
  src/libs/merge/kdbmerge.c
  src/plugins/augeas/augeas.c
  src/plugins/base64/base64.c
  src/plugins/conditionals/conditionals.c
  src/plugins/crypto/botan_operations.cpp
  src/plugins/crypto/gcrypt_operations.c
  src/plugins/crypto/gpg.c
  src/plugins/crypto/helper.c
  src/plugins/crypto/openssl_operations.c
  src/plugins/fcrypt/fcrypt.c
  src/plugins/file/file.c
  src/plugins/gpgme/gpgme.c
  src/plugins/hexnumber/hexnumber.c
  src/plugins/ini/ini.c
  src/plugins/ipaddr/ipaddr.c
  src/plugins/jni/jni.c
  src/plugins/keytometa/keytometa.c
  src/plugins/lua/lua.cpp
  src/plugins/multifile/multifile.c
  src/plugins/resolver/filename.c
  src/plugins/xerces/xerces.cpp
  src/plugins/yambi/convert.cpp
Labels: ready to merge

#3234 Base for tool integration
  doc/news/_preparation_next_release.md
  src/include/kdbmerge.h
  src/libs/merge/kdbmerge.c
  src/tools/kdb/cmerge.cpp
Labels: ready to merge

#3255 Remove kdb vset
  doc/help/kdb-vset.md
  doc/man/man1/kdb-vset.1
  doc/news/_preparation_next_release.md
  doc/tutorials/validation.md
  scripts/completion/kdb-bash-completion
  scripts/completion/kdb.fish
  scripts/completion/kdb_zsh_completion
  src/tools/kdb/factory.hpp
  src/tools/kdb/validation.cpp
  src/tools/kdb/validation.hpp
  src/tools/website-frontend/public/vendor/asciinema/asciinema-demo.json
Labels: ready to merge

#3248 Helper for merge tools
  doc/news/_preparation_next_release.md
  src/libs/tools/include/helper/keyhelper.hpp
  src/libs/tools/src/helper/keyhelper.cpp
Labels: lang/cpp, ready to merge

#3247 Merge in examples/kdbset.c
  doc/news/_preparation_next_release.md
  doc/tutorials/cmerge.md
  examples/CMakeLists.txt
  examples/kdbset.c
Labels: documentation, lang/c, ready to merge

#3230 Cirrus: Build And Test Elektra on Fedora Linux
  .cirrus.yml
  doc/COMPILE.md
  doc/news/_preparation_next_release.md
  scripts/docker/alpine/3.10/Dockerfile
  scripts/docker/cirrus/arch/Dockerfile
  scripts/docker/cirrus/fedora/Dockerfile
  scripts/jenkins/Jenkinsfile
Labels: build, continuous integration, enhancement, ready to merge

#3002 issue #2922
  .github/CONTRIBUTING.md
  doc/GETSTARTED.md
  doc/news/_preparation_next_release.md
  src/plugins/yajl/README.md
  src/tools/website-frontend/public/pages/main/website/home.html
  src/tools/website-frontend/resources/structure.json.in
Labels: ready to merge

#3264 Cirrus: Execute Unit Test for YAML CPP on macOS
  .cirrus.yml
  doc/news/_preparation_next_release.md
  scripts/cmake/Modules/Findyaml-cpp.cmake
  src/bindings/cpp/include/key.hpp
  src/plugins/yamlcpp/CMakeLists.txt
  src/plugins/yamlcpp/read.cpp
  src/plugins/yamlcpp/testmod_yamlcpp.cpp
  src/plugins/yamlcpp/write.cpp
  src/plugins/yamlcpp/yamlcpp.cpp
  tests/shell/shell_recorder/tutorial_wrapper/CMakeLists.txt
Labels: cleanup, continuous integration, lang/cpp, ready to merge

#3231 Various Minor Fixes
  .cirrus.yml
  doc/dev/error-handling.md
  doc/news/_preparation_next_release.md
  doc/tutorials/storage-plugins.md
  scripts/cmake/Modules/LibAddPlugin.cmake
  scripts/sed
Labels: cleanup, documentation, enhancement, ready to merge

#3265 mmapstorage: filter empty meta keysets
  doc/news/_preparation_next_release.md
  src/plugins/mmapstorage/mmapstorage.c
  src/plugins/mmapstorage/testmod_mmapstorage.c
Labels: ready to merge

#3276 Asciinema sudo fix
  doc/news/_preparation_next_release.md
  src/tools/website-frontend/public/vendor/asciinema/asciinema-demo.json
Labels: ready to merge

#3250 Docu fix
  doc/news/_preparation_next_release.md
  doc/tutorials/plugins.md
Labels: ready to merge

#3275 Remove kdbprivate.h from kdb get & mount
  doc/news/_preparation_next_release.md
  src/tools/kdb/get.cpp
  src/tools/kdb/mount.cpp
Labels: ready to merge

#3226 Style: Format Java Code With Clang-Format
  .cmake-format.yaml
  .restyled.yaml
  doc/CODING.md
  doc/news/_preparation_next_release.md
  examples/external/java/read-keys-example/src/main/java/org/libelektra/app/App.java
  scripts/cmake/Modules/LibAddPlugin.cmake
  scripts/cmake/Modules/LibAddTest.cmake
  scripts/dev/reformat-java
  scripts/dev/reformat-javascript
  scripts/dev/reformat-shell
  src/bindings/jna/HelloElektra.java
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/Elektra.java
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/KDB.java
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/Key.java
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/KeyNameIterator.java
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/KeySet.java
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/KeySetIterator.java
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/Plugin.java
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/PluginLoader.java
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/exception/ConflictingStateException.java
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/exception/InstallationException.java
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/exception/InterfaceException.java
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/exception/InternalException.java
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/exception/KDBException.java
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/exception/LogicalException.java
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/exception/OutOfMemoryException.java
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/exception/PermanentException.java
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/exception/PluginMisbehaviorException.java
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/exception/ResourceException.java
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/exception/SemanticValidationException.java
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/exception/SyntacticValidationException.java
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/exception/ValidationException.java
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/exception/mapper/ExceptionMapperService.java
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/exception/model/WarningEntry.java
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/plugin/Echo.java
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/plugin/NativePlugin.java
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/plugin/PropertiesStorage.java
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/plugin/Return.java
  src/bindings/jna/libelektra4j/src/test/java/org/libelektra/AllTests.java
  src/bindings/jna/libelektra4j/src/test/java/org/libelektra/ExceptionMapperIT.java
  src/bindings/jna/libelektra4j/src/test/java/org/libelektra/ExceptionMapperTest.java
  src/bindings/jna/libelektra4j/src/test/java/org/libelektra/KDBExceptionTest.java
  src/bindings/jna/libelektra4j/src/test/java/org/libelektra/KDBTest.java
  src/bindings/jna/libelektra4j/src/test/java/org/libelektra/KeySetTest.java
  src/bindings/jna/libelektra4j/src/test/java/org/libelektra/KeyTest.java
  src/bindings/jna/libelektra4j/src/test/java/org/libelektra/PluginLoaderIT.java
  src/bindings/jna/libelektra4j/src/test/java/org/libelektra/exception/model/WarningEntryTest.java
  tests/shell/check_bashisms.sh
  tests/shell/check_formatting.sh
  tests/shell/shell_recorder/tutorial_wrapper/CMakeLists.txt
Labels: enhancement, lang/java, lang/shell, ready to merge

#3133 Python enhancements
  doc/news/_preparation_next_release.md
  src/bindings/cpp/include/key.hpp
  src/bindings/cpp/include/keyset.hpp
  src/bindings/swig/common.i
  src/bindings/swig/lua/kdb.i
  src/bindings/swig/lua/tests/test_key.lua
  src/bindings/swig/lua/tests/test_keyset.lua
  src/bindings/swig/python/kdb.i
  src/bindings/swig/python/tests/test_key.py
  src/bindings/swig/python/tests/test_keyset.py
  src/bindings/swig/python2/kdb.i
  src/bindings/swig/python2/tests/testpy2_key.py
  src/bindings/swig/python2/tests/testpy2_keyset.py
  src/libs/elektra/key.c
Labels: ready to merge

#3286 Augeas add lenspath to errormessage
  doc/news/_preparation_next_release.md
  src/plugins/augeas/augeas.c
Labels: ready to merge

#3291 remove python2 and rename swig bindings
  doc/decisions/plugin_variants.md
  doc/images/plugins.dot
  doc/images/plugins.png
  doc/man/man7/elektra-plugins.7
  doc/news/_preparation_next_release.md
  doc/todo/TESTING
  scripts/cmake/ElektraCache.cmake
  scripts/cmake/ElektraUninstall.cmake
  scripts/cmake/Modules/LibAddBinding.cmake
  scripts/deploy/website
  scripts/dev/configure-debian-debug
  scripts/dev/configure-debian-log
  scripts/dev/configure-debian-optimizations
  scripts/dev/configure-debian-wheezy
  scripts/dev/configure-ini
  scripts/docker/website/backend/Dockerfile
  scripts/docker/website/frontend/Dockerfile
  src/bindings/README.md
  src/bindings/swig/CMakeLists.txt
  src/bindings/swig/lua/CMakeLists.txt
  src/bindings/swig/lua/README.md
  src/bindings/swig/python/CMakeLists.txt
  src/bindings/swig/python/README.md
  src/bindings/swig/python2/CMakeLists.txt
  src/bindings/swig/python2/README.md
  src/bindings/swig/python2/kdb.i
  src/bindings/swig/python2/tests/CMakeLists.txt
  src/bindings/swig/python2/tests/testpy2_kdb.py
  src/bindings/swig/python2/tests/testpy2_key.py
  src/bindings/swig/python2/tests/testpy2_keyset.py
  src/bindings/swig/ruby/CMakeLists.txt
  src/plugins/README.md
  src/plugins/lua/CMakeLists.txt
  src/plugins/python/CMakeLists.txt
  src/plugins/python/testmod_python.c
  src/plugins/python2/CMakeLists.txt
  src/plugins/python2/README.md
  src/plugins/python2/config.h.in
  src/plugins/python2/python.cpp
  src/plugins/python2/python.hpp
  src/plugins/python2/testmod_python2.c
  src/plugins/ruby/CMakeLists.txt
  src/plugins/ruby/README.md
Labels: ready to merge

#3296 Test: Use Google Test 1.10
  doc/news/_preparation_next_release.md
  scripts/docker/alpine/3.10/Dockerfile
  scripts/docker/arch/Dockerfile
  scripts/docker/debian/buster/Dockerfile
  scripts/docker/debian/buster/doc.Dockerfile
  scripts/docker/debian/buster/i386.Dockerfile
  scripts/docker/debian/buster/minimal.Dockerfile
  scripts/docker/debian/jessie/Dockerfile
  scripts/docker/debian/sid/Dockerfile
  scripts/docker/debian/stretch/Dockerfile
  scripts/docker/debian/stretch/doc.Dockerfile
  scripts/docker/debian/stretch/i386.Dockerfile
  scripts/docker/debian/stretch/minimal.Dockerfile
  scripts/docker/ubuntu/bionic/Dockerfile
  scripts/docker/ubuntu/disco/Dockerfile
  scripts/docker/ubuntu/xenial/Dockerfile
  scripts/docker/website/backend/Dockerfile
  scripts/docker/website/frontend/Dockerfile
  scripts/docker/webui/base/Dockerfile
  scripts/vagrant/ubuntu/artful32/Vagrantfile
  tests/CMakeLists.txt
  tests/kdb/testkdb_allplugins.cpp
  tests/kdb/testkdb_conflict.cpp
Labels: build, cleanup, enhancement, lang/c, lang/cpp, ready to merge

#3295 doc[validation]: remove header
  doc/news/_preparation_next_release.md
  doc/tutorials/validation.md
Labels: ready to merge

#3304 Improve Rust Documentation
  doc/news/_preparation_next_release.md
  src/bindings/rust/.gitignore
  src/bindings/rust/Cargo.lock
  src/bindings/rust/README.md
  src/bindings/rust/elektra-sys/published_Cargo.toml
  src/bindings/rust/elektra/published_Cargo.toml
  src/bindings/rust/elektra/src/kdb.rs
  src/bindings/rust/elektra/src/key.rs
  src/bindings/rust/elektra/src/keybuilder.rs
  src/bindings/rust/elektra/src/keyset.rs
  src/bindings/rust/elektra/src/lib.rs
  src/bindings/rust/elektra/src/writeable.rs
Labels: ready to merge

#3310 Fix coveralls
  doc/news/_preparation_next_release.md
  scripts/jenkins/Jenkinsfile
Labels: ready to merge
