Repository ElektraInitiative/libelektra, pull requests merged in 2019-06, with the labels that each got.

#2739 multifile+cache fix
  doc/news/_preparation_next_release.md
  src/libs/elektra/mount.c
  src/plugins/ini/ini.c
  src/plugins/multifile/multifile.c
Labels: ready to merge

#2736 Spec improvements
  doc/AUTHORS.md
  doc/METADATA.ini
  doc/news/_preparation_next_release.md
  examples/spec/spec.ini
  src/libs/elektra/internal.c
  src/libs/elektra/keymeta.c
  src/libs/elektra/keyset.c
  src/libs/elektra/keytest.c
  src/libs/highlevel/elektra.c
  src/libs/tools/src/specreader.cpp
  src/plugins/spec/CMakeLists.txt
  src/plugins/spec/README.md
  src/plugins/spec/spec.c
  src/plugins/spec/spec.h
  src/plugins/spec/testmod_spec.c
  tests/abi/testabi_key.c
  tests/abi/testabi_ks.c
  tests/kdb/testkdb_ensure.cpp
  tests/shell/check_gen.sh
  tests/shell/gen/elektra/context.check.sh
  tests/shell/gen/elektra/empty.check.sh
  tests/shell/gen/elektra/empty.data.ini
  tests/shell/gen/elektra/empty.expected.c
  tests/shell/gen/elektra/enum.check.sh
  tests/shell/gen/elektra/enum.data.ini
  tests/shell/gen/elektra/enum.expected.c
  tests/shell/gen/elektra/nodefault.data.ini
  tests/shell/gen/elektra/notype.data.ini
  tests/shell/gen/elektra/notype.expected.c
  tests/shell/gen/elektra/simple.check.sh
  tests/shell/gen/elektra/simple.data.ini
  tests/shell/gen/elektra/simple.expected.c
  tests/shell/gen/elektra/struct.check.sh
  tests/shell/gen/elektra/struct.data.ini
  tests/shell/gen/elektra/struct.expected.c
Labels: ready to merge

#2750 multifile: disable ini caching, add Global Keyset reference
  doc/news/_preparation_next_release.md
  src/plugins/multifile/multifile.c
Labels: ready to merge

#2621 WIP: Plugin for validating MAC-Addresses
  doc/METADATA.ini
  doc/news/_preparation_next_release.md
  src/plugins/README.md
  src/plugins/macaddr/CMakeLists.txt
  src/plugins/macaddr/README.md
  src/plugins/macaddr/macaddr.c
  src/plugins/macaddr/macaddr.h
  src/plugins/macaddr/testmod_macaddr.c
Labels: cm2019s, enhancement, lang/c, ready to merge

#2754 Documentation: Explain How to Profile Code With XRay
  README.md
  doc/images/flamegraph.svg
  doc/news/2015-11-19_0.8.14.md
  doc/news/_preparation_next_release.md
  doc/tutorials/profiling.md
  scripts/docker/ubuntu/disco/Dockerfile
  scripts/link-checker
Labels: enhancement, ready to merge

#2707 Highlevel codegen updates
  .travis.yml
  doc/METADATA.ini
  doc/news/_preparation_next_release.md
  examples/codegen/econf/src/application.c
  examples/codegen/tree/spec.ini
  src/include/elektra.h
  src/include/kdbprivate.h
  src/libs/highlevel/elektra.c
  src/plugins/gopts/CMakeLists.txt
  src/plugins/gopts/README.md
  src/plugins/gopts/gopts_osx.h
  src/plugins/gopts/gopts_sysctl.h
  src/plugins/gopts/sysctl_test.c
  src/plugins/gopts/testapp.c
  src/tools/kdb/CMakeLists.txt
  src/tools/kdb/gen/elektra/common.cpp
  src/tools/kdb/gen/elektra/common.hpp
  src/tools/kdb/gen/elektra/elektragen.cpp
  src/tools/kdb/gen/elektra/elektragen.hpp
  src/tools/kdb/gen/elektra/enums.cpp
  src/tools/kdb/gen/elektra/enums.hpp
  src/tools/kdb/gen/elektra/structs.cpp
  src/tools/kdb/gen/elektra/structs.hpp
  src/tools/kdb/gen/elektragen.cpp
  src/tools/kdb/gen/template.cpp
  src/tools/kdb/gen/templates/elektra.c.mustache
  src/tools/kdb/gen/templates/elektra.h.mustache
  src/tools/kdb/gen/templates/elektra/LICENSE.txt
  src/tools/kdb/gen/templates/elektra/context.fun.h.mustache
  src/tools/kdb/gen/templates/elektra/context.tags.h.mustache
  src/tools/kdb/gen/templates/elektra/enum.c.mustache
  src/tools/kdb/gen/templates/elektra/enum.decl.h.mustache
  src/tools/kdb/gen/templates/elektra/keys.fun.h.mustache
  src/tools/kdb/gen/templates/elektra/keys.fun.struct.h.mustache
  src/tools/kdb/gen/templates/elektra/keys.fun.structref.h.mustache
  src/tools/kdb/gen/templates/elektra/struct.alloc.fields.c.mustache
  src/tools/kdb/gen/templates/elektra/struct.c.mustache
  src/tools/kdb/gen/templates/elektra/struct.decl.h.mustache
  src/tools/kdb/gen/templates/elektra/union.c.mustache
  src/tools/kdb/gen/templates/elektra/union.decl.h.mustache
  tests/shell/gen/elektra/context.check.sh
  tests/shell/gen/elektra/context.data.ini.disabled
  tests/shell/gen/elektra/context.expected.c
  tests/shell/gen/elektra/context.expected.h
  tests/shell/gen/elektra/context.params
  tests/shell/gen/elektra/empty.expected.c
  tests/shell/gen/elektra/empty.expected.h
  tests/shell/gen/elektra/enum.expected.c
  tests/shell/gen/elektra/enum.expected.h
  tests/shell/gen/elektra/notype.expected.c
  tests/shell/gen/elektra/notype.expected.h
  tests/shell/gen/elektra/simple.expected.c
  tests/shell/gen/elektra/simple.expected.h
  tests/shell/gen/elektra/struct.check.sh
  tests/shell/gen/elektra/struct.data.ini
  tests/shell/gen/elektra/struct.expected.c
  tests/shell/gen/elektra/struct.expected.h
Labels: ready to merge

#2756 Fix compilation without deprecated OpenSSL APIs
  doc/news/_preparation_next_release.md
  src/plugins/crypto/openssl_operations.c
Labels: ready to merge

#2752 #2717: Improve qt-gui error message popup
  doc/news/_preparation_next_release.md
  src/tools/qt-gui/src/treeviewmodel.cpp
  src/tools/qt-gui/src/treeviewmodel.hpp
Labels: ready to merge

#2769 Travis: Simplify Mac Setup
  .travis.yml
  doc/news/_preparation_next_release.md
Labels: enhancement, lang/shell, ready to merge

#2771 cmake: fix REQUIRED_TOOLS in function add_msr_test
  cmake/ElektraCache.cmake
  cmake/Modules/LibAddTest.cmake
  doc/news/_preparation_next_release.md
Labels: ready to merge

#2773 Reformat with docker tutorial
  doc/news/_preparation_next_release.md
  doc/tutorials/run_all_tests_with_docker.md
  doc/tutorials/run_reformatting_script_with_docker.md
Labels: cm2019s, enhancement, usability

#2735 Resolving issue #2541
  doc/INSTALL.md
  doc/news/_preparation_next_release.md
  doc/tutorials/crypto.md
  doc/tutorials/validation.md
  scripts/run_dev_env
  src/plugins/base64/README.md
  src/plugins/blockresolver/README.md
  src/plugins/blockresolver/blockresolver/compare.block
  src/plugins/blockresolver/blockresolver/test.block
  src/plugins/conditionals/README.md
  src/plugins/curlget/README.md
  src/plugins/iconv/iconv/iconv.ini
  src/plugins/ini/README.md
  src/plugins/ini/crash_test/crash001.ini
  src/plugins/ini/ini.c
  src/plugins/ini/ini/array.ini
  src/plugins/ini/ini/arrayInsertIn.ini
  src/plugins/ini/ini/arrayInsertOut.ini
  src/plugins/ini/ini/bracketQuoteOut.ini
  src/plugins/ini/ini/commentini
  src/plugins/ini/ini/complexIn.ini
  src/plugins/ini/ini/complexOut.ini
  src/plugins/ini/ini/emptyLines
  src/plugins/ini/ini/emptySectionBugTest
  src/plugins/ini/ini/emptyval
  src/plugins/ini/ini/insertTest.input.ini
  src/plugins/ini/ini/insertTest.output.ini
  src/plugins/ini/ini/multilineini
  src/plugins/ini/ini/plainini
  src/plugins/ini/ini/plaininireverse
  src/plugins/ini/ini/sectionini
  src/plugins/ini/ini/sectionmerge.input
  src/plugins/ini/ini/sectionmerge.output
  src/plugins/ini/ini/testCommentMeta.ini
  src/plugins/ini/ini/writeCommentMeta.ini
  src/plugins/mozprefs/README.md
  tests/shell/shell_recorder/tutorial_wrapper/SyntaxCheck.md
Labels: cm2019s, enhancement, lang/c

#2775 Pull Request Template: Fix Broken Links
  .github/PULL_REQUEST_TEMPLATE.md
  doc/news/_preparation_next_release.md
Labels: enhancement, ready to merge

#2776 Add plugin tests only if BUILD_TESTING=ON
  doc/news/_preparation_next_release.md
  src/CMakeLists.txt
Labels: ready to merge

#2770 Documentation/rest api web
  doc/news/_preparation_next_release.md
  src/tools/web/README.md
Labels: cm2019s, enhancement, usability

#2783 Multifile error fixes
  doc/news/_preparation_next_release.md
  src/plugins/multifile/multifile.c
Labels: ready to merge

#2777 Covered Resolving Missing *.so Library Error
  doc/news/_preparation_next_release.md
  doc/tutorials/contributing-clion.md
Labels: cm2019s, enhancement, usability

#2744 memory value fixed conflicts
  doc/METADATA.ini
  doc/news/_preparation_next_release.md
  src/plugins/README.md
  src/plugins/unit/CMakeLists.txt
  src/plugins/unit/README.md
  src/plugins/unit/testmod_unit.c
  src/plugins/unit/unit.c
  src/plugins/unit/unit.h
Labels: cm2019s, enhancement, lang/c

#2784 Add temporary fix for finding jni plugin
  cmake/Modules/SafeCheckSymbolExists.cmake
  doc/news/_preparation_next_release.md
Labels: bug, cm2019s, lang/cmake, ready to merge

#2796 Add Documentation Search to Website
  doc/news/_preparation_next_release.md
  src/tools/rest-frontend/Gruntfile.js
  src/tools/rest-frontend/package.json
  src/tools/rest-frontend/public/assets/translations/en.json
  src/tools/rest-frontend/public/pages/main/template.html
  src/tools/rest-frontend/resources/assets/html/index.html.in
  src/tools/rest-frontend/resources/assets/js/controllers/main/MainController.js
  src/tools/rest-frontend/resources/assets/skin/base/theme.less
Labels: cm2019s, enhancement, lang/web, ready to merge

#2792 Anchor links
  doc/news/_preparation_next_release.md
  src/tools/rest-frontend/resources/assets/js/config/marked.js
Labels: cm2019s, enhancement, ready to merge

#2768 Add tutorial for running tests with Docker
  doc/news/_preparation_next_release.md
  doc/tutorials/run_all_tests_with_docker.md
Labels: cm2019s, enhancement, usability

#2778 Extend java tutorial
  doc/news/_preparation_next_release.md
  doc/tutorials/java-kdb.md
  examples/external/java/read-keys-example/README.md
  examples/external/java/read-keys-example/lib/README.md
  examples/external/java/read-keys-example/pom.xml
  examples/external/java/read-keys-example/src/main/java/org/libelektra/app/App.java
  src/bindings/jna/README.md
Labels: cm2019s, enhancement, lang/java

#2597 added license for asciinema
  src/tools/rest-frontend/public/vendor/asciinema/LICENCE
Labels: cm2019s, enhancement

#2791 Quickdump v3
  benchmarks/plugingetset.c
  doc/news/_preparation_next_release.md
  src/plugins/quickdump/README.md
  src/plugins/quickdump/benchmarks.md
  src/plugins/quickdump/benchmarks/results.get.2.json
  src/plugins/quickdump/benchmarks/results.get.200.json
  src/plugins/quickdump/benchmarks/results.get.200k.json
  src/plugins/quickdump/benchmarks/results.get.2M.json
  src/plugins/quickdump/benchmarks/results.get.2k.json
  src/plugins/quickdump/benchmarks/results.getset.2.json
  src/plugins/quickdump/benchmarks/results.getset.200.json
  src/plugins/quickdump/benchmarks/results.getset.200k.json
  src/plugins/quickdump/benchmarks/results.getset.2k.json
  src/plugins/quickdump/quickdump.c
  src/plugins/quickdump/quickdump/test.quickdump
  src/plugins/quickdump/quickdump/test.quickdump.h
  src/plugins/quickdump/quickdump/test.v2.quickdump
  src/plugins/quickdump/readv2.c
  src/plugins/quickdump/testmod_quickdump.c
  src/plugins/quickdump/varint.c
  src/plugins/specload/specload/add.quickdump
  src/plugins/specload/specload/basics.quickdump
  src/plugins/specload/specload/edit.quickdump
  src/plugins/specload/specload/remove.quickdump
  src/plugins/specload/testdata.h
Labels: ready to merge

#2802 Java Tutorials: Minor Improvements
  doc/news/_preparation_next_release.md
  doc/tutorials/java-kdb.md
  doc/tutorials/java-plugins.md
Labels: enhancement, ready to merge

#2803 Fix readme typos
  README.md
  doc/news/_preparation_next_release.md
  doc/tutorials/application-integration.md
  doc/tutorials/mount.md
  scripts/sed
  src/include/kdbconfig.h.in
  src/plugins/resolver/README.md
  src/tools/README.md
Labels: ready to merge

#2808 cmake: export symbols from function instead of custom executable
  cmake/Modules/ExportPluginSymbols.cmake
  doc/news/_preparation_next_release.md
  src/libs/elektra/CMakeLists.txt
  src/libs/elektra/exportsymbols.c
Labels: ready to merge

#2813 Restyled: Add Configuration for `shfmt`
  .restyled.yaml
  doc/news/_preparation_next_release.md
Labels: build, enhancement, lang/shell, ready to merge, usability
