Repository ElektraInitiative/libelektra, pull requests merged in 2019-03, with the labels that each got.

#2447 Jenkins: Disable Failing Tests
  doc/news/_preparation_next_release.md
  doc/todo/TESTING
  scripts/jenkins/Jenkinsfile
Labels: bug, build, ready to merge, usability

#2445 Markdown Link Converter: Change Location Style
  doc/markdownlinkconverter/README.md
  doc/markdownlinkconverter/markdownlinkconverter.c
  doc/news/_preparation_next_release.md
  src/libs/highlevel/README.md
Labels: build, enhancement, ready to merge, usability

#2443 Yan LR: Check if ANTLR 4 Version Supports ANTLR’s C++ Runtime
  doc/news/_preparation_next_release.md
  src/plugins/yanlr/CMakeLists.txt
  src/plugins/yanlr/README.md
  src/plugins/yanlr/error_listener.cpp
Labels: bug, build, ready to merge, usability

#2442 YAMBi: Improve Error Messages
  .cirrus.yml
  doc/news/_preparation_next_release.md
  src/plugins/yambi/CMakeLists.txt
  src/plugins/yambi/README.md
  src/plugins/yambi/driver.cpp
  src/plugins/yambi/driver.hpp
  src/plugins/yambi/input.cpp
  src/plugins/yambi/input.hpp
  src/plugins/yambi/lexer.cpp
  src/plugins/yambi/lexer.hpp
  src/plugins/yambi/parser.ypp
  src/plugins/yambi/symbol.hpp
  src/plugins/yambi/testmod_yambi.cpp
Labels: enhancement, ready to merge, usability

#2449 YAwn: Improve Error Reporting
  doc/news/_preparation_next_release.md
  src/plugins/yawn/README.md
  src/plugins/yawn/convert.cpp
  src/plugins/yawn/error_listener.cpp
  src/plugins/yawn/error_listener.hpp
  src/plugins/yawn/input.cpp
  src/plugins/yawn/input.hpp
  src/plugins/yawn/lexer.cpp
  src/plugins/yawn/lexer.hpp
  src/plugins/yawn/token.cpp
  src/plugins/yawn/token.hpp
  src/plugins/yawn/yaml.bnf
Labels: enhancement, ready to merge, usability

#2433 Specload
  .cmake-format.yaml
  .idea/codeStyles/Project.xml
  .idea/vcs.xml
  benchmarks/CMakeLists.txt
  benchmarks/README.md
  benchmarks/plugingetset.c
  benchmarks/storage.c
  cmake/Modules/LibAddPlugin.cmake
  doc/news/_preparation_next_release.md
  src/error/specification
  src/include/CMakeLists.txt
  src/include/kdbendian.h
  src/plugins/README.md
  src/plugins/quickdump/CMakeLists.txt
  src/plugins/quickdump/README.md
  src/plugins/quickdump/benchmarks.md
  src/plugins/quickdump/benchmarks/results.get.2.json
  src/plugins/quickdump/benchmarks/results.get.200.json
  src/plugins/quickdump/benchmarks/results.get.200k.json
  src/plugins/quickdump/benchmarks/results.get.2M.json
  src/plugins/quickdump/benchmarks/results.get.2k.json
  src/plugins/quickdump/benchmarks/results.getset.2.json
  src/plugins/quickdump/benchmarks/results.getset.200.json
  src/plugins/quickdump/benchmarks/results.getset.200k.json
  src/plugins/quickdump/benchmarks/results.getset.2k.json
  src/plugins/quickdump/quickdump.c
  src/plugins/quickdump/quickdump.h
  src/plugins/quickdump/quickdump/test.quickdump
  src/plugins/quickdump/quickdump/test.quickdump.h
  src/plugins/quickdump/testmod_quickdump.c
  src/plugins/specload/CMakeLists.txt
  src/plugins/specload/README.md
  src/plugins/specload/config.c.in
  src/plugins/specload/specload.c
  src/plugins/specload/specload.h
  src/plugins/specload/specload/add.quickdump
  src/plugins/specload/specload/basics.quickdump
  src/plugins/specload/specload/edit.quickdump
  src/plugins/specload/specload/remove.quickdump
  src/plugins/specload/test_testapp.c
  src/plugins/specload/testapp.c
  src/plugins/specload/testdata.h
  src/plugins/specload/testmod_specload.c
  tests/cframework/tests.h
  tests/ctest/test_storage.c
  tests/shell/check_kdb_internal_check.sh
  tests/shell/check_kdb_internal_suite.sh
  tests/shell/shell/again_two_value.quickdump
  tests/shell/shell/one_value.quickdump
  tests/shell/shell/three_value.quickdump
  tests/shell/shell/two_value.quickdump
Labels: ready to merge

#2458 Minor addition to specload
  doc/news/_preparation_next_release.md
  src/plugins/specload/README.md
  src/plugins/specload/specload.c
  src/plugins/specload/specload.h
  src/plugins/specload/testapp.c
Labels: ready to merge

#2459 move reference resolving into libease
  doc/news/_preparation_next_release.md
  src/include/kdbease.h
  src/libs/ease/reference.c
  src/plugins/reference/reference.c
  tests/icheck.suppression
Labels: ready to merge

#2462 ease/specload: minor improvements
  doc/news/_preparation_next_release.md
  src/libs/ease/reference.c
  src/plugins/specload/README.md
  src/plugins/specload/specload.c
  src/plugins/specload/testapp.c
Labels: ready to merge

#2463 Documentation: Add Badge for LGTM
  README.md
  doc/news/_preparation_next_release.md
  scripts/check-env-dep
Labels: bug, enhancement, ready to merge

#2446 examples: added some specification examples
  doc/news/_preparation_next_release.md
  examples/spec/cassandra.ini
  examples/spec/lcdproc/LCDd.ini
  examples/spec/lcdproc/lcdexec.ini
  examples/spec/lcdproc/lcdproc.ini
  examples/spec/lcdproc/lcdvc.ini
Labels: ready to merge

#2470 YAy PEG: Improve Error Messages
  doc/news/_preparation_next_release.md
  scripts/docker/debian/sid/Dockerfile
  scripts/docker/debian/stretch/Dockerfile
  src/plugins/yaypeg/README.md
  src/plugins/yaypeg/convert.cpp
  src/plugins/yaypeg/parser.hpp
Labels: enhancement, ready to merge, usability

#2475 type: improved documentation
  doc/news/_preparation_next_release.md
  src/plugins/type/README.md
Labels: ready to merge

#2480 Updated hello-elektra-tutorial (CM PR)
  doc/news/_preparation_next_release.md
  doc/tutorials/hello-elektra.md
Labels: ready to merge

#2491 LGTM: Add Initial Version of Configuration File
  doc/news/_preparation_next_release.md
  lgtm.yml
Labels: enhancement, ready to merge

#2479 Documentation: Add Basic Storage Plugin Tutorial
  doc/markdownlinkconverter/elektraSpecialCharacters.sty
  doc/news/2016-09-17_0.8.18.md
  doc/news/_preparation_next_release.md
  doc/tutorials/compilation-variants.md
  doc/tutorials/plugins.md
  doc/tutorials/storage-plugins.md
  src/libs/typesystem/specelektra/specelektra.cabal.in
  src/tools/rest-backend/README.md
  src/tools/rest-backend/config-specification.ini.in
  src/tools/web/README.md
  tests/shell/shell_recorder/tutorial_wrapper/CMakeLists.txt
Labels: enhancement, ready to merge, usability

#2485 Code Check: Fix Some Warnings Reported by LGTM
  doc/news/_preparation_next_release.md
  examples/helloElektra.c
  examples/keyCopy.c
  examples/keyMeta.c
  src/bindings/cpp/include/kdbtimer.hpp
  src/include/kdbassert.h
  src/include/kdbos.h
  src/include/macros/type_create_to_value.h
  src/plugins/conditionals/conditionals.c
  src/plugins/crypto/gpgagent_teardown.h
  src/plugins/curlget/curlget.c
  src/plugins/hosts/hosts.h
  src/plugins/iconv/conv.h
  src/plugins/mathcheck/floathelper.h
  src/plugins/mmapstorage/internal.h
  src/plugins/mmapstorage/mmapstorage.c
  src/plugins/ni/nickel-1.1.0/src/include/bohr/ds_vector.h
  src/plugins/python/python/python_filter.py
  src/plugins/python/python/python_plugin2.py
  src/plugins/resolver/shared.h
  src/plugins/syslog/syslog.c
  src/plugins/tcl/action.hpp
  src/tools/kdb/coloredkdbio.hpp
  src/tools/kdb/info.cpp
  src/tools/kdb/rename.hpp
  src/tools/qt-gui/qml/TooltipCreator.js
Labels: enhancement, ready to merge

#2500 Yan LR: Fix Grammar Ambiguity
  doc/news/_preparation_next_release.md
  src/plugins/yanlr/CMakeLists.txt
  src/plugins/yanlr/YAML.g4
Labels: bug, enhancement, ready to merge

#2503 Check Formatting: Improve Formatting Instructions
  doc/news/_preparation_next_release.md
  tests/shell/check_formatting.sh
Labels: enhancement, ready to merge, usability

#2504 reference: fix README
  doc/METADATA.ini
  doc/news/_preparation_next_release.md
  src/plugins/reference/README.md
Labels: ready to merge

#2506 Storage Plugin Tutorial: Fix Cleanup of MSR Test
  cmake/ElektraCache.cmake
  cmake/Modules/LibAddPlugin.cmake
  doc/decisions/unit_testing.md
  doc/news/2014-06-21_0.8.6.md
  doc/news/2014-11-04_0.8.9.md
  doc/news/2015-09-17_0.8.13.md
  doc/news/2015-11-19_0.8.14.md
  doc/news/2016-02-16_0.8.15.md
  doc/news/2016-04-29_0.8.16.md
  doc/news/2016-06-14_0.8.17.md
  doc/news/2016-11-22_0.8.19.md
  doc/news/_preparation_next_release.md
  doc/todo/TESTING
  doc/tutorials/plugins.md
  doc/tutorials/storage-plugins.md
  src/plugins/validation/lookupre.c
  src/tools/kdb/test.cpp
  tests/abi/testabi_ks.c
  tests/ctest/test_operation.c
Labels: bug, ready to merge

#2501 quickdump v2: relative key names, reused buffer, etc.
  .cirrus.yml
  .travis.yml
  doc/news/_preparation_next_release.md
  src/plugins/quickdump/README.md
  src/plugins/quickdump/benchmarks.md
  src/plugins/quickdump/quickdump.c
  src/plugins/quickdump/quickdump/test.quickdump
  src/plugins/quickdump/quickdump/test.quickdump.h
  src/plugins/quickdump/quickdump/test.v1.quickdump
  src/plugins/quickdump/readv1.c
  src/plugins/quickdump/testmod_quickdump.c
  src/plugins/specload/specload.c
  src/plugins/specload/specload/add.quickdump
  src/plugins/specload/specload/basics.quickdump
  src/plugins/specload/specload/edit.quickdump
  src/plugins/specload/specload/remove.quickdump
  src/plugins/specload/testapp.c
  src/plugins/specload/testdata.h
  src/plugins/specload/testmod_specload.c
  tests/ctest/test_storage.c
  tests/shell/shell/again_two_value.quickdump
  tests/shell/shell/one_value.quickdump
  tests/shell/shell/three_value.quickdump
  tests/shell/shell/two_value.quickdump
Labels: ready to merge

#2505 New type plugin
  doc/METADATA.ini
  doc/news/_preparation_next_release.md
  src/include/kdbmeta.h
  src/libs/elektra/keyvalue.c
  src/libs/meta/meta.c
  src/plugins/README.md
  src/plugins/boolean/README.md
  src/plugins/boolean/boolean.c
  src/plugins/enum/README.md
  src/plugins/newtype/CMakeLists.txt
  src/plugins/newtype/README.md
  src/plugins/newtype/newtype.c
  src/plugins/newtype/newtype.h
  src/plugins/newtype/testmod_newtype.c
  src/plugins/newtype/types.c
  src/plugins/newtype/types.h
  src/plugins/type/README.md
Labels: ready to merge

#2514 Yan LR: Fix Position Information of Tokens Emitted by Lexer
  doc/man/man7/elektra-plugins.7
  doc/news/_preparation_next_release.md
  src/plugins/yanlr/CMakeLists.txt
  src/plugins/yanlr/error_listener.cpp
  src/plugins/yanlr/error_listener.hpp
  src/plugins/yanlr/listener.cpp
  src/plugins/yanlr/listener.hpp
  src/plugins/yanlr/yaml_lexer.cpp
  src/plugins/yanlr/yaml_lexer.hpp
  src/plugins/yanlr/yanlr.cpp
  src/plugins/yanlr/yanlr.hpp
Labels: bug, enhancement, ready to merge, usability

#2512 shfmt: format include_common.sh.in
  doc/news/_preparation_next_release.md
  scripts/reformat-shfmt
  tests/shell/include_common.sh.in
Labels: ready to merge

#2513 newtype: minor improvements from code review
  doc/METADATA.ini
  doc/news/_preparation_next_release.md
  src/error/specification
  src/plugins/README.md
  src/plugins/boolean/README.md
  src/plugins/cpptype/CMakeLists.txt
  src/plugins/cpptype/README.md
  src/plugins/cpptype/cpptype.cpp
  src/plugins/cpptype/cpptype.hpp
  src/plugins/cpptype/testmod_cpptype.cpp
  src/plugins/cpptype/type_checker.hpp
  src/plugins/cpptype/types.cpp
  src/plugins/cpptype/types.hpp
  src/plugins/enum/README.md
  src/plugins/newtype/CMakeLists.txt
  src/plugins/newtype/README.md
  src/plugins/newtype/newtype.c
  src/plugins/newtype/newtype.h
  src/plugins/newtype/testmod_newtype.c
  src/plugins/newtype/types.h
  src/plugins/type/CMakeLists.txt
  src/plugins/type/README.md
  src/plugins/type/testmod_type.c
  src/plugins/type/type.c
  src/plugins/type/type.h
  src/plugins/type/type.hpp
  src/plugins/type/types.c
  src/plugins/type/types.h
  src/plugins/yamlcpp/README.md
  tests/cframework/tests.h
Labels: ready to merge

#2532 doc: improve section about checkconf in the plugin tutorial
  doc/news/_preparation_next_release.md
  doc/tutorials/plugins.md
Labels: ready to merge

#2538 Directory Value: Extend Test Suite
  doc/news/_preparation_next_release.md
  src/plugins/directoryvalue/directoryvalue/arrays.hpp
  src/plugins/directoryvalue/directoryvalue/arrays_get.hpp
  src/plugins/directoryvalue/directoryvalue/arrays_set.hpp
  src/plugins/directoryvalue/directoryvalue/mixed_get.hpp
  src/plugins/directoryvalue/directoryvalue/mixed_set.hpp
  src/plugins/directoryvalue/directoryvalue_delegate.cpp
  src/plugins/directoryvalue/testmod_directoryvalue.cpp
Labels: enhancement, ready to merge

#2539 CFramework: Compare Name of Meta Keys
  doc/news/_preparation_next_release.md
  tests/cframework/tests.h
Labels: enhancement, ready to merge

#2435 Error message concept
  doc/decisions/README.md
  doc/decisions/error_message.md
  doc/news/_preparation_next_release.md
Labels: ready to merge

#2542 Add fix to arguments for create methods in HelloElektra.java
  doc/news/_preparation_next_release.md
  src/bindings/jna/HelloElektra.java
Labels: cm2019s, enhancement, lang/java, ready to merge

#2545 YAML CPP: Improve Support for Arrays
  doc/news/_preparation_next_release.md
  doc/tutorials/storage-plugins.md
  scripts/docker/debian/sid/Dockerfile
  src/plugins/yamlcpp/CMakeLists.txt
  src/plugins/yamlcpp/README.md
  src/plugins/yamlcpp/log.cpp
  src/plugins/yamlcpp/log.hpp
  src/plugins/yamlcpp/read.cpp
  src/plugins/yamlcpp/testmod_yamlcpp.c
  src/plugins/yamlcpp/testmod_yamlcpp.cpp
  src/plugins/yamlcpp/write.cpp
  src/plugins/yamlcpp/yamlcpp.cpp
  src/plugins/yamlcpp/yamlcpp.hpp
  src/plugins/yamlcpp/yamlcpp/flat_block_mapping.h
  src/plugins/yamlcpp/yamlcpp/flat_flow_mapping.h
  src/plugins/yamlcpp/yamlcpp/mapping_with_array_key.h
  src/plugins/yamlcpp/yamlcpp/nested_block_mapping.h
  src/plugins/yamlcpp/yamlcpp/nested_mixed_mapping.h
  src/plugins/yamlcpp/yamlcpp/nested_sequences.h
  src/plugins/yamlcpp/yamlcpp/simple_sequence.h
Labels: bug, enhancement, lang/cpp, ready to merge

#2547 YAMBi: Fix Location Information Inside Error Messages
  doc/news/_preparation_next_release.md
  src/plugins/yambi/README.md
  src/plugins/yambi/driver.cpp
  src/plugins/yambi/lexer.cpp
  src/plugins/yambi/symbol.hpp
Labels: bug, lang/cpp, ready to merge, usability

#2554 YAwn: Fix Location Information Inside Error Messages
  doc/news/_preparation_next_release.md
  src/plugins/yawn/README.md
  src/plugins/yawn/error_listener.cpp
  src/plugins/yawn/lexer.cpp
Labels: bug, lang/cpp, ready to merge, usability

#2563 Release Notes Check: Fix Invalid Argument in Test Expression
  doc/news/_preparation_next_release.md
  scripts/run_check_release_notes
Labels: bug, lang/shell, ready to merge

#2562 Formatting improvements
  doc/news/_preparation_next_release.md
  scripts/pre-commit-check-formatting
  scripts/reformat-all
  scripts/reformat-cmake
  scripts/reformat-markdown
  scripts/reformat-shfmt
  scripts/reformat-source
Labels: enhancement, lang/shell, ready to merge

#2564 Jenkins: Increase Test Timeout
  doc/news/_preparation_next_release.md
  scripts/jenkins/Jenkinsfile
Labels: build, enhancement, ready to merge

#2544 Documentation: Fix Indefinite Articles
  README.md
  benchmarks/benchmarks.h
  cmake/Modules/FindDiscount.cmake
  doc/BUILDSERVER.md
  doc/DESIGN.md
  doc/METADATA.ini
  doc/decisions/deferred_plugin_calls.md
  doc/dev/data-structures.md
  doc/help/elektra-faq.md
  doc/help/elektra-namespaces.md
  doc/help/kdb.md
  doc/markdownlinkconverter/markdownlinkconverter.c
  doc/news/2014-06-21_0.8.6.md
  doc/news/2016-06-14_0.8.17.md
  doc/news/2016-09-17_0.8.18.md
  doc/news/2017-03-18_lcdproc.md
  doc/news/_preparation_next_release.md
  scripts/README.md
  src/bindings/cpp/include/key.hpp
  src/bindings/io/ev/io_ev.c
  src/bindings/io/glib/io_glib.c
  src/bindings/io/uv/io_uv.c
  src/error/specification
  src/libs/elektra/internal.c
  src/libs/elektra/key.c
  src/libs/elektra/keymeta.c
  src/libs/elektra/keyname.c
  src/libs/elektra/keyset.c
  src/libs/elektra/keytest.c
  src/libs/elektra/opmphm.c
  src/libs/elektra/opmphmpredictor.c
  src/libs/elektra/owner.c
  src/libs/highlevel/elektra_array_value.c
  src/libs/highlevel/elektra_value.c
  src/plugins/boolean/README.md
  src/plugins/date/date.c
  src/plugins/ini/README.md
  src/plugins/jni/README.md
  src/plugins/ni/nickel-1.1.0/src/hash.c
  src/plugins/ruby/ruby_test_scripts/invalid.rb
  src/plugins/spec/spec.c
  src/plugins/typechecker/README.md
  src/plugins/yajl/yajl_gen_open.c
  src/plugins/yanlr/error_listener.cpp
  src/plugins/yanlr/error_listener.hpp
  src/plugins/yawn/convert.cpp
  src/plugins/yawn/convert.hpp
  src/tools/gen/tests/Doxyfile
  src/tools/kdb/command.hpp
  tests/cframework/tests.c
Labels: enhancement, ready to merge

#2553 Fix dos newlines
  doc/news/_preparation_next_release.md
  doc/tutorials/cascading.md
  src/plugins/csvstorage/csvstorage.c
  src/plugins/csvstorage/csvstorage/validDos.csv
  src/plugins/csvstorage/testmod_csvstorage.c
Labels: bug, cm2019s, lang/c, usability

#2548 YAJL: Save Value Directly Below Mountpoint
  doc/news/_preparation_next_release.md
  src/plugins/yajl/testmod_yajl.c
  src/plugins/yajl/yajl/top_level_integer.json
  src/plugins/yajl/yajl/top_level_string.json
  src/plugins/yajl/yajl_gen.c
Labels: bug, cm2019s, lang/c, ready to merge, usability

#2567 Docker: Update Docker Image for Alpine Linux
  doc/news/_preparation_next_release.md
  scripts/docker/alpine/3.9/Dockerfile
  scripts/jenkins/Jenkinsfile
Labels: build, enhancement, ready to merge
