Repository ElektraInitiative/libelektra, pull requests merged in 2019-08, with the labels that each got.

#2841 Documentation: Fix Broken Links
  doc/BIGPICTURE.md
  doc/help/elektra-introduction.md
  doc/help/kdb.md
  doc/man/man1/kdb.1
  doc/man/man7/elektra-introduction.7
  doc/news/2018-11-18_0.8.25.md
  doc/news/_preparation_next_release.md
Labels: bug, lang/markdown, ready to merge

#2846 Build: Only Require GLib for IO Binding Example
  doc/news/_preparation_next_release.md
  examples/CMakeLists.txt
Labels: bug, build, lang/cmake, ready to merge

#2848 Build: Do Not Install System Files by Default
  .cirrus.yml
  .travis.yml
  cmake/ElektraCache.cmake
  doc/COMPILE.md
  doc/news/_preparation_next_release.md
  doc/tutorials/contributing-clion.md
  doc/tutorials/run_all_tests_with_docker.md
  scripts/build-homepage
  scripts/docker/homepage/backend/Dockerfile
  scripts/docker/homepage/frontend/Dockerfile
  scripts/jenkins/Jenkinsfile
  scripts/vagrant/ubuntu/artful32/README.md
Labels: enhancement, ready to merge, usability

#2604 cache: enable ini
  doc/news/_preparation_next_release.md
  scripts/jenkins/Jenkinsfile
  src/libs/elektra/kdb.c
  src/plugins/cache/README.md
  src/plugins/cache/testmod_cache.c
  src/plugins/ini/README.md
  src/plugins/mmapstorage/README.md
  src/plugins/multifile/multifile.c
Labels: ready to merge

#2862 jna: upgraded dependency versions
  doc/news/_preparation_next_release.md
  src/bindings/jna/libelektra4j/pom.xml.in
Labels: ready to merge

#2867 format: check version of cmake-format
  doc/news/_preparation_next_release.md
  scripts/reformat-cmake
Labels: ready to merge

#2864 Fixes for gopts
  doc/news/_preparation_next_release.md
  src/plugins/gopts/CMakeLists.txt
  src/plugins/gopts/gopts.c
Labels: ready to merge

#2685 error: warning array concept added
  doc/decisions/README.md
  doc/decisions/warning-array.md
  doc/news/_preparation_next_release.md
Labels: ready to merge

#2877 Reformat CMake: Fix Version Detection
  doc/news/2019-02-26_0.8.26.md
  doc/news/_preparation_next_release.md
  scripts/reformat-cmake
Labels: bug, lang/shell, ready to merge

#2879 Travis: Use Homebrew Addon to Install Dependencies
  .travis.yml
  doc/news/_preparation_next_release.md
Labels: enhancement, lang/shell, ready to merge

#2892 API Check: Do Not Require Newline Before EOF
  doc/news/_preparation_next_release.md
  scripts/run_icheck
Labels: enhancement, lang/shell, ready to merge

#2809 Symbol Versioning
  cmake/ElektraCompiling.cmake
  cmake/Modules/LibAddLib.cmake
  doc/dev/README.md
  doc/dev/symbol-versioning.md
  doc/news/_preparation_next_release.md
  src/include/CMakeLists.txt
  src/include/kdbconfig.h.in
  src/include/kdbmacros.h
  src/libs/CMakeLists.txt
  src/libs/ease/symbols.map
  src/libs/elektra/CMakeLists.txt
  src/libs/elektra/README.md
  src/libs/elektra/libelektra-symbols.map
  src/libs/elektra/symbols.map
  src/libs/globbing/symbols.map
  src/libs/highlevel/symbols.map
  src/libs/invoke/symbols.map
  src/libs/io/symbols.map
  src/libs/loader/symbols.map
  src/libs/meta/symbols.map
  src/libs/notification/symbols.map
  src/libs/opts/symbols.map
  src/libs/plugin/symbols.map
  src/libs/pluginprocess/symbols.map
  src/libs/proposal/symbols.map
  src/libs/tools/src/CMakeLists.txt
  src/libs/typesystem/symbols.map
  src/libs/utility/symbols.map
  src/libs/version_gen.awk
  src/libs/versions.def
  src/symvertest/CMakeLists.txt
  src/symvertest/basic.c
  src/symvertest/basic.map
  src/symvertest/test.c
  src/symvertest/versions.map
Labels: ready to merge

#2902 Doxygen: Remove Deprecated Config Options
  doc/Doxyfile
  doc/news/_preparation_next_release.md
Labels: build, enhancement, ready to merge

#2903 Draw Plugins: Support Space Characters in Repository Path
  doc/news/_preparation_next_release.md
  scripts/draw-all-plugins
Labels: enhancement, lang/shell, ready to merge

#2887 Remove plugins
  doc/METADATA.ini
  doc/images/plugins.dot
  doc/images/plugins.png
  doc/news/_preparation_next_release.md
  doc/tutorials/mount.md
  doc/tutorials/validation.md
  src/plugins/README.md
  src/plugins/boolean/CMakeLists.txt
  src/plugins/boolean/README.md
  src/plugins/boolean/boolean.c
  src/plugins/boolean/boolean.h
  src/plugins/boolean/testmod_boolean.c
  src/plugins/cachefilter/CMakeLists.txt
  src/plugins/cachefilter/README.md
  src/plugins/cachefilter/cachefilter.c
  src/plugins/cachefilter/cachefilter.h
  src/plugins/cachefilter/testmod_cachefilter.c
  src/plugins/cpptype/CMakeLists.txt
  src/plugins/cpptype/README.md
  src/plugins/cpptype/cpptype.cpp
  src/plugins/cpptype/cpptype.hpp
  src/plugins/cpptype/testmod_cpptype.cpp
  src/plugins/cpptype/type_checker.hpp
  src/plugins/cpptype/types.cpp
  src/plugins/cpptype/types.hpp
  src/plugins/dini/CMakeLists.txt
  src/plugins/dini/README.md
  src/plugins/dini/dini.c
  src/plugins/dini/dini.h
  src/plugins/enum/CMakeLists.txt
  src/plugins/enum/README.md
  src/plugins/enum/enum.c
  src/plugins/enum/enum.h
  src/plugins/enum/testmod_enum.c
  src/plugins/regexstore/CMakeLists.txt
  src/plugins/regexstore/README.md
  src/plugins/regexstore/regexstore.cpp
  src/plugins/regexstore/regexstore.h
  src/plugins/required/CMakeLists.txt
  src/plugins/required/README.md
  src/plugins/required/required.c
  src/plugins/required/required.h
  src/plugins/simplespeclang/CMakeLists.txt
  src/plugins/simplespeclang/README.md
  src/plugins/simplespeclang/simplespeclang.cpp
  src/plugins/simplespeclang/simplespeclang.hpp
  src/plugins/struct/CMakeLists.txt
  src/plugins/struct/README.md
  src/plugins/struct/checker.cpp
  src/plugins/struct/checker.hpp
  src/plugins/struct/factory.hpp
  src/plugins/struct/struct.cpp
  src/plugins/struct/struct.hpp
  src/plugins/xmltool/README.md
  src/tools/kdb/convert.hpp
Labels: ready to merge

#2908 Symbol Versioning: Set Missing Project Name
  doc/news/_preparation_next_release.md
  src/symvertest/CMakeLists.txt
Labels: build, enhancement, lang/cmake, ready to merge

#2909 YAy PEG: Remove Plugin
  .cirrus.yml
  .travis.yml
  cmake/Modules/FindPEGTL.cmake
  doc/images/plugins.dot
  doc/images/plugins.png
  doc/images/qcachegrind.png
  doc/man/man7/elektra-plugins.7
  doc/news/2019-02-26_0.8.26.md
  doc/news/2019-08-06_0.9.0.md
  doc/news/_preparation_next_release.md
  doc/tutorials/benchmarking.md
  doc/tutorials/profiling.md
  scripts/benchmark-yaml.in
  scripts/docker/alpine/3.9/Dockerfile
  scripts/docker/debian/buster/Dockerfile
  scripts/docker/debian/sid/Dockerfile
  scripts/docker/debian/stretch/Dockerfile
  scripts/docker/ubuntu/disco/Dockerfile
  scripts/jenkins/Jenkinsfile
  src/plugins/README.md
  src/plugins/yaypeg/CMakeLists.txt
  src/plugins/yaypeg/README.md
  src/plugins/yaypeg/convert.cpp
  src/plugins/yaypeg/convert.hpp
  src/plugins/yaypeg/listener.cpp
  src/plugins/yaypeg/listener.hpp
  src/plugins/yaypeg/parser.in.hpp
  src/plugins/yaypeg/state.cpp
  src/plugins/yaypeg/state.hpp
  src/plugins/yaypeg/testmod_yaypeg.cpp
  src/plugins/yaypeg/walk.cpp
  src/plugins/yaypeg/walk.hpp
  src/plugins/yaypeg/yaypeg.cpp
  src/plugins/yaypeg/yaypeg.hpp
  src/plugins/yaypeg/yaypeg/comment.yaml
  src/plugins/yaypeg/yaypeg/double_quoted_scalar.hpp
  src/plugins/yaypeg/yaypeg/double_quoted_scalar.yaml
  src/plugins/yaypeg/yaypeg/list-list_map-mixed_scalars.hpp
  src/plugins/yaypeg/yaypeg/list-list_map-mixed_scalars.yaml
  src/plugins/yaypeg/yaypeg/list-plain_scalars.hpp
  src/plugins/yaypeg/yaypeg/list-plain_scalars.yaml
  src/plugins/yaypeg/yaypeg/map-list-plain_scalars.hpp
  src/plugins/yaypeg/yaypeg/map-list-plain_scalars.yaml
  src/plugins/yaypeg/yaypeg/map-map-plain_scalars.hpp
  src/plugins/yaypeg/yaypeg/map-map-plain_scalars.yaml
  src/plugins/yaypeg/yaypeg/map-null.hpp
  src/plugins/yaypeg/yaypeg/map-null.yaml
  src/plugins/yaypeg/yaypeg/map-plain_scalar.hpp
  src/plugins/yaypeg/yaypeg/map-plain_scalar.yaml
  src/plugins/yaypeg/yaypeg/map-plain_scalars.hpp
  src/plugins/yaypeg/yaypeg/map-plain_scalars.yaml
  src/plugins/yaypeg/yaypeg/null.hpp
  src/plugins/yaypeg/yaypeg/null.yaml
  src/plugins/yaypeg/yaypeg/plain_scalar-word_chars.hpp
  src/plugins/yaypeg/yaypeg/plain_scalar-word_chars.yaml
  src/plugins/yaypeg/yaypeg/plain_scalar-word_chars_space.hpp
  src/plugins/yaypeg/yaypeg/plain_scalar-word_chars_space.yaml
  src/plugins/yaypeg/yaypeg/single_quoted_scalar.hpp
  src/plugins/yaypeg/yaypeg/single_quoted_scalar.yaml
  tests/shell/check_oclint.sh
Labels: lang/cpp, ready to merge

#2914 Link Checker merge PRs before checking links
  .cirrus.yml
  doc/news/_preparation_next_release.md
  scripts/link-checker
Labels: ready to merge

#2825 kdb: kdbCommit
  doc/decisions/README.md
  doc/decisions/commit_function.md
  doc/news/_preparation_next_release.md
  src/include/kdbplugin.h
  src/include/kdbprivate.h
  src/libs/elektra/kdb.c
  src/libs/plugin/plugin.c
  src/plugins/blockresolver/blockresolver.c
  src/plugins/blockresolver/blockresolver.h
  src/plugins/curlget/curlget.c
  src/plugins/curlget/curlget.h
  src/plugins/doc/doc.c
  src/plugins/doc/doc.h
  src/plugins/gitresolver/gitresolver.c
  src/plugins/gitresolver/gitresolver.h
  src/plugins/multifile/multifile.c
  src/plugins/multifile/multifile.h
  src/plugins/resolver/resolver.c
  src/plugins/resolver/resolver.h
  src/plugins/resolver/testmod_resolver.c
  src/plugins/template/template.c
  src/plugins/template/template.h
  src/plugins/template/testmod_template.c
  tests/icheck.suppression
Labels: ready to merge

#2626 Initial setup of merge files
  doc/help/elektra-cmerge-strategy.md
  doc/help/kdb-cmerge.md
  doc/man/man1/kdb-cmerge.1
  doc/man/man7/elektra-cmerge-strategy.7
  doc/news/_preparation_next_release.md
  scripts/elektra-cmerge.sh
  src/include/kdbmerge.h
  src/libs/CMakeLists.txt
  src/libs/merge/CMakeLists.txt
  src/libs/merge/kdbmerge.c
  src/libs/merge/symbols.map
  src/tools/kdb/CMakeLists.txt
  src/tools/kdb/cmerge.cpp
  src/tools/kdb/cmerge.hpp
  src/tools/kdb/factory.hpp
  tests/ctest/CMakeLists.txt
  tests/ctest/test_cmerge.c
Labels: lang/c, lang/cpp, ready to merge

#2911 Conditionals: Use Explicit Type Conversion
  doc/news/_preparation_next_release.md
  src/plugins/conditionals/CMakeLists.txt
  src/plugins/conditionals/conditionals.c
Labels: build, enhancement, lang/c

#2916 Move conversion functions from highlevel to ease
  doc/news/_preparation_next_release.md
  src/include/elektra/conversion.h
  src/include/kdbease.h
  src/include/kdbtypes.h
  src/libs/ease/conversion.c
  src/libs/ease/symbols.map
  src/libs/highlevel/symbols.map
  src/plugins/type/CMakeLists.txt
  src/plugins/type/type.c
  src/plugins/type/types.c
  tests/icheck.suppression
Labels: ready to merge

#2919 Highlevel Bindings tutorial
  doc/news/_preparation_next_release.md
  doc/tutorials/highlevel-bindings.md
  doc/tutorials/language-bindings.md
Labels: ready to merge

#2915 Type: disabling restore
  doc/news/_preparation_next_release.md
  src/plugins/type/README.md
  src/plugins/type/testmod_type.c
  src/plugins/type/type.c
  src/plugins/type/types.c
Labels: ready to merge
