Repository ElektraInitiative/libelektra, pull requests merged in 2019-04, with the labels that each got.

#2568 Docker: Install Default JDK on Debian sid
  doc/man/man1/kdb-find-tools.1
  doc/man/man7/elektra-faq.7
  doc/man/man7/elektra-introduction.7
  doc/man/man7/elektra-namespaces.7
  doc/man/man7/elektra-plugins.7
  doc/news/_preparation_next_release.md
  scripts/docker/debian/sid/Dockerfile
Labels: bug, build, ready to merge

#2546 added badges to website
  doc/news/_preparation_next_release.md
  src/tools/rest-frontend/public/pages/main/website/home.html
Labels: cm2019s, enhancement, ready to merge

#2569 Yan LR: Fix Insertion of Map Start Tokens
  doc/news/_preparation_next_release.md
  scripts/docker/debian/sid/Dockerfile
  src/plugins/yanlr/yaml_lexer.cpp
Labels: bug, lang/cpp, ready to merge, usability

#2570 Coding: Add Guidelines for Markdown Headers
  doc/CODING.md
  doc/news/_preparation_next_release.md
Labels: enhancement, ready to merge

#2573 kdb: Don't fail if target-key has same value as source-key
  doc/help/kdb-cp.md
  doc/news/_preparation_next_release.md
  src/tools/kdb/cp.cpp
  tests/shell/shell_recorder/tutorial_wrapper/CMakeLists.txt
Labels: bug, cm2019s, enhancement, lang/cpp, ready to merge, usability

#2579 Workaround fix for issue #2441
  doc/news/_preparation_next_release.md
  src/tools/web/client/src/components/pages/Configuration.jsx
Labels: cm2019s, enhancement, lang/javascript, ready to merge

#2575 JNA: Improve Maven Integration Into Build System
  doc/news/_preparation_next_release.md
  src/bindings/jna/CMakeLists.txt
Labels: bug, build, enhancement, lang/cmake, lang/java, ready to merge

#2582 type: more boolean config
  doc/METADATA.ini
  doc/news/_preparation_next_release.md
  src/plugins/type/README.md
  src/plugins/type/testmod_type.c
  src/plugins/type/type.c
  src/plugins/type/type.h
  src/plugins/type/types.c
Labels: ready to merge

#2576 keyhelper: Fix calculation of relative path
  doc/news/_preparation_next_release.md
  src/libs/tools/src/helper/keyhelper.cpp
Labels: cm2019s, enhancement, lang/cpp, ready to merge

#2586 Fcrypt keyid fix
  doc/news/_preparation_next_release.md
  src/plugins/crypto/gpg.c
  src/plugins/fcrypt/fcrypt.c
Labels: ready to merge

#2590 Coveralls: Update Excluded Files
  doc/news/_preparation_next_release.md
  scripts/jenkins/Jenkinsfile
Labels: build, enhancement, ready to merge

#2457 mmapcache
  benchmarks/CMakeLists.txt
  benchmarks/kdb.c
  benchmarks/storage.c
  doc/CONTRACT.ini
  doc/news/_preparation_next_release.md
  src/include/kdbglobal.h
  src/include/kdbplugin.h
  src/include/kdbprivate.h
  src/libs/elektra/backend.c
  src/libs/elektra/kdb.c
  src/libs/elektra/mount.c
  src/libs/elektra/split.c
  src/libs/tools/src/plugin.cpp
  src/plugins/README.md
  src/plugins/cache/CMakeLists.txt
  src/plugins/cache/README.md
  src/plugins/cache/cache.c
  src/plugins/cache/cache.h
  src/plugins/cache/testmod_cache.c
  src/plugins/mmapstorage/internal.h
  src/plugins/mmapstorage/mmapstorage.c
  src/plugins/mmapstorage/testmod_mmapstorage.c
  src/plugins/resolver/resolver.c
  tests/ctest/test_splitget.c
Labels: ready to merge

#2594 Added keyhelper-test
  doc/news/_preparation_next_release.md
  src/libs/tools/tests/testtool_keyhelper.cpp
Labels: cm2019s, enhancement, lang/cpp, ready to merge

#2580 WIP: Yajl: Removing empty parent keys
  doc/news/_preparation_next_release.md
  src/plugins/yajl/README.md
  src/plugins/yajl/testmod_yajl.c
  src/plugins/yajl/yajl_parse.c
Labels: cm2019s, lang/c, ready to merge

#2599 YAML CPP: Convert Boolean Values
  doc/news/_preparation_next_release.md
  doc/tutorials/storage-plugins.md
  scripts/sed
  src/plugins/yamlcpp/README.md
  src/plugins/yamlcpp/read.cpp
  src/plugins/yamlcpp/write.cpp
  src/plugins/yamlcpp/yamlcpp.cpp
  tests/shell/shell_recorder/tutorial_wrapper/CMakeLists.txt
Labels: enhancement, lang/cpp, ready to merge

#2601 multifile: add support for cache
  doc/news/_preparation_next_release.md
  src/plugins/multifile/multifile.c
Labels: ready to merge

#2608 mmapcache: fix dependencies and segfault
  doc/news/_preparation_next_release.md
  src/libs/elektra/mount.c
  src/plugins/cache/CMakeLists.txt
  src/plugins/cache/cache.c
Labels: ready to merge

#2611 Fix kdb cp
  doc/help/kdb-cp.md
  doc/news/_preparation_next_release.md
  src/tools/kdb/cp.cpp
  tests/shell/shell_recorder/tutorial_wrapper/CMakeLists.txt
Labels: bug, cm2019s, enhancement, lang/cpp, ready to merge

#2622 2591 crypto ini fix
  doc/news/_preparation_next_release.md
  src/plugins/crypto/gpg.c
  src/plugins/crypto/gpg.h
  src/plugins/crypto/helper.c
  src/plugins/crypto/helper.h
Labels: ready to merge

#2618 YAML CPP: Improve Support for Sparse Key Sets
  doc/news/_preparation_next_release.md
  src/plugins/yamlcpp/README.md
  src/plugins/yamlcpp/read.cpp
  src/plugins/yamlcpp/write.cpp
Labels: enhancement, lang/cpp, ready to merge

#2625 cache: fix file name check
  doc/news/_preparation_next_release.md
  src/libs/elektra/kdb.c
  src/libs/elektra/split.c
Labels: ready to merge, urgent

#2629 Docker: Install Bison & YAEP on Debian Sid
  doc/news/_preparation_next_release.md
  scripts/docker/debian/sid/Dockerfile
  scripts/docker/debian/stretch/Dockerfile
Labels: build, enhancement, ready to merge

#2628 Docker: Install PEGTL on Alpine Linux
  doc/news/_preparation_next_release.md
  scripts/docker/alpine/3.9/Dockerfile
Labels: enhancement, ready to merge

#2627 YAy PEG: Add Support for PEGTL 2.8
  doc/news/_preparation_next_release.md
  src/plugins/yaypeg/CMakeLists.txt
  src/plugins/yaypeg/README.md
  src/plugins/yaypeg/parser.in.hpp
Labels: enhancement, lang/cpp, ready to merge

#2630 Logging changes
  doc/decisions/logging.md
  doc/dev/logging.md
  doc/news/_preparation_next_release.md
  src/error/exporterrors.cpp
  src/include/kdbassert.h
  src/include/kdbhelper.h
  src/include/kdblogger.h
  src/include/kdbmacros.h
  src/libs/elektra/log.c
  src/libs/opts/opts.c
Labels: ready to merge

#2631 Fixsync
  doc/news/_preparation_next_release.md
  src/tools/kdb/cmdline.cpp
  src/tools/kdb/mount.cpp
Labels: ready to merge

#2637 Logger: Fix Minor Problems
  doc/dev/logging.md
  doc/news/_preparation_next_release.md
  src/include/kdblogger.h
  src/libs/elektra/log.c
Labels: bug, enhancement, lang/c, ready to merge

#2638 YAy PEG: Fix Support for Compact Mappings & Sequences
  doc/news/_preparation_next_release.md
  src/plugins/yaypeg/convert.cpp
  src/plugins/yaypeg/listener.cpp
  src/plugins/yaypeg/parser.in.hpp
  src/plugins/yaypeg/walk.cpp
  src/plugins/yaypeg/yaypeg.cpp
  src/plugins/yaypeg/yaypeg.hpp
Labels: bug, lang/cpp, ready to merge

#2639 mmapstorage: add import/export compatibility
  doc/news/_preparation_next_release.md
  src/plugins/mmapstorage/README.md
  src/plugins/mmapstorage/internal.h
  src/plugins/mmapstorage/mmapstorage.c
  src/plugins/mmapstorage/shelltests.md
  src/plugins/mmapstorage/testmod_mmapstorage.c
  tests/shell/shell_recorder/tutorial_wrapper/CMakeLists.txt
Labels: ready to merge

#2642 KDB List-Tools: Support Space Characters in `KDB_EXEC_PATH`
  doc/help/kdb-list-tools.md
  doc/news/_preparation_next_release.md
  scripts/list-tools.in
Labels: bug, lang/shell, ready to merge

#2643 Fast Cache
  doc/news/_preparation_next_release.md
  src/libs/elektra/kdb.c
  tests/kdb/testkdb_ensure.cpp
Labels: ready to merge

#2635 Enable MSR for crypto.md
  cmake/ElektraCache.cmake
  cmake/Modules/FindLibGpgme.cmake
  cmake/Modules/LibAddMacros.cmake
  cmake/Modules/LibAddTest.cmake
  doc/news/_preparation_next_release.md
  doc/tutorials/crypto.md
  src/tools/gen-gpg-testkey/CMakeLists.txt
  src/tools/gen-gpg-testkey/gen-gpg-testkey.c
  tests/shell/include_common.sh.in
  tests/shell/shell_recorder/tutorial_wrapper/CMakeLists.txt
Labels: ready to merge

#2647 Travis: Fix Caching Directive
  .travis.yml
  doc/news/_preparation_next_release.md
Labels: bug, ready to merge

#2646 Coveralls: Improve Exclusion Patterns
  doc/news/_preparation_next_release.md
  scripts/docker/debian/stretch/Dockerfile
  scripts/jenkins/Jenkinsfile
Labels: bug, lang/shell, ready to merge

#2645 Reformat Shfmt: Format Additional Files
  doc/news/_preparation_next_release.md
  scripts/change-resolver-symlink.in
  scripts/change-storage-symlink.in
  scripts/configure-firefox.in
  scripts/elektrify-getenv.in
  scripts/elektrify-open.in
  scripts/install-sh-completion.in
  scripts/make-source-package.in
  scripts/reformat-shfmt
Labels: enhancement, lang/shell, ready to merge
