Repository ElektraInitiative/libelektra, pull requests merged in 2019-02, with the labels that each got.

#2350 Highlevel API improvements
  cmake/CMakeLists.txt
  cmake/ElektraConfig.cmake.in
  doc/news/_preparation_next_release.md
  examples/external/README.md
  examples/external/pkgconfig/Makefile
  examples/highlevel/README.md
  examples/highlevel/cmake/CMakeLists.txt
  examples/highlevel/cmake/application.c
  examples/highlevel/pkgconfig/Makefile
  examples/highlevel/pkgconfig/application.c
  scripts/run_all.in
  src/include/CMakeLists.txt
  src/include/elektra.h
  src/include/elektra/CMakeLists.txt
  src/include/kdbos.h
  src/include/kdbprivate.h
  src/libs/elektra/keyset.c
  src/libs/highlevel/CMakeLists.txt
  src/libs/highlevel/README.md
  src/libs/highlevel/elektra-highlevel.pc.in
  src/libs/highlevel/elektra.c
  src/libs/highlevel/elektra_array_value.c
  tests/ctest/test_array.c
  tests/kdb/testkdb_highlevel.cpp
  tests/shell/CMakeLists.txt
  tests/shell/check_gen.sh.disabled
  tests/shell/external/CMakeLists.txt
  tests/shell/external/check_example.sh
  tests/shell/external/check_example_highlevel.sh
  tests/shell/include_common.sh.in
  tests/shell/run_all.sh
Labels: ready to merge

#2359 Sanitizer: Update Blacklist for GNU C++ Library 8
  doc/news/_preparation_next_release.md
  scripts/jenkins/Jenkinsfile
  tests/sanitizer.blacklist
Labels: bug, build, ready to merge

#2355 YAMBi: Update Deprecated Parser Directive
  doc/news/_preparation_next_release.md
  src/plugins/yambi/CMakeLists.txt
  src/plugins/yambi/parser.ypp
Labels: build, enhancement, ready to merge

#2356 IO GLib: Fix Linking Problems Properly
  cmake/Modules/FindGLib.cmake
  doc/news/_preparation_next_release.md
  examples/CMakeLists.txt
  src/bindings/io/glib/CMakeLists.txt
  src/bindings/io/glib/example/CMakeLists.txt
Labels: build, enhancement, ready to merge

#2357 Augeas: Change Prefix for Lens Directory on macOS
  cmake/Modules/FindAugeas.cmake
  doc/news/_preparation_next_release.md
Labels: enhancement, ready to merge

#2360 CMake: provide plugin name as compiler definition
  cmake/Modules/LibAddPlugin.cmake
  doc/news/_preparation_next_release.md
  src/plugins/base64/CMakeLists.txt
  src/plugins/crypto/CMakeLists.txt
  src/plugins/fcrypt/CMakeLists.txt
  src/plugins/gpgme/CMakeLists.txt
Labels: ready to merge

#2349 Iconv: Fix Linking Problems
  .cirrus.yml
  cmake/Modules/FindIconv.cmake
  doc/news/_preparation_next_release.md
  src/plugins/filecheck/CMakeLists.txt
  src/plugins/iconv/CMakeLists.txt
Labels: bug, build, ready to merge

#2364 highlevel: fix linker flags
  doc/news/_preparation_next_release.md
  examples/highlevel/README.md
  src/libs/highlevel/CMakeLists.txt
Labels: work in progress

#2366 Cirrus: Install GPGME on macOS
  .cirrus.yml
  cmake/Modules/FindLibGpgme.cmake
  doc/news/_preparation_next_release.md
  src/bindings/cpp/tests/CMakeLists.txt
  src/plugins/crypto/CMakeLists.txt
  src/plugins/gpgme/CMakeLists.txt
Labels: build, enhancement, ready to merge

#2376 Debian: Update Build Instructions for YAy PEG Plugin
  debian/elektra-tests.install
  debian/libelektra4-experimental.install
Labels: bug, build

#2369 Improve CMake Find Modules & Move Travis macOS Build Jobs to Cirrus CI
  .cirrus.yml
  .travis.yml
  cmake/Modules/FindLibBotan.cmake
  cmake/Modules/FindLibGcrypt.cmake
  cmake/Modules/FindLibGit2.cmake
  cmake/Modules/FindLibOpenSSL.cmake
  cmake/Modules/FindLibgcrypt.cmake
  cmake/Modules/FindZeroMQ.cmake
  cmake/Modules/Findlibuv.cmake
  cmake/Modules/Findyaml-cpp.cmake
  doc/news/_preparation_next_release.md
  examples/CMakeLists.txt
  scripts/docker/README.md
  src/bindings/io/uv/CMakeLists.txt
  src/bindings/io/uv/example/CMakeLists.txt
  src/libs/io/adapter/zeromq/CMakeLists.txt
  src/plugins/crypto/CMakeLists.txt
  src/plugins/curlget/CMakeLists.txt
  src/plugins/dbusrecv/CMakeLists.txt
  src/plugins/gitresolver/CMakeLists.txt
  src/plugins/gitresolver/gitresolver_test.c
  src/plugins/jni/CMakeLists.txt
  src/plugins/xerces/CMakeLists.txt
  src/plugins/yaypeg/CMakeLists.txt
  src/plugins/zeromqrecv/CMakeLists.txt
  src/plugins/zeromqsend/CMakeLists.txt
  src/tools/hub-zeromq/CMakeLists.txt
Labels: build, enhancement, ready to merge

#2375 highlevel: rename external tests
  doc/news/_preparation_next_release.md
  examples/highlevel/README.md
  tests/shell/external/CMakeLists.txt
  tests/shell/external/example.sh
  tests/shell/external/example_highlevel.sh
  tests/shell/run_all.sh
Labels: ready to merge

#2368 KDB_DB_SPEC improvements
  CMakeLists.txt
  cmake/ElektraCache.cmake
  cmake/Modules/LibAddPlugin.cmake
  doc/news/_preparation_next_release.md
  src/include/CMakeLists.txt
  src/include/kdbconfig.h.in
  src/plugins/resolver/filename.c
  src/plugins/resolver/testmod_resolver.c
  tests/shell/check_resolver.sh
  tests/shell/include_common.sh.in
Labels: ready to merge

#2385 Yan LR: Fix Comment Handling & Improve Error Output
  cmake/Modules/FindLibOpenSSL.cmake
  doc/help/kdb-restore.md
  doc/man/man1/kdb-restore.1
  doc/man/man7/elektra-libs.7
  doc/news/_preparation_next_release.md
  doc/tutorials/command-line-options.md
  src/plugins/path/README.md
  src/plugins/yanlr/README.md
  src/plugins/yanlr/error_listener.cpp
  src/plugins/yanlr/error_listener.hpp
  src/plugins/yanlr/yaml_lexer.cpp
  src/plugins/yanlr/yanlr.cpp
Labels: bug, enhancement, ready to merge, usability

#2387 YAy PEG: Fix Segfault Caused by Empty Input
  doc/news/_preparation_next_release.md
  src/plugins/yambi/yambi/null.yaml
  src/plugins/yanlr/yanlr/null.yaml
  src/plugins/yawn/yawn/null.yaml
  src/plugins/yaypeg/parser.hpp
  src/plugins/yaypeg/yaypeg/null.yaml
Labels: bug, ready to merge

#2391 Cirrus: Use Compiler Option `-Werror` on FreeBSD
  .cirrus.yml
  doc/news/_preparation_next_release.md
Labels: enhancement, ready to merge

#2392 YAMBi: Fix Handling of Comments at End of File
  doc/news/_preparation_next_release.md
  src/plugins/yambi/lexer.cpp
Labels: bug, ready to merge

#2390 YAwn: Fix Comment Handling & Improve Error Messages
  doc/news/_preparation_next_release.md
  src/plugins/yawn/README.md
  src/plugins/yawn/convert.cpp
  src/plugins/yawn/error_listener.cpp
  src/plugins/yawn/lexer.cpp
Labels: bug, enhancement, ready to merge, usability

#2395 Cirrus: Make Sure Uninstall Procedure Removes All Installed Files on macOS
  .cirrus.yml
  cmake/ElektraUninstall.cmake
  doc/news/_preparation_next_release.md
Labels: enhancement, ready to merge, usability

#2393 CMake: Set Project Description and Homepage URL
  CMakeLists.txt
  doc/news/_preparation_next_release.md
Labels: enhancement, ready to merge

#2396 Yan LR: Improve Syntax Error Messages
  doc/news/_preparation_next_release.md
  src/plugins/yanlr/CMakeLists.txt
  src/plugins/yanlr/README.md
  src/plugins/yanlr/YAML.g4
  src/plugins/yanlr/YAML.tokens
  src/plugins/yanlr/error_listener.cpp
  src/plugins/yanlr/yaml_lexer.cpp
  src/plugins/yanlr/yaml_lexer.hpp
Labels: enhancement, ready to merge

#2398 YAMBi: Emit Different End Token for Map/Sequence
  doc/news/_preparation_next_release.md
  src/plugins/yambi/README.md
  src/plugins/yambi/lexer.cpp
  src/plugins/yambi/lexer.hpp
  src/plugins/yambi/parser.ypp
  src/plugins/yambi/symbol.hpp
Labels: enhancement, ready to merge, usability

#2401 Tests: Various Minor Improvements
  .cirrus.yml
  doc/news/_preparation_next_release.md
  src/plugins/typechecker/README.md
  src/plugins/yamlcpp/README.md
Labels: bug, enhancement, ready to merge

#2402 Libopts improvements
  doc/news/_preparation_next_release.md
  doc/tutorials/command-line-options.md
  examples/opts.c
  src/libs/opts/opts.c
  tests/ctest/test_opts.c
Labels: ready to merge

#2403 YAwn: Minor Updates
  doc/news/_preparation_next_release.md
  src/plugins/yawn/CMakeLists.txt
  src/plugins/yawn/README.md
  src/plugins/yawn/lexer.cpp
  src/plugins/yawn/lexer.hpp
  src/plugins/yawn/token.cpp
  src/plugins/yawn/token.hpp
  src/plugins/yawn/yaml.bnf
Labels: bug, enhancement, ready to merge

#2404 Spelling: Add Test to Check for Common Spelling Mistakes
  doc/man/man7/elektra-libs.7
  doc/news/_preparation_next_release.md
  src/libs/README.md
  tests/shell/CMakeLists.txt
  tests/shell/check_spelling.sh
Labels: enhancement, ready to merge

#2418 Jenkins: Test Shell Formatting in Build Job `formatting-check`
  doc/news/_preparation_next_release.md
  scripts/docker/debian/sid/Dockerfile
Labels: build, enhancement, ready to merge

#2420 Python 2: Fix Detection of Include Directory on macOS
  doc/news/_preparation_next_release.md
  src/bindings/swig/python2/CMakeLists.txt
Labels: bug, build, ready to merge, usability

#2421 Cirrus: Check Formatting of Source Files in macOS Build Jobs
  .cirrus.yml
  doc/news/_preparation_next_release.md
  scripts/reformat-source
  src/plugins/yawn/token.cpp
  tests/shell/check_oclint.sh
Labels: bug, build, ready to merge

#2399 Highlevel API fixes
  .idea/codeStyles/Project.xml
  doc/news/_preparation_next_release.md
  src/error/specification_highlevel
  src/include/CMakeLists.txt
  src/include/elektra.h
  src/include/kdbconfig.h.in
  src/include/kdbtypes.h
  src/libs/highlevel/README.md
  src/libs/highlevel/elektra.c
  src/libs/highlevel/elektra_array_value.c
  src/libs/highlevel/elektra_conversion.c
  src/libs/highlevel/elektra_error.c
  src/libs/highlevel/elektra_value.c
  tests/kdb/testkdb_highlevel.cpp
Labels: ready to merge

#2428 Build: Remove `configure` Script
  configure
  doc/news/_preparation_next_release.md
Labels: enhancement, ready to merge, usability

#2429 Don't reformat gitignored files
  cmake/Modules/DownloadProject.cmake
  doc/news/_preparation_next_release.md
  scripts/reformat-cmake
  scripts/reformat-markdown
  scripts/reformat-shfmt
  scripts/reformat-source
Labels: ready to merge

#2431 Yan LR: Improve Error Messages
  doc/news/_preparation_next_release.md
  scripts/docker/README.md
  scripts/docker/debian/sid/Dockerfile
  src/plugins/yanlr/CMakeLists.txt
  src/plugins/yanlr/README.md
  src/plugins/yanlr/RenameSymbols.cmake
  src/plugins/yanlr/testmod_yanlr.cpp
  src/plugins/yanlr/yaml_lexer.cpp
  src/plugins/yanlr/yaml_lexer.hpp
Labels: enhancement, ready to merge, usability

#2438 Test: Add Instructions on How To Fix Formatting Problems to Formatting Test
  doc/news/_preparation_next_release.md
  scripts/reformat-source
  tests/shell/check_formatting.sh
  tests/shell/include_common.sh.in
Labels: enhancement, ready to merge, usability

#2436 Ruby: Improve Ruby Detection on macOS
  .cirrus.yml
  doc/news/_preparation_next_release.md
  src/bindings/swig/ruby/CMakeLists.txt
  src/plugins/ruby/CMakeLists.txt
Labels: build, enhancement, ready to merge, usability

#2432 highlevel: remove most of error handling from public API
  doc/news/_preparation_next_release.md
  src/error/exporterrors.cpp
  src/include/elektra/error.h
  src/include/kdbprivate.h
  src/libs/highlevel/README.md
  src/libs/highlevel/elektra.c
  tests/kdb/testkdb_highlevel.cpp
Labels: ready to merge
