Repository ElektraInitiative/libelektra, pull requests merged in 2019-10, with the labels that each got.

#3021 Path: Fix Markdown Shell Recorder Test
  doc/news/_preparation_next_release.md
  src/plugins/path/README.md
Labels: bug, lang/shell, ready to merge

#3026 Cleanup scripts
  doc/news/_preparation_next_release.md
  scripts/CMakeLists.txt
  scripts/completion/CMakeLists.txt
  scripts/kdb/list-tools.in
Labels: ready to merge

#3004 Remove elektra
  doc/news/_preparation_next_release.md
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/Elektra.java
  src/bindings/rust/README.md
  src/bindings/rust/elektra-sys/build.rs.in
  src/bindings/rust/elektra-sys/published_build.rs
  src/libs/elektra/CMakeLists.txt
  src/libs/elektra/symbols.map
  src/libs/invoke/CMakeLists.txt
  src/libs/pluginprocess/CMakeLists.txt
Labels: ready to merge

#2988 Rename keyIsDirectBelow to keyIsDirectlyBelow
  doc/news/_preparation_next_release.md
  doc/todo/FUTURE
  examples/functional.c
  examples/iterate.c
  src/bindings/cpp/include/key.hpp
  src/bindings/glib/gelektra-key.c
  src/bindings/intercept/fs/intercept.c
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/Elektra.java
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/Key.java
  src/bindings/jna/libelektra4j/src/test/java/org/libelektra/KeyTest.java
  src/bindings/rust/elektra/src/readable.rs
  src/include/kdb.h.in
  src/libs/ease/array.c
  src/libs/elektra/keytest.c
  src/libs/elektra/symbols.map
  src/plugins/glob/glob.c
  src/plugins/hosts/hosts-set.c
  src/plugins/ini/ini.c
  src/plugins/passwd/passwd.c
  src/plugins/reference/reference.c
  src/plugins/spec/spec.c
  tests/abi/testabi_key.c
  tests/abi/testabi_ks.c
Labels: ready to merge

#3033 doc: xerces add homebrew dependency instructions
  doc/news/_preparation_next_release.md
  src/plugins/xerces/README.md
Labels: lang/markdown, ready to merge

#3025 Travis: Build and Test Elektra on Ubuntu Bionic Beaver
  .travis.yml
  doc/news/_preparation_next_release.md
  doc/tutorials/language-bindings.md
  src/libs/elektra/log.c
  src/plugins/dbus/testmod_dbus.c
Labels: bug, continuous integration, enhancement, lang/c, lang/shell, ready to merge

#3040 tools: fix key description in gen-gpg-testkey
  doc/news/_preparation_next_release.md
  src/tools/gen-gpg-testkey/gen-gpg-testkey.c
Labels: ready to merge

#3038 Remove keyRel and keyRel2
  doc/help/elektra-key-names.md
  doc/man/man7/elektra-key-names.7
  doc/news/_preparation_next_release.md
  doc/todo/FUTURE
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/Elektra.java
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/Key.java
  src/bindings/jna/libelektra4j/src/test/java/org/libelektra/KeyTest.java
  src/include/kdb.h.in
  src/include/kdbproposal.h
  src/libs/elektra/backend.c
  src/libs/elektra/keyset.c
  src/libs/elektra/keytest.c
  src/libs/elektra/mount.c
  src/libs/elektra/plugin.c
  src/libs/elektra/split.c
  src/libs/elektra/symbols.map
  src/libs/proposal/proposal.c
  src/plugins/conditionals/conditionals.c
  src/plugins/csvstorage/csvstorage.c
  src/plugins/dump/dump.cpp
  src/plugins/hexcode/hexcode.c
  src/plugins/hosts/hosts-set.c
  src/plugins/list/list.c
  src/plugins/mmapstorage/mmapstorage.c
  src/plugins/noresolver/noresolver.c
  src/plugins/resolver/resolver.c
  tests/abi/testabi_rel.c
  tests/ctest/test_proposal.c
Labels: ready to merge

#3042 Remove & move parts of kdbproposal
  doc/news/_preparation_next_release.md
  src/bindings/cpp/include/kdbvalue.hpp
  src/include/kdbease.h
  src/include/kdbhelper.h
  src/include/kdbinternal.h
  src/include/kdbprivate.h
  src/include/kdbproposal.h
  src/libs/ease/functional.c
  src/libs/elektra/global.c
  src/libs/elektra/proposal.c
  src/libs/elektra/split.c
  src/libs/elektra/symbols.map
  src/libs/proposal/proposal.c
  src/libs/proposal/symbols.map
  src/plugins/hosts/keymetaformatting.c
  src/plugins/keytometa/keytometa.c
  src/tools/kdb/get.cpp
  tests/ctest/CMakeLists.txt
  tests/ctest/test_ks.c
  tests/ctest/test_proposal.c
  tests/ctest/test_spec.c
Labels: ready to merge

#3051 Documentation: Fix Broken Links
  doc/news/_preparation_next_release.md
  src/plugins/README.md
  src/plugins/ni/README.md
Labels: lang/markdown, ready to merge

#3043 Cirrus: Use Xcode 11.1
  .cirrus.yml
  doc/news/_preparation_next_release.md
  tests/sanitizer.blacklist
Labels: continuous integration, enhancement, lang/shell, ready to merge

#3047 Fix rust test case
  doc/news/_preparation_next_release.md
  src/bindings/rust/CMakeLists.txt
  src/bindings/rust/elektra/src/kdb.rs
Labels: ready to merge

#3053 Docker: Add Dockerfile for Ubuntu Bionic Beaver
  doc/news/_preparation_next_release.md
  scripts/docker/ubuntu/bionic/Dockerfile
  scripts/jenkins/Jenkinsfile
  tests/linkchecker.whitelist
Labels: continuous integration, enhancement, lang/groovy, ready to merge

#3058 Improve error messages (crypto, fcrypt, gpgme)
  doc/news/_preparation_next_release.md
  src/plugins/crypto/botan_operations.cpp
  src/plugins/crypto/gcrypt_operations.c
  src/plugins/crypto/helper.c
  src/plugins/crypto/openssl_operations.c
  src/plugins/fcrypt/fcrypt.c
  src/plugins/gpgme/gpgme.c
Labels: ready to merge

#3044 Various bugfixes
  doc/news/_preparation_next_release.md
  examples/codegen/econf/README.md
  examples/codegen/tree/README.md
  src/plugins/specload/README.md
  src/plugins/specload/specload.c
  src/plugins/specload/testmod_specload.c
  src/tools/kdb/gen/templates/highlevel.c.mustache
  tests/shell/gen/highlevel/empty.expected.c
  tests/shell/gen/highlevel/enum.expected.c
  tests/shell/gen/highlevel/externalspec.expected.c
  tests/shell/gen/highlevel/externalwithdefaults.expected.c
  tests/shell/gen/highlevel/nosetter.expected.c
  tests/shell/gen/highlevel/notype.expected.c
  tests/shell/gen/highlevel/simple.expected.c
  tests/shell/gen/highlevel/struct.expected.c
Labels: ready to merge

#3070 Kdb list-commands order output
  doc/news/_preparation_next_release.md
  src/plugins/README.md
  src/tools/kdb/factory.hpp
  src/tools/kdb/pluginlist.cpp
Labels: ready to merge

#3064 Documentation: Remove Old Links & Update Compile Instructions
  doc/COMPILE.md
  doc/news/2014-06-21_0.8.6.md
  doc/news/2014-11-04_0.8.9.md
  doc/news/_preparation_next_release.md
Labels: enhancement, lang/markdown, ready to merge

#3103 Conversion Engine: Disable Test
  doc/news/_preparation_next_release.md
  src/tools/website-backend/tests/CMakeLists.txt
Labels: bug, build, continuous integration, lang/cpp, ready to merge

#3062 Error hierarchy doc improvements
  doc/decisions/error_codes.md
  doc/dev/error-categorization.md
  doc/news/_preparation_next_release.md
Labels: ready to merge

#3071 error: Improved error message for range plugin
  doc/news/_preparation_next_release.md
  src/bindings/jna/README.md
  src/plugins/range/range.c
  src/plugins/range/range.h
Labels: lang/c, ready to merge

#3096 Fix reformat
  doc/news/_preparation_next_release.md
  scripts/dev/reformat-all
  scripts/dev/reformat-markdown
  scripts/dev/reformat-shfmt
Labels: lang/shell, ready to merge

#3076 Various documentation improvements
  doc/CODING.md
  doc/TESTING.md
  doc/news/_preparation_next_release.md
  doc/tutorials/run_reformatting_script_with_docker.md
Labels: ready to merge

#3101 Vagrant: Add Vagrantfile for FreeBSD VM
  .gitignore
  doc/news/_preparation_next_release.md
  scripts/vagrant/freebsd/README.md
  scripts/vagrant/freebsd/Vagrantfile
  scripts/vagrant/freebsd/provision.sh
Labels: documentation, enhancement, lang/ruby, ready to merge

#3108 Docker: Remove Haskell Packages
  doc/news/_preparation_next_release.md
  scripts/docker/debian/stretch/Dockerfile
  scripts/docker/jenkinsnode/Dockerfile
  scripts/docker/jenkinsnode/README.md
Labels: cleanup, continuous integration, ready to merge

#3097 Markdown Shell Recorder: Fix FreeBSD Specific Problems
  doc/news/_preparation_next_release.md
  tests/shell/shell_recorder/tutorial_wrapper/markdown_shell_recorder.sh
Labels: bug, lang/shell, ready to merge

#3052 Replace elektraRenameKeys with ksRenameKeys
  doc/news/_preparation_next_release.md
  src/include/kdbprivate.h
  src/include/kdbproposal.h
  src/libs/elektra/backend.c
  src/libs/elektra/kdb.c
  src/libs/elektra/mount.c
  src/libs/elektra/plugin.c
  src/libs/elektra/proposal.c
  src/libs/elektra/symbols.map
  src/libs/proposal/proposal.c
  src/libs/proposal/symbols.map
  src/plugins/csvstorage/CMakeLists.txt
  src/plugins/csvstorage/csvstorage.c
  src/plugins/list/list.c
  src/plugins/multifile/multifile.c
  tests/ctest/test_ks.c
Labels: ready to merge

#3118 Kdb plugin list doc
  doc/help/kdb-plugin-list.md
  doc/news/_preparation_next_release.md
  src/tools/kdb/pluginlist.cpp
  src/tools/kdb/pluginlist.hpp
Labels: ready to merge

#3121 Release: Move News Items to Correct Location
  doc/news/_preparation_next_release.md
  tests/linkchecker.whitelist
Labels: bug, documentation, lang/markdown, ready to merge

#3046 Jna improvments part 2
  doc/news/_preparation_next_release.md
  src/bindings/jna/README.md
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/Elektra.java
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/Key.java
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/KeySet.java
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/Plugin.java
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/PluginLoader.java
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/plugin/NativePlugin.java
  src/bindings/jna/libelektra4j/src/test/java/org/libelektra/ExceptionMapperIT.java
Labels: ready to merge

#3113 build: make jni depend on jna to avoid mvn dependency resolution fails
  doc/news/_preparation_next_release.md
  src/plugins/jni/CMakeLists.txt
Labels: ready to merge

#3127 Man Page: Revert Single Line Date Updates
  doc/CMakeLists.txt
  doc/help/CMakeLists.txt
  doc/news/_preparation_next_release.md
  scripts/cmake/ElektraManPage.cmake
  scripts/cmake/Modules/LibAddMacros.cmake
  scripts/git-checkout-ronn-files
  src/plugins/jni/CMakeLists.txt
Labels: build, documentation, enhancement, lang/cmake, ready to merge
