Repository ElektraInitiative/libelektra, pull requests merged in 2020-05, with the labels that each got.

#3424 Enabling building Bionic packages.
  doc/news/_preparation_next_release.md
  scripts/jenkins/Jenkinsfile
Labels: ready to merge

#3430 Documentation for Ubuntu Bionic Packages.
  doc/INSTALL.md
  doc/news/_preparation_next_release.md
Labels: documentation, ready to merge

#3372 tool: elektrad - add documentation endpoint
  doc/news/_preparation_next_release.md
  src/tools/elektrad/doc_handler.go
  src/tools/elektrad/router.go
Labels: ready to merge

#3434 jenkins: add fedora 32 asan build
  doc/news/_preparation_next_release.md
  scripts/docker/fedora/31/Dockerfile
  scripts/docker/fedora/32/Dockerfile
  scripts/jenkins/Jenkinsfile
Labels: ready to merge

#3433 Removed a broken link from the link checker.
  doc/news/_preparation_next_release.md
  tests/linkchecker.whitelist
Labels: build, ready to merge

#3439 Fix Rust build: Readd Cargo.lock
  doc/news/_preparation_next_release.md
  src/bindings/rust/Cargo.lock
Labels: ready to merge

#3441 website-backend: disable build
  doc/news/_preparation_next_release.md
  scripts/docker/website/backend/Dockerfile
  scripts/jenkins/Jenkinsfile
Labels: ready to merge

#3438 Plugins
  doc/news/_preparation_next_release.md
  doc/todo/BINDINGS
  doc/todo/DOCUMENTATION
  doc/todo/FRONT_END
  doc/todo/FUTURE
  doc/todo/OPTIMIZE
  doc/todo/PLUGINS
  doc/todo/PROPOSALS
  doc/todo/ROADMAP.md
  doc/todo/TODO
  doc/todo/TOOLS
  src/plugins/blockresolver/README.md
  src/plugins/csvstorage/README.md
  src/plugins/gitresolver/README.md
  src/plugins/hosts/README.md
  src/plugins/list/README.md
  src/plugins/multifile/README.md
  src/plugins/resolver/README.md
  src/plugins/simpleini/README.md
  src/plugins/spec/README.md
  src/plugins/unit/README.md
  src/plugins/wresolver/README.md
Labels: ready to merge

#3432 doc: Fixed old path for reformat script
  doc/news/_preparation_next_release.md
  doc/tutorials/run_reformatting_script_with_docker.md
Labels: documentation, ready to merge

#3402 Webd: update dependencies
  doc/news/_preparation_next_release.md
  src/tools/webd/package-lock.json
Labels: dependencies, work in progress

#3442 0.9.2 Release preparation, fix website deployment
  .travis.yml
  doc/news/_preparation_next_release.md
  doc/todo/RELEASE
  scripts/docker/website/frontend/Dockerfile
  scripts/jenkins/Jenkinsfile
  src/tools/website-frontend/package.json
  src/tools/website-frontend/public/pages/main/auth/login.html
  src/tools/website-frontend/public/pages/main/auth/registration.html
  src/tools/website-frontend/public/pages/main/auth/template.html
  src/tools/website-frontend/public/pages/main/entries/create.html
  src/tools/website-frontend/public/pages/main/entries/delete_confirmation.html
  src/tools/website-frontend/public/pages/main/entries/details.html
  src/tools/website-frontend/public/pages/main/entries/edit.html
  src/tools/website-frontend/public/pages/main/entries/form.html
  src/tools/website-frontend/public/pages/main/entries/search.html
  src/tools/website-frontend/public/pages/main/entries/template.html
  src/tools/website-frontend/public/pages/main/template.html
  src/tools/website-frontend/public/pages/main/users/details.html
  src/tools/website-frontend/public/pages/main/users/search.html
  src/tools/website-frontend/public/pages/main/users/template.html
  src/tools/website-frontend/public/pages/main/website/conversion.html
  src/tools/website-frontend/resources/assets/js/config/routes.js
Labels: work in progress
