Repository ElektraInitiative/libelektra, pull requests merged in 2020-11, with the labels that each got.

#3550 CMake: use Lua 5.4 when available.
  doc/news/_preparation_next_release.md
  scripts/cmake/Modules/FindLua.cmake
Labels: ready to merge

#3537 Remove plugins mpranj
  doc/images/plugins.dot.flatten
  doc/images/plugins.pdf
  doc/images/plugins.png
  doc/images/plugins.ps
  doc/news/_preparation_next_release.md
  scripts/cmake/ElektraCache.cmake
  scripts/docker/fedora/32/Dockerfile
  src/include/kdbconfig.h.in
  src/libs/loader/dl.c
  src/plugins/jni/jni.c
Labels: ready to merge

#3201 Remove kdbproposal
  doc/man/man7/elektra-libs.7
  doc/news/_preparation_next_release.md
  src/include/kdbinternal.h
  src/include/kdbproposal.h
  src/libs/CMakeLists.txt
  src/libs/README.md
  src/libs/ease/symbols.map
  src/libs/elektra/proposal.c
  src/libs/meta/CMakeLists.txt
  src/libs/proposal/CMakeLists.txt
  src/libs/proposal/proposal.c
  src/libs/proposal/symbols.map
  src/plugins/augeas/CMakeLists.txt
  src/plugins/augeas/testmod_augeas.c
  src/plugins/hosts/CMakeLists.txt
  src/plugins/hosts/hosts-set.c
  src/plugins/hosts/keymetaformatting.c
  src/plugins/hosts/keymetaformatting.h
  src/plugins/hosts/testmod_hosts.c
  src/plugins/keytometa/CMakeLists.txt
  src/plugins/list/CMakeLists.txt
  src/plugins/specload/CMakeLists.txt
  tests/ctest/CMakeLists.txt
  tests/ctest/test_meta.c
  tests/ctest/test_operation.c
  tests/ctest/test_proposal.c
Labels: work in progress

#3566 YAML CPP: Fix Use After Free Bug
  .cirrus.yml
  .travis.yml
  doc/news/2020-05-26_0.9.2.md
  doc/news/_preparation_next_release.md
  scripts/cmake/Modules/LibAddBinding.cmake
  scripts/docker/debian/sid/doc.Dockerfile
  scripts/jenkins/Jenkinsfile
  src/plugins/yamlcpp/README.md
  src/plugins/yamlcpp/read.cpp
  tests/kdb/CMakeLists.txt
Labels: bug, build, continuous integration, lang/cpp, ready to merge

#3573 mINI/Simple INI: Change Provided Format From INI to Properties
  doc/news/_preparation_next_release.md
  doc/tutorials/crypto.md
  src/plugins/mini/README.md
  src/plugins/simpleini/README.md
Labels: cleanup, enhancement, lang/c, ready to merge
