Repository ElektraInitiative/libelektra, pull requests merged in 2020-03, with the labels that each got.

#3357 YAML CPP/Directory Value: Require `array` Metadata for Arrays
  doc/news/_preparation_next_release.md
  doc/tutorials/arrays.md
  doc/tutorials/storage-plugins.md
  src/bindings/cpp/include/kdbplugin.hpp
  src/plugins/csvstorage/README.md
  src/plugins/directoryvalue/CMakeLists.txt
  src/plugins/directoryvalue/README.md
  src/plugins/directoryvalue/directoryvalue.cpp
  src/plugins/directoryvalue/directoryvalue.hpp
  src/plugins/directoryvalue/directoryvalue/arrays.hpp
  src/plugins/directoryvalue/directoryvalue/arrays_get.hpp
  src/plugins/directoryvalue/directoryvalue/arrays_set.hpp
  src/plugins/directoryvalue/directoryvalue/empty.hpp
  src/plugins/directoryvalue/directoryvalue/extended_get.hpp
  src/plugins/directoryvalue/directoryvalue/extended_set.hpp
  src/plugins/directoryvalue/directoryvalue/mixed_get.hpp
  src/plugins/directoryvalue/directoryvalue/mixed_set.hpp
  src/plugins/directoryvalue/directoryvalue/simple_get.hpp
  src/plugins/directoryvalue/directoryvalue/simple_set.hpp
  src/plugins/directoryvalue/directoryvalue_delegate.cpp
  src/plugins/directoryvalue/directoryvalue_delegate.hpp
  src/plugins/directoryvalue/log.cpp
  src/plugins/directoryvalue/log.hpp
  src/plugins/directoryvalue/testmod_directoryvalue.cpp
  src/plugins/yajl/README.md
  src/plugins/yamlcpp/README.md
  src/plugins/yamlcpp/read.cpp
  src/plugins/yamlcpp/testmod_yamlcpp.cpp
  src/plugins/yamlcpp/write.cpp
  src/plugins/yamlcpp/yamlcpp.cpp
  src/plugins/yamlcpp/yamlcpp.hpp
  src/plugins/yamlcpp/yamlcpp/flat_block_mapping.h
  src/plugins/yamlcpp/yamlcpp/flat_block_mapping.hpp
  src/plugins/yamlcpp/yamlcpp/flat_flow_mapping.h
  src/plugins/yamlcpp/yamlcpp/flat_flow_mapping.hpp
  src/plugins/yamlcpp/yamlcpp/mapping_with_array_key.h
  src/plugins/yamlcpp/yamlcpp/mapping_with_array_key.hpp
  src/plugins/yamlcpp/yamlcpp/mixed.h
  src/plugins/yamlcpp/yamlcpp/mixed.hpp
  src/plugins/yamlcpp/yamlcpp/nested_block_mapping.h
  src/plugins/yamlcpp/yamlcpp/nested_block_mapping.hpp
  src/plugins/yamlcpp/yamlcpp/nested_mixed_mapping.h
  src/plugins/yamlcpp/yamlcpp/nested_mixed_mapping.hpp
  src/plugins/yamlcpp/yamlcpp/nested_sequences.h
  src/plugins/yamlcpp/yamlcpp/nested_sequences.hpp
  src/plugins/yamlcpp/yamlcpp/simple_sequence.h
  src/plugins/yamlcpp/yamlcpp/simple_sequence.hpp
  tests/shell/check_oclint.sh
Labels: documentation, enhancement, lang/cpp, usability

#3359 Docker: Fix Install of `apiaryio` Gem
  doc/news/_preparation_next_release.md
  scripts/docker/debian/stretch/doc.Dockerfile
Labels: bug, continuous integration, ready to merge

#3358 YAML CPP: Set and Require Boolean Metadata
  doc/news/_preparation_next_release.md
  doc/tutorials/storage-plugins.md
  src/plugins/yamlcpp/README.md
  src/plugins/yamlcpp/read.cpp
  src/plugins/yamlcpp/write.cpp
  src/plugins/yamlcpp/yamlcpp.cpp
Labels: bug, enhancement, lang/cpp, ready to merge

#2827 Elektrad-v2 (written in Go)
  .cirrus.yml
  doc/man/man1/kdb-run-elektrad.1
  doc/man/man1/kdb-run-web.1
  doc/news/_preparation_next_release.md
  scripts/docker/webui/base/Dockerfile
  src/libs/elektra/keyvalue.c
  src/tools/web/CMakeLists.txt
  src/tools/web/README.md
  src/tools/web/build.sh
  src/tools/web/elektrad/.babelrc
  src/tools/web/elektrad/.gitignore
  src/tools/web/elektrad/README.md
  src/tools/web/elektrad/assertions_test.go
  src/tools/web/elektrad/benchmark_test.go
  src/tools/web/elektrad/find_handler.go
  src/tools/web/elektrad/find_handler_test.go
  src/tools/web/elektrad/go.mod
  src/tools/web/elektrad/go.sum
  src/tools/web/elektrad/handlepool.go
  src/tools/web/elektrad/helper_test.go
  src/tools/web/elektrad/kdb.go
  src/tools/web/elektrad/kdb_handler.go
  src/tools/web/elektrad/kdb_handler_test.go
  src/tools/web/elektrad/main.go
  src/tools/web/elektrad/meta_handler.go
  src/tools/web/elektrad/meta_handler_test.go
  src/tools/web/elektrad/middleware.go
  src/tools/web/elektrad/move_handler.go
  src/tools/web/elektrad/move_handler_test.go
  src/tools/web/elektrad/package-lock.json
  src/tools/web/elektrad/package.json
  src/tools/web/elektrad/router.go
  src/tools/web/elektrad/src/app.js
  src/tools/web/elektrad/src/config.js
  src/tools/web/elektrad/src/index.js
  src/tools/web/elektrad/src/log.js
  src/tools/web/elektrad/src/routes/index.js
  src/tools/web/elektrad/src/routes/utils.js
  src/tools/web/elektrad/src/versions.js
  src/tools/web/elektrad/temp-elektra.pc.in
  src/tools/web/elektrad/version_handler.go
  src/tools/web/elektrad/version_handler_test.go
  src/tools/web/run-elektrad.sh
  src/tools/web/test.sh
  src/tools/web/webd/src/connector.js
  src/tools/web/webd/src/index.js
Labels: lang/go

#3362 link checker: whitelist broken links
  doc/news/_preparation_next_release.md
  tests/linkchecker.whitelist
Labels: ready to merge

#3363 Web: Update Man Pages
  .cirrus.yml
  doc/man/man1/kdb-run-elektrad.1
  doc/man/man1/kdb-run-web.1
  doc/news/_preparation_next_release.md
  scripts/docker/cirrus/arch/Dockerfile
  src/tools/web/CMakeLists.txt
  tests/linkchecker.whitelist
Labels: documentation, enhancement, ready to merge

#3368 Jenkins: Add Monthly Build Job
  .travis.yml
  doc/news/_preparation_next_release.md
  scripts/jenkins/Jenkinsfile.monthly
Labels: continuous integration, lang/groovy, ready to merge

#3365 python: test kdbEnsure
  doc/news/_preparation_next_release.md
  src/bindings/swig/common.i
  src/bindings/swig/python/tests/test_kdb.py
Labels: ready to merge
