Repository ElektraInitiative/libelektra, pull requests merged in 2020-04, with the labels that each got.

#3383 Fix macOS builds
  .cirrus.yml
  .travis.yml
  doc/news/_preparation_next_release.md
  lgtm.yml
  scripts/docker/debian/buster/Dockerfile
  scripts/docker/debian/buster/doc.Dockerfile
  scripts/docker/debian/buster/i386.Dockerfile
  scripts/docker/debian/buster/minimal.Dockerfile
  src/tools/kdb/complete.cpp
  tests/kdb/testkdb_allplugins.cpp
  tests/kdb/testkdb_conflict.cpp
  tests/sanitizer.blacklist
Labels: work in progress

#3386 YAML CPP/Yan LR: Limit Scope of Logging Function
  .cirrus.yml
  doc/news/_preparation_next_release.md
  scripts/docker/cirrus/fedora/Dockerfile
  src/plugins/directoryvalue/CMakeLists.txt
  src/plugins/directoryvalue/log.cpp
  src/plugins/directoryvalue/log.hpp
  src/plugins/yamlcpp/CMakeLists.txt
  src/plugins/yamlcpp/log.cpp
  src/plugins/yamlcpp/log.hpp
  src/plugins/yamlcpp/write.cpp
Labels: bug, build, continuous integration, lang/cpp, ready to merge

#3387 cache: XDG compatibility
  doc/news/_preparation_next_release.md
  src/plugins/cache/README.md
  src/plugins/cache/cache.c
Labels: ready to merge

#3394 cirrus: enable fcrypt on fedora again #3283
  .cirrus.yml
  doc/news/_preparation_next_release.md
Labels: ready to merge

#3395 3391 crypto cleanup
  .cirrus.yml
  .travis.yml
  doc/news/_preparation_next_release.md
  doc/todo/TESTING
  doc/tutorials/crypto.md
  scripts/cmake/ElektraCache.cmake
  scripts/cmake/Modules/FindLibBotan.cmake
  scripts/dev/configure-debian-musl
  scripts/docker/cirrus/fedora/Dockerfile
  scripts/docker/debian/buster/Dockerfile
  scripts/docker/debian/sid/Dockerfile
  scripts/docker/debian/stretch/Dockerfile
  scripts/docker/fedora/31/Dockerfile
  scripts/docker/jenkinsnode/Dockerfile
  scripts/docker/ubuntu/bionic/Dockerfile
  scripts/jenkins/Jenkinsfile
  src/libs/tools/benchmarks/benchmark_crypto_comparison.cpp
  src/plugins/crypto/CMakeLists.txt
  src/plugins/crypto/README.md
  src/plugins/crypto/botan_operations.cpp
  src/plugins/crypto/botan_operations.h
  src/plugins/crypto/compile_botan.cpp
  src/plugins/crypto/crypto.c
  src/plugins/crypto/crypto.h
  src/plugins/crypto/gcrypt_operations.h
  src/plugins/crypto/openssl_operations.c
  src/plugins/crypto/openssl_operations.h
  src/plugins/crypto/testmod_crypto.c
  src/plugins/crypto/testmod_crypto_botan.c
  src/plugins/crypto/testmod_crypto_gcrypt.c
  src/plugins/crypto/testmod_crypto_openssl.c
  tests/sanitizer.blacklist
  tests/shell/shell_recorder/tutorial_wrapper/CMakeLists.txt
  tests/valgrind.suppression
Labels: cleanup

#3400 tools: webd - remember elektrad sessions
  doc/news/_preparation_next_release.md
  src/tools/webd/package-lock.json
  src/tools/webd/package.json
  src/tools/webd/src/app.js
  src/tools/webd/src/connector.js
  src/tools/webd/src/routes/instances.js
  src/tools/webd/src/routes/utils.js
  src/tools/webd/src/serveClient.js
  src/tools/webui/package-lock.json
Labels: work in progress

#3409 3246 fix kdb exec path
  doc/news/_preparation_next_release.md
  scripts/docker/debian/sid/Dockerfile
  scripts/jenkins/Jenkinsfile
  tests/shell/include_common.sh.in
  tests/shell/shell_recorder/tutorial_wrapper/CMakeLists.txt
Labels: help wanted

#3411 swig: exclude incompatible swig, ruby, python combinations
  .cirrus.yml
  doc/news/_preparation_next_release.md
  doc/todo/TESTING
  scripts/cmake/Modules/LibAddMacros.cmake
  scripts/jenkins/Jenkinsfile
  src/bindings/swig/CMakeLists.txt
  src/bindings/swig/python/CMakeLists.txt
  src/bindings/swig/ruby/CMakeLists.txt
  src/plugins/ruby/CMakeLists.txt
Labels: ready to merge

#3413 cirrus: install ruby 2.6
  .cirrus.yml
  doc/news/_preparation_next_release.md
  scripts/jenkins/Jenkinsfile
Labels: ready to merge

#3417 Jenkins: disable crypto on debian-unstable-full
  doc/news/_preparation_next_release.md
  scripts/jenkins/Jenkinsfile
Labels: ready to merge
