Repository ElektraInitiative/libelektra, pull requests merged in 2021-04, with the labels that each got.

#3639 CI: update macOS images and various fixes
  .cirrus.yml
  .github/workflows/macOS_gcc10.yml
  doc/news/_preparation_next_release.md
  scripts/dev/run_nocheckshell.in
Labels: ready to merge

#3748 webd: update y18n
  doc/news/_preparation_next_release.md
  src/tools/webd/package-lock.json
Labels: dependencies, ready to merge

#3745 Cleanup
  doc/news/_preparation_next_release.md
  src/bindings/jna/README.md
Labels: ready to merge

#3751 swig/python+lua: add support for ks.remove(key)
  doc/news/_preparation_next_release.md
  doc/tutorials/python-kdb.md
  src/bindings/swig/lua/kdb.i
  src/bindings/swig/lua/tests/test_keyset.lua
  src/bindings/swig/python/kdb.i
  src/bindings/swig/python/tests/test_keyset.py
Labels: lang/lua, lang/python

#3755 keep rpath for jni plugin
  doc/news/_preparation_next_release.md
  scripts/cmake/Modules/LibAddPlugin.cmake
  src/plugins/jni/CMakeLists.txt
Labels: ready to merge

#3763 Fix ARM builds
  doc/news/_preparation_next_release.md
  src/libs/notification/notification.c
  src/plugins/internalnotification/internalnotification.c
  src/plugins/internalnotification/testmod_internalnotification.c
Labels: ready to merge

#3769 doc: add "syncing forks" info to doc/GIT.md
  doc/COMPILE.md
  doc/GIT.md
  doc/news/_preparation_next_release.md
  scripts/docker/legacy/README.md
  scripts/sed
Labels: ready to merge

#3773 [CM H2] Remove kdb set functionality that creates a null key
  doc/help/kdb-set.md
  doc/man/man1/kdb-set.1
  doc/news/_preparation_next_release.md
  doc/tutorials/arrays.md
  doc/tutorials/storage-plugins.md
  src/plugins/rename/README.md
  src/plugins/shell/README.md
  src/plugins/yamlcpp/README.md
  src/tools/kdb/set.cpp
  src/tools/kdb/set.hpp
  tests/shell/check_merge.sh
  tests/shell/check_spec.sh
  tests/shell/shell_recorder/replay_tests/ls.epf
  tests/shell/shell_recorder/replay_tests/ls.esr
Labels: ready to merge

#3774 [CM H2] disable tests when BUILD_TESTING is disabled
  doc/news/_preparation_next_release.md
  scripts/jenkins/Jenkinsfile
  src/bindings/io/doc/CMakeLists.txt
  src/bindings/io/ev/CMakeLists.txt
  src/bindings/io/glib/CMakeLists.txt
  src/bindings/io/uv/CMakeLists.txt
  src/bindings/jna/CMakeLists.txt
  src/bindings/rust/CMakeLists.txt
  src/bindings/swig/lua/CMakeLists.txt
  src/bindings/swig/python/CMakeLists.txt
Labels: ready to merge

#3786 Website cleanup
  doc/man/man1/kdb-run-website.1
  doc/news/_preparation_next_release.md
  scripts/docker/website/Dockerfile
  src/tools/website/Gruntfile.js
  src/tools/website/README.md
  src/tools/website/application-config.json.tpl
  src/tools/website/package-lock.json
  src/tools/website/package.json
  src/tools/website/public/assets/translations/en.json
  src/tools/website/public/pages/main/template.html
  src/tools/website/public/pages/main/website/listfiles.html
  src/tools/website/public/pages/main/website/news.html
  src/tools/website/public/templates/breadcrumbs.html
  src/tools/website/resources/assets/html/index.html.in
  src/tools/website/resources/assets/js/config/auth.js
  src/tools/website/resources/assets/js/config/http.js
  src/tools/website/resources/assets/js/config/index.js.in
  src/tools/website/resources/assets/js/config/marked.js
  src/tools/website/resources/assets/js/controllers/main/auth/AuthLoginController.js
  src/tools/website/resources/assets/js/controllers/main/auth/AuthRegistrationController.js
  src/tools/website/resources/assets/js/controllers/main/auth/index.js
  src/tools/website/resources/assets/js/controllers/main/entries/EntryCreateController.js
  src/tools/website/resources/assets/js/controllers/main/entries/EntryDeleteConfirmationController.js
  src/tools/website/resources/assets/js/controllers/main/entries/EntryDetailsController.js
  src/tools/website/resources/assets/js/controllers/main/entries/EntryEditController.js
  src/tools/website/resources/assets/js/controllers/main/entries/EntrySearchController.js
  src/tools/website/resources/assets/js/controllers/main/entries/index.js
  src/tools/website/resources/assets/js/controllers/main/index.js
  src/tools/website/resources/assets/js/controllers/main/users/UserDetailsController.js
  src/tools/website/resources/assets/js/controllers/main/users/UserSearchController.js
  src/tools/website/resources/assets/js/controllers/main/users/index.js
  src/tools/website/resources/assets/js/controllers/main/website/WebsiteConversionController.js
  src/tools/website/resources/assets/js/controllers/main/website/index.js
  src/tools/website/resources/assets/js/directives/index.js
  src/tools/website/resources/assets/js/directives/permission/HasRankDirective.js
  src/tools/website/resources/assets/js/directives/permission/HasRankOrIsOwnerDirective.js
  src/tools/website/resources/assets/js/directives/permission/index.js
  src/tools/website/resources/assets/js/run/index.js
  src/tools/website/resources/assets/js/run/states.js
  src/tools/website/resources/assets/js/services/ConversionService.js
  src/tools/website/resources/assets/js/services/EntryService.js
  src/tools/website/resources/assets/js/services/UserService.js
  src/tools/website/resources/assets/js/services/index.js
  src/tools/website/resources/grunt-tasks/grunt-create-website-sitemap.js
Labels: lang/web

#3790 Fixing small issues
  LICENSE.md
  doc/news/2021-02-01_0.9.4.md
  doc/news/_preparation_next_release.md
  doc/todo/RELEASE
  doc/todo/RELEASE.md
  src/bindings/rust/elektra/src/key.rs
  src/libs/elektra/keyset.c
  src/libs/version_gen.awk
  src/plugins/lua/CMakeLists.txt
  src/tools/kdb/gen/templates/collect.sh
  src/tools/kdb/gen/templates/highlevel.c.mustache
  src/tools/kdb/gen/templates/highlevel.commands.h.mustache
  src/tools/kdb/gen/templates/highlevel.h.mustache
  src/tools/kdb/gen/templates/highlevel/LICENSE.txt
  src/tools/kdb/specmount.cpp
  tests/shell/gen/highlevel/commands.expected.c
  tests/shell/gen/highlevel/commands.expected.commands.h
  tests/shell/gen/highlevel/commands.expected.h
  tests/shell/gen/highlevel/empty.expected.c
  tests/shell/gen/highlevel/empty.expected.h
  tests/shell/gen/highlevel/enum.expected.c
  tests/shell/gen/highlevel/enum.expected.h
  tests/shell/gen/highlevel/externalspec.expected.c
  tests/shell/gen/highlevel/externalspec.expected.h
  tests/shell/gen/highlevel/externalwithdefaults.expected.c
  tests/shell/gen/highlevel/externalwithdefaults.expected.h
  tests/shell/gen/highlevel/nosetter.expected.c
  tests/shell/gen/highlevel/nosetter.expected.h
  tests/shell/gen/highlevel/notype.expected.c
  tests/shell/gen/highlevel/notype.expected.h
  tests/shell/gen/highlevel/simple.expected.c
  tests/shell/gen/highlevel/simple.expected.h
  tests/shell/gen/highlevel/struct.expected.c
  tests/shell/gen/highlevel/struct.expected.h
Labels: ready to merge

#3791 elektraMemDup: use `void *`
  doc/news/_preparation_next_release.md
  src/include/kdbhelper.h
  src/libs/elektra/internal.c
Labels: ready to merge

#3796 ni: fix Clang 12 warnings
  .cirrus.yml
  doc/news/_preparation_next_release.md
  src/plugins/ni/testmod_ni.c
Labels: build, continuous integration, urgent

#3779 Improve documentation of keytest.c with suggestions from API review
  doc/news/_preparation_next_release.md
  src/libs/elektra/keytest.c
Labels: documentation, ready to merge

#3780 Improve documentation of keyvalue.c with suggestions from API review
  doc/news/_preparation_next_release.md
  src/libs/elektra/keyvalue.c
Labels: documentation, ready to merge

#3782 Improve documentation of kdb.c with suggestions from API review
  doc/api_review/core/kdbOpen.md
  doc/news/_preparation_next_release.md
  src/libs/elektra/kdb.c
Labels: documentation, ready to merge

#3789 elektrad: update
  doc/news/_preparation_next_release.md
  src/tools/elektrad/CMakeLists.txt
  src/tools/elektrad/benchmark_test.go
  src/tools/elektrad/find_handler_test.go
  src/tools/elektrad/go.mod
  src/tools/elektrad/go.sum
  src/tools/elektrad/handlepool.go
  src/tools/elektrad/helper_test.go
  src/tools/elektrad/kdb.go
  src/tools/elektrad/kdb_handler.go
  src/tools/elektrad/kdb_handler_test.go
  src/tools/elektrad/meta_handler.go
  src/tools/elektrad/meta_handler_test.go
  src/tools/elektrad/move_handler.go
  src/tools/elektrad/move_handler_test.go
  src/tools/elektrad/router.go
Labels: ready to merge

#3778 Improve documentation of keyset.c with suggestions from API review
  doc/news/_preparation_next_release.md
  src/libs/elektra/keyset.c
Labels: documentation, ready to merge

#3793 Improve documentation of key.c with suggestions from API review
  doc/news/_preparation_next_release.md
  src/libs/elektra/key.c
Labels: documentation, ready to merge

#3803 doc: fix #3799
  doc/news/_preparation_next_release.md
  src/libs/elektra/kdb.c
Labels: documentation

#3805 doc: fix mount example
  doc/news/_preparation_next_release.md
  doc/tutorials/mount.md
Labels: documentation

#3807 Clang 12
  .cirrus.yml
  doc/news/_preparation_next_release.md
  src/bindings/swig/CMakeLists.txt
  tests/sanitizer.blacklist
Labels: ready to merge

#3809 GnuPG: use 2.2.x
  .cirrus.yml
  .github/workflows/macOS_gcc10.yml
  doc/news/_preparation_next_release.md
  scripts/jenkins/Jenkinsfile
  tests/shell/shell_recorder/tutorial_wrapper/CMakeLists.txt
Labels: ready to merge

#3761 actions: enable jni plugin
  .cirrus.yml
  .github/workflows/macOS_gcc10.yml
  doc/news/_preparation_next_release.md
  src/plugins/jni/CMakeLists.txt
Labels: ready to merge
