Repository ElektraInitiative/libelektra, pull requests merged in 2021-08, with the labels that each got.

#3971 #3790 hid errorKey from KDB and refactored Key::createNameless
  doc/news/_preparation_next_release.md
  doc/tutorials/java-kdb.md
  src/bindings/jna/libelektra/src/main/java/org/libelektra/Elektra.java
  src/bindings/jna/libelektra/src/main/java/org/libelektra/KDB.java
  src/bindings/jna/libelektra/src/main/java/org/libelektra/Key.java
  src/bindings/jna/libelektra/src/main/java/org/libelektra/KeySet.java
  src/bindings/jna/libelektra/src/main/java/org/libelektra/KeySetIterator.java
  src/bindings/jna/libelektra/src/main/java/org/libelektra/PluginLoader.java
  src/bindings/jna/libelektra/src/test/java/org/libelektra/GOptsTest.java
  src/bindings/jna/libelektra/src/test/java/org/libelektra/KDBTest.java
  src/bindings/jna/libelektra/src/test/java/org/libelektra/KeySetTest.java
  src/bindings/jna/libelektra/src/test/java/org/libelektra/KeyTest.java
  src/libs/elektra/kdb.c
Labels: lang/java

#3993 doc: fix broken links breaking build
  doc/news/_preparation_next_release.md
  doc/tutorials/profiling.md
  scripts/docker/fedora/33/release.Dockerfile
  scripts/docker/fedora/34/release.Dockerfile
  tests/linkchecker.whitelist
Labels: documentation, important, needs review

#3997 Update tutorial "High-level API (with code-generation)"
  doc/news/_preparation_next_release.md
  doc/tutorials/highlevel.md
Labels: ready to merge

#3961 doc: add pre/postconditions and invarians to module keymeta
  doc/api_review/core/keyCopyAllMeta.md
  doc/api_review/core/keyCopyMeta.md
  doc/api_review/core/keyCurrentMeta.md
  doc/api_review/core/keyGetMeta.md
  doc/api_review/core/keyMeta.md
  doc/api_review/core/keyNextMeta.md
  doc/api_review/core/keyRewindMeta.md
  doc/api_review/core/keySetMeta.md
  doc/news/_preparation_next_release.md
  src/libs/elektra/keymeta.c
Labels: ready to merge

#3962 doc: add pre/postconditions and invarians to module key
  doc/api_review/core/keyClear.md
  doc/api_review/core/keyDecRef.md
  doc/api_review/core/keyDel.md
  doc/api_review/core/keyIncRef.md
  doc/api_review/core/keyIsLocked.md
  doc/api_review/core/keyLock.md
  doc/api_review/core/keyNew.md
  doc/news/_preparation_next_release.md
  src/libs/elektra/key.c
Labels: ready to merge

#3964 doc: add pre/postconditions and invariants to module keytest
  doc/api_review/core/keyCmp.md
  doc/api_review/core/keyIsBelow.md
  doc/api_review/core/keyIsBinary.md
  doc/api_review/core/keyIsDirectlyBelow.md
  doc/api_review/core/keyIsString.md
  doc/api_review/core/keyNeedSync.md
  doc/news/_preparation_next_release.md
  src/libs/elektra/keyset.c
  src/libs/elektra/keytest.c
Labels: ready to merge

#4010 Debian Bullseye
  doc/news/_preparation_next_release.md
  scripts/docker/debian/bullseye/Dockerfile
  scripts/docker/debian/bullseye/i386.Dockerfile
  scripts/docker/debian/bullseye/minimal.Dockerfile
  scripts/docker/debian/buster/Dockerfile
  scripts/docker/debian/sid/Dockerfile
  scripts/docker/debian/stretch/Dockerfile
  scripts/docker/fedora/31/Dockerfile
  scripts/docker/fedora/32/Dockerfile
  scripts/docker/fedora/33/Dockerfile
  scripts/docker/fedora/34/Dockerfile
  scripts/docker/jenkinsnode/Dockerfile
  scripts/docker/ubuntu/bionic/Dockerfile
  scripts/docker/ubuntu/focal/Dockerfile
  scripts/docker/website/Dockerfile
  scripts/jenkins/Jenkinsfile
  src/plugins/crypto/gcrypt_operations.c
Labels: ready to merge

#4015 Include deeply nested keys in help message
  doc/news/_preparation_next_release.md
  src/libs/opts/opts.c
  tests/ctest/test_opts.c
Labels: ready to merge
