Repository ElektraInitiative/libelektra, pull requests merged in 2021-09, with the labels that each got.

#3996 Packaging for fuse tool
  doc/news/_preparation_next_release.md
  scripts/cmake/ElektraPackaging.cmake
  scripts/cmake/Modules/PackagingDebian.cmake
  scripts/cmake/Modules/PackagingFedora.cmake
  scripts/docker/alpine/3.14/Dockerfile
  scripts/docker/arch/Dockerfile
  scripts/docker/cirrus/arch/Dockerfile
  scripts/docker/debian/bullseye/Dockerfile
  scripts/docker/debian/bullseye/i386.Dockerfile
  scripts/docker/debian/buster/Dockerfile
  scripts/docker/debian/buster/i386.Dockerfile
  scripts/docker/debian/sid/Dockerfile
  scripts/docker/debian/stretch/Dockerfile
  scripts/docker/debian/stretch/i386.Dockerfile
  scripts/docker/fedora/31/Dockerfile
  scripts/docker/fedora/32/Dockerfile
  scripts/docker/fedora/33/Dockerfile
  scripts/docker/fedora/34/Dockerfile
  scripts/docker/jenkinsnode/Dockerfile
  scripts/docker/legacy/Dockerfile
  scripts/docker/ubuntu/bionic/Dockerfile
  scripts/docker/ubuntu/disco/Dockerfile
  scripts/docker/ubuntu/focal/Dockerfile
  scripts/docker/ubuntu/xenial/Dockerfile
  src/tools/README.md
  src/tools/fuse/CMakeLists.txt
  src/tools/fuse/README.md
  src/tools/fuse/fuse.in
  src/tools/fuse/setup.py
Labels: ready to merge, needs review

#4025 FUSE: fix bug preventing binary writes
  doc/news/_preparation_next_release.md
  src/tools/fuse/src/elektra_fuse/elektra_util.py
Labels: ready to merge

#4018 Restyled updates
  .cirrus.yml
  .github/workflows/macOS.yml
  .restyled.yaml
  doc/CODING.md
  doc/news/_preparation_next_release.md
  scripts/dev/reformat-javascript
  scripts/dev/reformat-markdown
  scripts/docker/debian/bullseye/Dockerfile
  scripts/docker/debian/buster/Dockerfile
  scripts/docker/debian/sid/Dockerfile
  scripts/docker/debian/stretch/Dockerfile
  src/tools/website/Gruntfile.js
  src/tools/website/public/vendor/asciinema/asciinema-player.js
  src/tools/website/resources/assets/js/config/marked.js
  src/tools/website/resources/grunt-tasks/grunt-copy-website-content.js
  src/tools/webui/src/components/TreeItem/dialogs/AddDialog.jsx
  src/tools/webui/src/components/TreeItem/dialogs/EditDialog.jsx
  src/tools/webui/src/components/TreeItem/dialogs/SettingsDialog.jsx
  src/tools/webui/src/components/TreeItem/index.js
  tests/linkchecker.whitelist
Labels: ready to merge

#3967 Build OpenWrt packages in main pipeline
  doc/news/_preparation_next_release.md
  scripts/docker/openwrt/sdk/Dockerfile
  scripts/jenkins/Jenkinsfile
  scripts/release/prepare-openwrt-makefile.sh
Labels: ready to merge

#4033 jenkinsfile: move basic checks to dedicated stage
  doc/news/_preparation_next_release.md
  scripts/jenkins/Jenkinsfile
Labels: ready to merge

#4023 opts: Improve naming, documentation, etc.
  doc/news/_preparation_next_release.md
  src/libs/opts/opts.c
Labels: ready to merge

#3853 Add additional test cases for module keytest
  doc/api_review/core/keyCmp.md
  doc/api_review/core/keyIsBelow.md
  doc/api_review/core/keyIsBinary.md
  doc/api_review/core/keyIsDirectlyBelow.md
  doc/api_review/core/keyIsString.md
  doc/api_review/core/keyNeedSync.md
  doc/news/_preparation_next_release.md
  tests/abi/testabi_key.c
  tests/abi/testabi_rel.c
  tests/ctest/test_key.c
Labels: ready to merge

#4046 Add files generated by CMake and docker tutorial to .gitignore
  .gitignore
  doc/news/_preparation_next_release.md
Labels: ready to merge

#3956 Abi tests
  doc/news/_preparation_next_release.md
  scripts/docker/debian/bullseye/abi.Dockerfile
  scripts/docker/fedora/34/abi.Dockerfile
  scripts/jenkins/Jenkinsfile.release
Labels: ready to merge

#3965 doc: add pre/postconditions and invariants to module keyvalue
  doc/api_review/core/keyGetBinary.md
  doc/api_review/core/keyGetString.md
  doc/api_review/core/keyGetValueSize.md
  doc/api_review/core/keySetBinary.md
  doc/api_review/core/keySetString.md
  doc/api_review/core/keyString.md
  doc/api_review/core/keyValue.md
  doc/news/_preparation_next_release.md
  src/libs/elektra/keyvalue.c
Labels: ready to merge

#4045 Fixes for gopts and spec
  doc/news/_preparation_next_release.md
  examples/codegen/econf/spec.ini
  examples/codegen/tree/spec.ini
  src/libs/elektra/kdb.c
  src/plugins/type/README.md
  src/plugins/type/testmod_type.c
  src/plugins/type/types.c
  tests/shell/gen/highlevel/commands.check.sh
  tests/shell/gen/highlevel/commands.data.ini
  tests/shell/gen/highlevel/commands.expected.c
  tests/shell/gen/highlevel/commands.expected.h
  tests/shell/gen/highlevel/empty.check.sh
  tests/shell/gen/highlevel/enum.check.sh
  tests/shell/gen/highlevel/externalspec.check.sh
  tests/shell/gen/highlevel/externalwithdefaults.check.sh
  tests/shell/gen/highlevel/nosetter.check.sh
  tests/shell/gen/highlevel/simple.check.sh
  tests/shell/gen/highlevel/struct.check.sh
  tests/shell/gen/highlevel/struct.data.ini
  tests/shell/gen/highlevel/struct.expected.c
Labels: ready to merge

#4058 Add sanity-checks for keys to "kdb spec-mount" command
  doc/news/_preparation_next_release.md
  src/libs/tools/include/specreader.hpp
  src/libs/tools/src/specreader.cpp
  tests/shell/gen/highlevel/nodefault.data.ini
Labels: ready to merge

#4055 Use `type` metakey as fallback in range plugin
  doc/METADATA.ini
  doc/news/_preparation_next_release.md
  src/plugins/range/README.md
  src/plugins/range/range.c
Labels: ready to merge

#4037 Upgraded Java binding gradle wrapper to 7.2 to fit CI docker images
  doc/news/_preparation_next_release.md
  scripts/docker/cirrus/fedora/Dockerfile
  src/bindings/jna/README.md
  src/bindings/jna/gradle/wrapper/gradle-wrapper.properties
  src/bindings/jna/gradlew
Labels: ready to merge, lang/java

#4067 CI fixes
  doc/news/_preparation_next_release.md
  doc/todo/TESTING
  src/bindings/io/glib/CMakeLists.txt
  src/libs/highlevel/CMakeLists.txt
Labels: urgent

#3851 Add additional test cases for module keymeta
  doc/api_review/core/keyCopyAllMeta.md
  doc/api_review/core/keyCurrentMeta.md
  doc/api_review/core/keyGetMeta.md
  doc/api_review/core/keyMeta.md
  doc/api_review/core/keyNextMeta.md
  doc/api_review/core/keyRewindMeta.md
  doc/api_review/core/keySetMeta.md
  doc/news/_preparation_next_release.md
  src/libs/elektra/keymeta.c
  tests/abi/testabi_meta.c
Labels: ready to merge

#4036 Docker images and packaging for CentOS and openSUSE
  doc/INSTALL.md
  doc/news/_preparation_next_release.md
  scripts/cmake/ElektraPackaging.cmake
  scripts/cmake/Modules/PackagingFedora.cmake
  scripts/docker/centos/stream8/Dockerfile
  scripts/docker/opensuse/15.3/Dockerfile
  scripts/docker/opensuse/15.3/package.Dockerfile
  scripts/docker/opensuse/15.3/release.Dockerfile
  scripts/jenkins/Jenkinsfile
  scripts/jenkins/Jenkinsfile.release
  scripts/packaging/package.sh
  scripts/release/release.sh
Labels: ready to merge

#4047 highlevel: detect if spec properly mounted and unmodified
  doc/THIRD-PARTY-LICENSES
  doc/help/elektra-highlevel-gen.md
  doc/help/kdb-gen-highlevel.md
  doc/man/man1/kdb-gen-highlevel.1
  doc/man/man7/elektra-highlevel-gen.7
  doc/news/_preparation_next_release.md
  src/include/kdbease.h
  src/include/kdbprivate.h
  src/libs/ease/CMakeLists.txt
  src/libs/ease/hash.c
  src/libs/ease/sha-256.c
  src/libs/ease/sha-256.h
  src/libs/ease/symbols.map
  src/libs/highlevel/elektra.c
  src/libs/highlevel/elektra_error.c
  src/tools/kdb/gen.cpp
  src/tools/kdb/gen/highlevel/highlevel.cpp
  src/tools/kdb/gen/highlevel/highlevel.hpp
  tests/ctest/CMakeLists.txt
  tests/ctest/test_hash.c
  tests/ctest/test_sha-256.c
  tests/shell/gen/highlevel/commands.expected.c
  tests/shell/gen/highlevel/empty.expected.c
  tests/shell/gen/highlevel/enum.expected.c
  tests/shell/gen/highlevel/externalspec.expected.c
  tests/shell/gen/highlevel/externalwithdefaults.expected.c
  tests/shell/gen/highlevel/nosetter.expected.c
  tests/shell/gen/highlevel/notype.expected.c
  tests/shell/gen/highlevel/simple.expected.c
  tests/shell/gen/highlevel/struct.expected.c
Labels: ready to merge

#4063 Treat validation problems as warnings in HL API
  doc/news/_preparation_next_release.md
  src/include/kdbprivate.h
  src/libs/elektra/kdb.c
  src/libs/highlevel/elektra.c
  src/libs/highlevel/elektra_error.c
  src/plugins/range/range.c
Labels: ready to merge

#4078 Fix extraction of first warning in HL API.
  doc/news/_preparation_next_release.md
  src/libs/highlevel/elektra.c
Labels: ready to merge
