Repository ElektraInitiative/libelektra, pull requests merged in 2021-12, with the labels that each got.

#4163 [FLOSS T1] Fix missing array meta-key in the csvstorage plugin
  doc/news/_preparation_next_release.md
  src/plugins/csvstorage/README.md
  src/plugins/csvstorage/csvstorage.c
  src/plugins/csvstorage/csvstorage/metakey.csv
  src/plugins/csvstorage/testmod_csvstorage.c
Labels: floss2021W

#3919 doc: add decision docs for decision meeting 15.07.2021
  doc/decisions/README.md
  doc/decisions/error_handling.md
  doc/decisions/functions_with_buffers.md
  doc/decisions/iterators.md
  doc/decisions/key_string_return_value.md
  doc/decisions/reference_counting.md
  doc/decisions/remove_elektra_malloc.md
  doc/news/_preparation_next_release.md
Labels: help wanted, work in progress, documentation

#4146 [FLOSS H2] Fixed some simple typos in the namespaces tutorial.
  doc/news/_preparation_next_release.md
  doc/tutorials/namespaces.md
Labels: ready to merge

#4171 [FLOSS H3] File name checker for CI
  .cirrus.yml
  doc/news/_preparation_next_release.md
  scripts/dev/filename-checker
  scripts/jenkins/Jenkinsfile
  tests/filename.whitelist
Labels: ready to merge

#4174 [FLOSS H3] Fix #3981
  doc/news/_preparation_next_release.md
  src/libs/elektra/keymeta.c
  tests/abi/testabi_meta.c
Labels: ready to merge

#4180 [FLOSS H3] fix hashing collisions in specification token
  doc/news/_preparation_next_release.md
  src/libs/ease/hash.c
  tests/ctest/test_hash.c
  tests/shell/gen/highlevel/commands.expected.c
  tests/shell/gen/highlevel/empty.expected.c
  tests/shell/gen/highlevel/enum.expected.c
  tests/shell/gen/highlevel/externalspec.expected.c
  tests/shell/gen/highlevel/externalwithdefaults.expected.c
  tests/shell/gen/highlevel/nosetter.expected.c
  tests/shell/gen/highlevel/notype.expected.c
  tests/shell/gen/highlevel/simple.expected.c
  tests/shell/gen/highlevel/struct.expected.c
Labels: bug, ready to merge, floss2021W, 7p

#4193 [FLOSS H3] Remove the deprecated flags KEY_NAME and KEY_COMMENT
  doc/news/_preparation_next_release.md
  doc/tutorials/python-kdb.md
  examples/functional.c
  examples/iterate.c
  examples/kdbget.c
  examples/kdbget_error.c
  examples/keyNew.c
  examples/keyNewExample.c
  examples/set_key.c
  src/bindings/cpp/tests/testcpp_key.cpp
  src/bindings/glib/gelektra-key.h
  src/bindings/glib/tests/testglib_key.c
  src/bindings/jna/libelektra/src/main/java/org/libelektra/Key.java
  src/bindings/swig/lua/examples/example_key.lua
  src/bindings/swig/python/examples/example_key.py
  src/bindings/swig/ruby/tests/testruby_key.rb
  src/include/kdb.h.in
  src/include/kdbease.h
  src/libs/elektra/kdbenum.c
  src/libs/elektra/key.c
  src/libs/elektra/keytest.c
  src/libs/meta/meta.c
  src/libs/tools/src/backend.cpp
  src/libs/tools/src/plugins.cpp
  src/plugins/augeas/contract.h
  src/plugins/dump/dump/v2/demo.dump
  src/plugins/dump/dump/v2/fullnames.dump
  src/plugins/dump/testdata.h
  src/plugins/fstab/testmod_fstab.c
  src/plugins/iconv/data_latin1.c
  src/plugins/iconv/data_utf8.c
  src/plugins/iconv/iconv.c
  src/plugins/keytometa/README.md
  src/plugins/specload/specload.c
  src/plugins/validation/lookupre.c
  src/plugins/validation/testmod_validation.c
  src/plugins/xmltool/stream.c
  tests/abi/testabi_key.c
  tests/abi/testabi_ks.c
  tests/ctest/test_key.c
  tests/ctest/test_meta.c
  tests/data/data_allns.c
  tests/data/data_dbelow.c
  tests/data/data_filesys.c
  tests/data/data_hosts.c
  tests/data/data_key.c
  tests/data/data_keyset.c
  tests/data/data_ns.c
  tests/data/data_one.c
  tests/data/data_others.c
Labels: ready to merge, lang/c, floss2021W, 7p

#4195 [FLOSS H3] Fix some errors in sed-script & spelling errors in documentation
  doc/API.md
  doc/BIGPICTURE.md
  doc/decisions/array.md
  doc/decisions/base_name.md
  doc/decisions/error_handling.md
  doc/dev/algorithm.md
  doc/dev/data-structures.md
  doc/dev/plugins-framework.md
  doc/help/elektra-bootstrapping.md
  doc/help/kdb-meta-get.md
  doc/man/man1/kdb-meta-get.1
  doc/man/man7/elektra-bootstrapping.7
  doc/markdownlinkconverter/README.md
  doc/news/_preparation_next_release.md
  doc/todo/NEWS.md
  doc/tutorials/application-integration.md
  doc/tutorials/mount.md
  doc/tutorials/plugins.md
  doc/tutorials/validation.md
  scripts/sed
  src/plugins/fcrypt/README.md
  src/plugins/file/README.md
  src/plugins/ni/README.md
Labels: ready to merge, floss2021W

#4191 [FLOSS T2] Add a new Shell Recorder test to doc/tutorials/merge.md
  doc/news/_preparation_next_release.md
  doc/tutorials/merge.md
  tests/shell/shell_recorder/tutorial_wrapper/CMakeLists.txt
Labels: ready to merge, lang/markdown, floss2021W

#4188 [FLOSS T2] docs: added verification to the "Arrays" tutorial
  doc/news/_preparation_next_release.md
  doc/tutorials/arrays.md
Labels: ready to merge

#4175 [FLOSS H3] Replace type=int in ini files
  doc/CONTRACT.ini
  doc/news/_preparation_next_release.md
  examples/spec/cassandra.ini
Labels: ready to merge

#4177 [T2 FLOSS] Improvements to the api doc
  doc/news/_preparation_next_release.md
  src/libs/loader/doc.c
  src/libs/meta/meta.c
Labels: ready to merge
