Repository ElektraInitiative/libelektra, pull requests merged in 2021-01, with the labels that each got.

#3617 Yan LR & OCLint Updates
  .cirrus.yml
  .github/workflows/macOS_gcc10.yml
  .travis.yml
  doc/news/_preparation_next_release.md
  scripts/cmake/Modules/FindANTLR4CPP.cmake
  scripts/kdb/mount-list-all-files
  src/bindings/swig/ruby/CMakeLists.txt
  src/plugins/ccode/testmod_ccode.cpp
  src/plugins/cpptemplate/testmod_cpptemplate.cpp
  src/plugins/directoryvalue/testmod_directoryvalue.cpp
  src/plugins/ruby/CMakeLists.txt
  src/plugins/yamlcpp/testmod_yamlcpp.cpp
  src/plugins/yanlr/CMakeLists.txt
  src/plugins/yanlr/error_listener.hpp
  src/plugins/yanlr/testmod_yanlr.cpp
  src/plugins/yanlr/yaml_lexer.cpp
  src/plugins/yanlr/yaml_lexer.hpp
  src/plugins/yanlr/yanlr.cpp
  src/plugins/zeromqrecv/testmod_zeromqrecv.c
  tests/shell/check_oclint.sh
Labels: build, continuous integration, lang/cmake, lang/cpp, work in progress

#3589 qtgui: update for keyname overhaul
  doc/news/_preparation_next_release.md
  src/bindings/cpp/include/key.hpp
  src/bindings/cpp/tests/testcpp_iter_name.cpp
  src/tools/qt-gui/qml/EditKeyWindow.qml
  src/tools/qt-gui/qml/KeyWindow.qml
  src/tools/qt-gui/qml/NewKeyWindow.qml
  src/tools/qt-gui/qml/TreeView.qml
  src/tools/qt-gui/qml/main.qml
  src/tools/qt-gui/src/confignode.cpp
  src/tools/qt-gui/src/confignode.hpp
  src/tools/qt-gui/src/guibackend.cpp
  src/tools/qt-gui/src/guisettings.cpp
  src/tools/qt-gui/src/newkeycommand.cpp
  src/tools/qt-gui/src/treeviewmodel.cpp
  src/tools/qt-gui/src/treeviewmodel.hpp
Labels: ready to merge

#3605 Fix key set allocation hint
  doc/news/_preparation_next_release.md
  src/bindings/jna/libelektra4j/src/main/java/org/libelektra/KeySet.java
Labels: ready to merge

#3595 core: kdbSet read-only parentKey
  doc/news/_preparation_next_release.md
  src/libs/elektra/kdb.c
Labels: ready to merge

#3625 Minor OCLint & GitHub Actions Update
  .github/workflows/macOS_gcc10.yml
  doc/news/_preparation_next_release.md
  doc/todo/NEWS.md
  scripts/check-env-dep
  tests/shell/check_oclint.sh
Labels: cleanup, continuous integration, lang/shell, ready to merge, testing

#3601 CPack RPM packaging
  CMakeLists.txt
  doc/INSTALL.md
  doc/news/_preparation_next_release.md
  scripts/cmake/ElektraPackaging.cmake
  scripts/cmake/Modules/PackagingDebian.cmake
  scripts/cmake/Modules/PackagingFedora.cmake
  scripts/cmake/Modules/PackagingMacros.cmake
  scripts/docker/fedora/33/Dockerfile
  scripts/kdb/find-tools
  scripts/packaging/fedora/changelog
  scripts/packaging/fedora/map_licenses.sh
  scripts/packaging/fedora/update-rpm-changelog.sh
  scripts/packaging/package.sh
Labels: ready to merge

#3615 Design
  doc/DESIGN.md
  doc/news/_preparation_next_release.md
  doc/paper/paper.bib
  src/libs/elektra/keyname.c
  src/libs/elektra/keyset.c
  src/libs/elektra/keyvalue.c
  src/libs/meta/meta.c
Labels: ready to merge

#3545 Release documentation
  doc/news/_preparation_next_release.md
  doc/todo/RELEASE
Labels: ready to merge

#3641 Minor fixes release notes
  doc/news/_preparation_next_release.md
  doc/todo/NEWS.md
  scripts/cmake/ElektraCache.cmake
  src/bindings/cpp/include/key.hpp
  src/bindings/cpp/tests/testcpp_key.cpp
  src/bindings/swig/ruby/kdb.i
Labels: ready to merge
