Repository ElektraInitiative/libelektra, pull requests merged in 2021-07, with the labels that each got.

#3890 doc: small fixes
  doc/news/_preparation_next_release.md
  doc/tutorials/java-kdb.md
  src/bindings/cpp/include/key.hpp
Labels: ready to merge

#3927 #3874 removed Key::get*AndRelease convenience methods (from public api)
  doc/news/_preparation_next_release.md
  doc/tutorials/java-kdb.md
  src/bindings/jna/libelektra/src/main/java/org/libelektra/Key.java
  src/bindings/jna/libelektra/src/test/java/org/libelektra/KeyTest.java
Labels: lang/java

#3500 Toml fixes
  doc/news/_preparation_next_release.md
  src/libs/elektra/keyname.c
  src/plugins/toml/CMakeLists.txt
  src/plugins/toml/README.md
  src/plugins/toml/comment_list.h
  src/plugins/toml/driver.c
  src/plugins/toml/integer.c
  src/plugins/toml/integer.h
  src/plugins/toml/lexer.l
  src/plugins/toml/node.c
  src/plugins/toml/node.h
  src/plugins/toml/testmod_toml.c
  src/plugins/toml/toml.c
  src/plugins/toml/toml/basic.h
  src/plugins/toml/toml/basic.toml
  src/plugins/toml/toml/checks_toml_1_0_0/invalid_read/apostroph_too_much.toml
  src/plugins/toml/toml/checks_toml_1_0_0/invalid_read/array_redefined_table_array.toml
  src/plugins/toml/toml/checks_toml_1_0_0/invalid_read/empty_assignment.toml
  src/plugins/toml/toml/checks_toml_1_0_0/invalid_read/floats.toml
  src/plugins/toml/toml/checks_toml_1_0_0/invalid_read/inline_appending.toml
  src/plugins/toml/toml/checks_toml_1_0_0/invalid_read/inline_appending2.toml
  src/plugins/toml/toml/checks_toml_1_0_0/invalid_read/integer_redefined_table.toml
  src/plugins/toml/toml/checks_toml_1_0_0/invalid_read/key_redefinition.toml
  src/plugins/toml/toml/checks_toml_1_0_0/invalid_read/key_redefinition_quotes.toml
  src/plugins/toml/toml/checks_toml_1_0_0/invalid_read/no_keyname.toml
  src/plugins/toml/toml/checks_toml_1_0_0/invalid_read/simple_redefined_table_array.toml
  src/plugins/toml/toml/checks_toml_1_0_0/invalid_read/table_array_simple_table_same_name.toml
  src/plugins/toml/toml/checks_toml_1_0_0/invalid_read/table_redefine_value.toml
  src/plugins/toml/toml/checks_toml_1_0_0/invalid_read/table_redefinition.toml
  src/plugins/toml/toml/checks_toml_1_0_0/invalid_read/two_assignments_one_line.toml
  src/plugins/toml/toml/checks_toml_1_0_0/roundtrip.toml
  src/plugins/toml/toml/integer.h
  src/plugins/toml/toml/integer.toml
  src/plugins/toml/toml/integer_overflow/binary.toml
  src/plugins/toml/toml/integer_overflow/decimal.toml
  src/plugins/toml/toml/integer_overflow/decimal_under.toml
  src/plugins/toml/toml/integer_overflow/hexadecimal.toml
  src/plugins/toml/toml/integer_overflow/octal.toml
  src/plugins/toml/toml/key_names_empty.h
  src/plugins/toml/toml/key_names_empty.toml
  src/plugins/toml/toml/simple_table.h
  src/plugins/toml/toml/string_multiline.h
  src/plugins/toml/toml/string_multiline.toml
  src/plugins/toml/type.c
  src/plugins/toml/type.h
  src/plugins/toml/utility.c
  src/plugins/toml/write.c
  tests/ctest/test_keyname.c
Labels: ready to merge

#3843 [CM H3] introduce email validation plugin
  doc/METADATA.ini
  doc/man/man7/elektra-plugins.7
  doc/news/_preparation_next_release.md
  src/plugins/README.md
  src/plugins/email/CMakeLists.txt
  src/plugins/email/README.md
  src/plugins/email/email.c
  src/plugins/email/email.h
  src/plugins/email/test_email.h
  src/plugins/email/testmod_email.c
Labels: ready to merge

#3931 doc: change gpg keyserver for receiving public gpg key for `apt`
  doc/INSTALL.md
  doc/news/_preparation_next_release.md
Labels: ready to merge

#3928 gradle: bump to 7.1.1
  doc/news/_preparation_next_release.md
  scripts/docker/cirrus/fedora/Dockerfile
  scripts/docker/debian/bullseye/Dockerfile
  scripts/docker/debian/buster/Dockerfile
  scripts/docker/debian/sid/Dockerfile
  scripts/docker/debian/stretch/Dockerfile
  scripts/docker/fedora/31/Dockerfile
  scripts/docker/fedora/32/Dockerfile
  scripts/docker/fedora/33/Dockerfile
  scripts/docker/fedora/34/Dockerfile
  scripts/docker/jenkinsnode/Dockerfile
  scripts/docker/ubuntu/bionic/Dockerfile
  scripts/docker/ubuntu/focal/Dockerfile
  src/bindings/jna/gradle/wrapper/gradle-wrapper.properties
Labels: dependencies, ready to merge

#3930 Cm h3 2
  doc/METADATA.ini
  doc/man/man7/elektra-plugins.7
  doc/news/_preparation_next_release.md
  src/plugins/README.md
  src/plugins/length/CMakeLists.txt
  src/plugins/length/README.md
  src/plugins/length/length.c
  src/plugins/length/length.h
  src/plugins/length/test_length.h
  src/plugins/length/testmod_length.c
Labels: ready to merge

#3915 Aaronabebe spec tutorial
  doc/news/_preparation_next_release.md
  doc/tutorials/specification.md
Labels: ready to merge

#3858 Add additional tests for module keyset
  doc/api_review/core/ksAppend.md
  doc/api_review/core/ksAppendKey.md
  doc/api_review/core/ksAtCursor.md
  doc/api_review/core/ksCopy.md
  doc/api_review/core/ksCurrent.md
  doc/api_review/core/ksCut.md
  doc/api_review/core/ksDel.md
  doc/api_review/core/ksDup.md
  doc/api_review/core/ksGetCursor.md
  doc/api_review/core/ksGetSize.md
  doc/api_review/core/ksHead.md
  doc/api_review/core/ksLookup.md
  doc/api_review/core/ksLookupByName.md
  doc/api_review/core/ksNew.md
  doc/api_review/core/ksNext.md
  doc/api_review/core/ksPop.md
  doc/api_review/core/ksRewind.md
  doc/api_review/core/ksSetCursor.md
  doc/api_review/core/ksTail.md
  doc/api_review/core/ksVNew.md
  doc/news/_preparation_next_release.md
  tests/abi/testabi_ks.c
Labels: ready to merge

#3657 Implement fuse-prototype including context-mocking and README.md
  doc/news/_preparation_next_release.md
  scripts/cmake/ElektraCache.cmake
  src/tools/README.md
  src/tools/fuse/.gitignore
  src/tools/fuse/CMakeLists.txt
  src/tools/fuse/MANIFEST.in
  src/tools/fuse/Makefile
  src/tools/fuse/README.md
  src/tools/fuse/docker/Dockerfile
  src/tools/fuse/docker/build_container.sh
  src/tools/fuse/docker/create_gopts_keys.py
  src/tools/fuse/docker/create_keys.sh
  src/tools/fuse/docker/create_keys_and_mount.sh
  src/tools/fuse/docker/do_nothing.c
  src/tools/fuse/docker/remove_container.sh
  src/tools/fuse/docker/run_new_container.sh
  src/tools/fuse/docker/sample_config_files/config.ini
  src/tools/fuse/docker/sample_config_files/config.json
  src/tools/fuse/docker/sample_config_files/config.xml
  src/tools/fuse/docker/start_dummy_proc.sh
  src/tools/fuse/fuse.in
  src/tools/fuse/pyproject.toml
  src/tools/fuse/setup.cfg
  src/tools/fuse/setup.py
  src/tools/fuse/src/elektra_fuse.egg-info/dependency_links.txt
  src/tools/fuse/src/elektra_fuse.egg-info/entry_points.txt
  src/tools/fuse/src/elektra_fuse.egg-info/requires.txt
  src/tools/fuse/src/elektra_fuse.egg-info/top_level.txt
  src/tools/fuse/src/elektra_fuse/__init__.py
  src/tools/fuse/src/elektra_fuse/elektra_fuse_interface.py
  src/tools/fuse/src/elektra_fuse/elektra_util.py
  src/tools/fuse/src/elektra_fuse/mock_context.py
  src/tools/fuse/src/elektra_fuse/rootlevel_resolver.py
Labels: ready to merge

#3852 Add additional test cases for module keyvalue
  doc/api_review/core/keyGetBinary.md
  doc/api_review/core/keyGetString.md
  doc/api_review/core/keyGetValueSize.md
  doc/api_review/core/keySetBinary.md
  doc/api_review/core/keyString.md
  doc/news/_preparation_next_release.md
  tests/abi/testabi_key.c
Labels: ready to merge

#3850 Add additional test cases for module key
  doc/api_review/core/keyDecRef.md
  doc/api_review/core/keyGetRef.md
  doc/api_review/core/keyIncRef.md
  doc/api_review/core/keyIsLocked.md
  doc/api_review/core/keyLock.md
  doc/api_review/core/keyNew.md
  doc/news/_preparation_next_release.md
  src/libs/elektra/key.c
  tests/abi/testabi_key.c
  tests/ctest/test_key.c
Labels: ready to merge

#3348 GSettings Backend fixes
  doc/news/_preparation_next_release.md
  src/bindings/glib/gelektra-key.c
  src/bindings/glib/gelektra-key.h
  src/bindings/gsettings/elektrasettingsbackend.c
Labels: ready to merge

#3932 docker: upgrade Alpine images to 3.14.0
  doc/news/_preparation_next_release.md
  scripts/docker/alpine/3.14/Dockerfile
  scripts/docker/alpine/3.14/release.Dockerfile
  scripts/jenkins/Jenkinsfile
Labels: ready to merge

#3934 cache: fix default backend and initial parentKey
  doc/news/_preparation_next_release.md
  src/libs/elektra/kdb.c
  src/libs/elektra/split.c
  src/plugins/resolver/resolver.c
Labels: ready to merge

#3940 doc: update news template statistics
  doc/news/2021-07-09_0.9.7.md
  doc/news/_preparation_next_release.md
  doc/todo/NEWS.md
Labels: documentation

#3942 Remove obsolete `ksNeedSync`
  doc/news/_preparation_next_release.md
  doc/todo/FUTURE
  src/bindings/jna/libelektra/src/main/java/org/libelektra/Elektra.java
  src/include/kdb.h.in
  src/libs/elektra/keyset.c
  src/libs/elektra/symbols.map
  src/tools/elektrad/go.mod
  src/tools/elektrad/go.sum
  tests/abi/testabi_ks.c
Labels: ready to merge

#3936 Fixes
  .cirrus.yml
  .github/workflows/macOS_gcc10.yml
  doc/TESTING.md
  doc/man/man1/kdb-run-hub-zeromq.1
  doc/news/_preparation_next_release.md
  scripts/cmake/ElektraCache.cmake
  scripts/cmake/Modules/LibAddMacros.cmake
  src/tools/hub-zeromq/CMakeLists.txt
  src/tools/hub-zeromq/hub-zeromq.c
Labels: ready to merge

#3945 actions: add macOS job matrix
  .cirrus.yml
  .github/workflows/macOS.yml
  doc/news/_preparation_next_release.md
Labels: ready to merge

#3946 Fixes
  doc/news/_preparation_next_release.md
  doc/tutorials/specification.md
  src/tools/website/public/assets/translations/en.json
Labels: ready to merge

#3762 authors: remove people without code
  doc/AUTHORS.md
  doc/news/_preparation_next_release.md
  doc/todo/NEWS.md
  src/plugins/mozprefs/README.md
Labels: cleanup, ready to merge

#3947 docker: use tmpfs for `build` commands
  doc/news/_preparation_next_release.md
  scripts/docker/alpine/3.14/release.Dockerfile
  scripts/docker/debian/bullseye/release.Dockerfile
  scripts/docker/debian/buster/release.Dockerfile
  scripts/docker/fedora/33/release.Dockerfile
  scripts/docker/fedora/34/release.Dockerfile
  scripts/docker/ubuntu/bionic/release.Dockerfile
  scripts/docker/ubuntu/focal/release.Dockerfile
  scripts/docker/website/Dockerfile
Labels: continuous integration, ready to merge

#3950 cirrus: FreeBSD updates
  .cirrus.yml
  .travis.yml
  doc/CODING.md
  doc/COMPILE.md
  doc/news/2019-08-06_0.9.0.md
  doc/news/_preparation_next_release.md
Labels: continuous integration
