Repository ElektraInitiative/libelektra, pull requests merged in 2022-11, with the labels that each got.

#4635 Fix JavaDoc generation on Debian Sid
  doc/decisions/change_tracking.md
  doc/decisions/operation_sequences.md
  doc/news/2014-09-02_0.8.8.md
  doc/news/2022-10-05_0.9.11.md
  doc/news/_preparation_next_release.md
  scripts/docker/debian/sid/Dockerfile
  src/bindings/jna/CMakeLists.txt
  tests/linkchecker.whitelist
Labels: urgent

#4631 [FLOSS H2] documentation: fix some minor mistakes in CONTRIBUTING.md
  .github/CONTRIBUTING.md
  doc/news/_preparation_next_release.md
Labels: ready to merge, documentation

#4640 [FLOSS H3] Delete leftover package-lock.json
  doc/news/_preparation_next_release.md
  src/tools/elektrad/package-lock.json
Labels: ready to merge, H3

#4506 PR#4492 (updates for upcoming release) Review - suggestions
  doc/contrib/documentation.md
  doc/dev/architecture.md
  doc/dev/data-structures.md
  doc/news/_preparation_next_release.md
  src/plugins/template/README.md
Labels: ready to merge

#4651 [FLOSS H2] Add Installation instructions for Arch
  doc/INSTALL.md
  doc/news/_preparation_next_release.md
Labels: documentation, floss2022w, H2

#4650 [FLOSS H2] CMake fix developer warning for package DISCOUNT
  .reuse/dep5
  doc/news/_preparation_next_release.md
  scripts/cmake/Modules/FindDISCOUNT.cmake
  src/tools/qt-gui/CMakeLists.txt
Labels: ready to merge, lang/cmake, floss2022w, H2

#4656 [FLOSS H2] Fix grammar for elektra-granularity.md
  doc/help/elektra-granularity.md
  doc/man/man7/elektra-granularity.7
  doc/news/_preparation_next_release.md
Labels: ready to merge, documentation, floss2022w, H2

#4658 [FLOSS H2] Fix typo in doc/dev/hooks.md
  doc/dev/hooks.md
  doc/news/_preparation_next_release.md
Labels: ready to merge, documentation, floss2022w, H2

#4660 [FLOSS H2] Improve readability of doc/tutorials/highlevel.md
  doc/news/_preparation_next_release.md
  doc/tutorials/highlevel.md
Labels: ready to merge, documentation, floss2022w, H2

#4663 doc: Update Getstarted with links to documentation
  doc/GETSTARTED.md
  doc/news/_preparation_next_release.md
Labels: ready to merge, documentation, H2

#4664 [FLOSS H2] Fix broken links and redirect logic of website
  doc/news/2017-03-18_lcdproc.md
  doc/news/_preparation_next_release.md
  src/bindings/cpp/README.md
  src/tools/website/public/assets/translations/en.json
  src/tools/website/resources/assets/js/config/routes.js
Labels: ready to merge, lang/web, floss2022w, H2

#4668 [FLOSS H2] Rephrase sections in doc/dev/error-*
  doc/dev/error-categorization.md
  doc/dev/error-handling.md
  doc/dev/error-message.md
  doc/news/_preparation_next_release.md
Labels: documentation, floss2022w, H2

#4630 [FLOSS H2] documentation: Unify spelling of documentation
  README.md
  doc/VERSION.md
  doc/decisions/2_in_progress/functions_with_buffers.md
  doc/decisions/2_in_progress/iterators.md
  doc/decisions/5_implemented/semantics_name.md
  doc/news/2014-06-21_0.8.6.md
  doc/news/2014-07-28_0.8.7.md
  doc/news/2014-09-02_0.8.8.md
  doc/news/2014-11-04_0.8.9.md
  doc/news/2014-12-02_0.8.10.md
  doc/news/2015-04-03_0.8.11.md
  doc/news/2015-07-13_0.8.12.md
  doc/news/2015-09-17_0.8.13.md
  doc/news/2015-11-19_0.8.14.md
  doc/news/2016-02-16_0.8.15.md
  doc/news/2016-04-29_0.8.16.md
  doc/news/2016-06-14_0.8.17.md
  doc/news/2016-09-17_0.8.18.md
  doc/news/2016-11-22_0.8.19.md
  doc/news/2017-10-31_0.8.20.md
  doc/news/2017-12-22_0.8.21.md
  doc/news/2018-03-27_0.8.22.md
  doc/news/2018-05-13_0.8.23.md
  doc/news/2018-08-18_0.8.24.md
  doc/news/2018-11-18_0.8.25.md
  doc/news/2019-02-26_0.8.26.md
  doc/news/2019-08-06_0.9.0.md
  doc/news/2019-11-26_0.9.1.md
  doc/news/2020-05-26_0.9.2.md
  doc/news/2020-10-30_0.9.3.md
  doc/news/2021-02-01_0.9.4.md
  doc/news/2021-04-12_0.9.5.md
  doc/news/2021-06-07_0.9.6.md
  doc/news/2021-07-09_0.9.7.md
  doc/news/2021-10-04_0.9.8.md
  doc/news/2022-03-10_0.9.9.md
  doc/news/2022-07-11_0.9.10.md
  doc/news/2022-10-05_0.9.11.md
  doc/news/_preparation_next_release.md
  doc/todo/NEWS.md
  scripts/sed
  src/bindings/template/README.md
  src/libs/template/README.md
Labels: ready to merge, documentation, floss2022w, H2

#4629 [FLOSS H2] doc: remove "Don't panic" from Git
  doc/GETSTARTED.md
  doc/news/_preparation_next_release.md
Labels: ready to merge, documentation, floss2022w, H2

#4654 [FLOSS H2] io file flag check
  doc/news/_preparation_next_release.md
  src/libs/io/io.c
Labels: lang/c, floss2022w, H2

#4693 [FLOSS T1] Fixed Coverage Badge Link
  README.md
  doc/news/_preparation_next_release.md
Labels: T1

#4646 [FLOSS H2] Reinstate Mounting tutorial
  doc/news/_preparation_next_release.md
  doc/tutorials/mount.md
  scripts/sed
Labels: documentation, floss2022w, H2

#4644 [FLOSS H2] Add uname error handling
  doc/news/_preparation_next_release.md
  src/plugins/uname/README.md
  src/plugins/uname/uname.c
Labels: lang/c, floss2022w, H2

#4703 [FLOSS T1] fix: shell recorder warnings parsing
  doc/news/_preparation_next_release.md
  tests/shell/shell_recorder/shell_recorder.sh
Labels: ready to merge, T1

#4661 [FLOSS H2] jna: Update compilation instructions in readme.md
  doc/news/_preparation_next_release.md
  src/bindings/jna/README.md
Labels: documentation, project2022w, H2

#4647 [FLOSS H2] Fix outdated ansible example in vision.md
  doc/VISION.md
  doc/news/_preparation_next_release.md
Labels: documentation, floss2022w, H2

#4707 [FLOSS T1] shellrecorder: fix/extends two shell recorder checks
  doc/news/_preparation_next_release.md
  tests/shell/shell_recorder/mathcheck.esr
  tests/shell/shell_recorder/selftest.esr
Labels: ready to merge, T1

#4712 [FLOSS T1] CI: Fix npm reproducability issues
  doc/news/_preparation_next_release.md
  scripts/dev/audit-dependencies
  src/tools/webd/CMakeLists.txt
  src/tools/website/CMakeLists.txt
Labels: lang/cmake, lang/shell, continuous integration, T1

#4704 [FLOSS T1] Add shellcheck to Debian containers
  doc/news/_preparation_next_release.md
  scripts/docker/debian/bullseye/Dockerfile
  scripts/docker/debian/buster/Dockerfile
  scripts/docker/debian/sid/Dockerfile
Labels: T1

#4694 [FLOSS T1] Fix segfault from circular links (overrides)
  doc/news/_preparation_next_release.md
  src/libs/elektra/keyset.c
  tests/ctest/test_ks.c
Labels: T1

#4695 [FLOSS T1] Change checking of stale issues/PRs to GitHub action
  .github/stale.yml
  .github/workflows/stale.yml
  doc/news/_preparation_next_release.md
Labels: T1

#4665 [FLOSS H2] doc: Use of `Code` blocks on package and variable names in INSTALL.md
  doc/INSTALL.md
  doc/news/_preparation_next_release.md
Labels: floss2022w, H2

#4701 [FLOSS T1] fix-spelling: Fix an issue where tests fails, when path contains whitespaces
  doc/contrib/documentation.md
  doc/news/2017-12-22_0.8.21.md
  doc/news/2022-03-10_0.9.9.md
  doc/news/_preparation_next_release.md
  scripts/dev/fix-spelling
  scripts/spelling.sed
  tests/shell/check_spelling.sh
Labels: continuous integration, testing, T1
