Repository ElektraInitiative/libelektra, pull requests merged in 2022-10, with the labels that each got.

#4492 updates for upcoming release
  .github/PULL_REQUEST_TEMPLATE.md
  .github/stale.yml
  LICENSE.md
  doc/contrib/documentation.md
  doc/decisions/elektra_prefix.md
  doc/decisions/private_api.md
  doc/dev/architecture.md
  doc/dev/data-structures.md
  doc/help/elektra-glossary.md
  doc/man/man7/elektra-glossary.7
  doc/news/_preparation_next_release.md
  scripts/dev/reformat-all
  scripts/dev/run_checkshell.in
  src/bindings/template/README.md
  src/libs/template/README.md
  src/plugins/csvstorage/csvstorage.c
  src/plugins/lua/CMakeLists.txt
  src/plugins/template/README.md
  src/plugins/type/testmod_type.c
  src/tools/fuse/README.md
  src/tools/kdb/gen/highlevel/highlevel.cpp
  src/tools/template/README.md
  src/tools/website/resources/structure.json.in
Labels: ready to merge

#4504 [new-backend] notification send hooks
  doc/dev/hooks.md
  doc/news/_preparation_next_release.md
  src/include/kdbprivate.h
  src/libs/elektra/hooks.c
  src/libs/elektra/kdb.c
  src/libs/elektra/split.c
  src/plugins/dbus/dbus.c
  src/plugins/internalnotification/internalnotification.c
  src/plugins/zeromqsend/zeromqsend.c
  tests/ctest/test_hooks.c
Labels: ready to merge

#4540 Update pcre packagename from debian sid
  doc/news/_preparation_next_release.md
  scripts/docker/debian/sid/Dockerfile
Labels: build, ready to merge

#4528 document decision process
  doc/contrib/documentation.md
  doc/decisions/EXPLANATIONS.md
  doc/decisions/README.md
  doc/decisions/TEMPLATE.md
  doc/decisions/decision_process.md
  doc/decisions/manpages.md
  doc/news/_preparation_next_release.md
  doc/todo/NEWS.md
Labels: ready to merge

#4561 jenkins improvements
  doc/news/_preparation_next_release.md
  scripts/jenkins/Jenkinsfile
Labels: ready to merge

#4575 [FLOSS H2/H3] Fix SIGSEGV in kdb find
  doc/news/_preparation_next_release.md
  src/tools/kdb/find.cpp
Labels: ready to merge, floss2022w, H2, H3

#4556 ci: add cancellation job to github action
  .github/workflows/macOS.yml
  doc/news/_preparation_next_release.md
Labels: ready to merge

#4622 logchange: add notification-send hooks to contract
  doc/news/_preparation_next_release.md
  src/plugins/logchange/logchange.c
Labels: needs review
