Repository ElektraInitiative/libelektra, pull requests merged in 2022-01, with the labels that each got.

#4210 [FLOSS T3] Update and improve the CLion tutorial, add screenshots
  doc/images/clion/cmake_edit_profile.png
  doc/images/clion/cmake_edit_profile_build_option.png
  doc/images/clion/cmake_load.png
  doc/images/clion/ctest_config.png
  doc/images/clion/ctest_run.png
  doc/images/clion/git_commit.png
  doc/images/clion/git_create_branch.png
  doc/images/clion/git_settings.png
  doc/images/clion/vcs_button.png
  doc/images/clion/vcs_import.png
  doc/news/_preparation_next_release.md
  doc/tutorials/contributing-clion.md
Labels: lang/markdown, documentation, floss2021W

#4196 doc: forgot to install gnupg and removed sudo
  doc/news/_preparation_next_release.md
  doc/tutorials/python-kdb.md
Labels: ready to merge

#4134 [FLOSS H2] Python bindings: added examples for append, extend and remove
  doc/news/_preparation_next_release.md
  src/bindings/swig/python/examples/example_keyset.py
Labels: ready to merge

#4190 [FLOSS H3] enable all shell recorder
  doc/news/_preparation_next_release.md
  src/plugins/augeas/README.md
  src/plugins/base64/README.md
  src/plugins/crypto/README.md
  src/plugins/desktop/README.md
  src/plugins/error/README.md
  src/plugins/fstab/README.md
  src/plugins/gitresolver/README.md
  src/plugins/iterate/README.md
  src/plugins/logchange/README.md
  src/plugins/passwd/README.md
  src/plugins/python/README.md
  tests/shell/shell_recorder/tutorial_wrapper/CMakeLists.txt
Labels: ready to merge, testing

#4178 [FLOSS T2] improve storage plugin tutorial by adding sections about ordering and comments
  doc/news/_preparation_next_release.md
  doc/tutorials/storage-plugins.md
Labels: ready to merge, documentation, floss2021W

#4126 [FLOSS H2] Small correction of the build path in the "Get Strarted" guide
  doc/GETSTARTED.md
  doc/news/_preparation_next_release.md
Labels: documentation

#4206 [FLOSS T3] Add flatpak package
  .gitignore
  doc/news/_preparation_next_release.md
  scripts/flatpak/README.md
  scripts/flatpak/org.libelektra.kdb.appdata.xml
  scripts/flatpak/org.libelektra.kdb.desktop
  scripts/flatpak/org.libelektra.kdb.svg
  scripts/flatpak/org.libelektra.kdb.yaml
Labels: ready to merge

#4209 [FLOSS T3] Improve GETSTARTED.md / Link to Web UI Installation Tutorial in webui/README.md / Add Link to Docker Guide to README.md
  README.md
  doc/GETSTARTED.md
  doc/man/man1/kdb-qt-gui.1
  doc/news/_preparation_next_release.md
  scripts/dev/.devcontainer/Dockerfile
  scripts/dev/.devcontainer/README.md
  scripts/dev/.devcontainer/devcontainer.json
  src/tools/qt-gui/README.md
  src/tools/qt-gui/images/Qt-GUI-1.png
  src/tools/qt-gui/images/Qt-GUI-2.png
  src/tools/qt-gui/images/Qt-GUI-3.png
  src/tools/qt-gui/images/Qt-GUI-4.png
  src/tools/qt-gui/images/Qt-GUI-5.png
  src/tools/qt-gui/images/Qt-GUI-6.png
  src/tools/webui/README.md
Labels: documentation, floss2021W

#4224 [FLOSS P3] Kdb validate
  doc/decisions/error_codes.md
  doc/help/kdb-validate.md
  doc/man/man1/kdb-validate.1
  doc/man/man7/elektra-plugins.7
  doc/news/_preparation_next_release.md
  doc/tutorials/highlevel-bindings.md
  doc/tutorials/install-webui.md
  doc/tutorials/validation.md
  src/libs/elektra/symbols.map
  src/libs/tools/include/CMakeLists.txt
  src/libs/tools/include/errors/baseNotification.hpp
  src/libs/tools/include/errors/error.hpp
  src/libs/tools/include/errors/errorFactory.hpp
  src/libs/tools/include/errors/errorTypes.hpp
  src/libs/tools/include/errors/warning.hpp
  src/libs/tools/include/errors/warningFactory.hpp
  src/libs/tools/include/errors/warningTypes.hpp
  src/libs/tools/src/errors/baseNotification.cpp
  src/libs/tools/src/errors/error.cpp
  src/libs/tools/src/errors/errorFactory.cpp
  src/libs/tools/src/errors/errorTypes.cpp
  src/libs/tools/src/errors/warning.cpp
  src/libs/tools/src/errors/warningFactory.cpp
  src/libs/tools/src/errors/warningTypes.cpp
  src/libs/tools/tests/testtool_error.cpp
  src/plugins/README.md
  src/plugins/ni/README.md
  src/plugins/range/range.c
  src/tools/kdb/cmdline.hpp
  src/tools/kdb/coloredkdbio.hpp
  src/tools/kdb/factory.hpp
  src/tools/kdb/plugincheck.cpp
  src/tools/kdb/plugincheck.hpp
  src/tools/kdb/validate.cpp
  src/tools/kdb/validate.hpp
  tests/linkchecker.whitelist
  tests/shell/shell_recorder/tutorial_wrapper/CMakeLists.txt
Labels: ready to merge, lang/cpp, floss2021W, project2021W
