Repository ElektraInitiative/libelektra, pull requests merged in 2022-05, with the labels that each got.

#4351 [CM T2] Lineendings Plugin
  doc/news/_preparation_next_release.md
  src/plugins/lineendings/README.md
  src/plugins/lineendings/lineendings.c
  src/plugins/lineendings/lineendings/inconsistent1
  src/plugins/lineendings/lineendings/inconsistent2
  src/plugins/lineendings/lineendings/invalid1
  src/plugins/lineendings/lineendings/invalid2
  src/plugins/lineendings/lineendings/valid3
  src/plugins/lineendings/lineendings/valid4
  src/plugins/lineendings/testmod_lineendings.c
Labels: ready to merge, lang/c, cm2022s

#4342 [CM T2] Java Sorted Plugin
  doc/news/_preparation_next_release.md
  src/bindings/jna/plugins/sorted/README.md
  src/bindings/jna/plugins/sorted/src/main/java/org/libelektra/plugin/SortedContract.java
  src/bindings/jna/plugins/sorted/src/main/java/org/libelektra/plugin/SortedPlugin.java
  src/bindings/jna/plugins/sorted/src/test/java/org/libelektra/plugin/SortedPluginTest.java
  src/bindings/jna/plugins/sorted/src/test/java/org/libelektra/plugin/TestData.java
  src/bindings/jna/settings.gradle
Labels: lang/java

#4352 [CM P1] JNA/Kotlin binding
  doc/news/_preparation_next_release.md
  src/bindings/jna/kotlin/README.md
  src/bindings/jna/kotlin/build.gradle
  src/bindings/jna/kotlin/dependencies.gradle
  src/bindings/jna/kotlin/src/main/kotlin/org/libelektra/dsl/KeyBuilder.kt
  src/bindings/jna/kotlin/src/main/kotlin/org/libelektra/dsl/KeySetBuilder.kt
  src/bindings/jna/kotlin/src/main/kotlin/org/libelektra/kdbExt/OpenExt.kt
  src/bindings/jna/kotlin/src/main/kotlin/org/libelektra/keyExt/GetExt.kt
  src/bindings/jna/kotlin/src/main/kotlin/org/libelektra/keyExt/SetExt.kt
  src/bindings/jna/kotlin/src/main/kotlin/org/libelektra/keyExt/Util.kt
  src/bindings/jna/kotlin/src/main/kotlin/org/libelektra/keySetExt/KeySetJsonExt.kt
  src/bindings/jna/kotlin/src/main/kotlin/org/libelektra/keySetExt/KeySetSerializationExt.kt
  src/bindings/jna/kotlin/src/main/kotlin/org/libelektra/keySetExt/Util.kt
  src/bindings/jna/kotlin/src/test/kotlin/org/libelektra/kdb/OpenTest.kt
  src/bindings/jna/kotlin/src/test/kotlin/org/libelektra/key/GetKeyTest.kt
  src/bindings/jna/kotlin/src/test/kotlin/org/libelektra/key/KeyBuilderTest.kt
  src/bindings/jna/kotlin/src/test/kotlin/org/libelektra/key/SetKeyTest.kt
  src/bindings/jna/kotlin/src/test/kotlin/org/libelektra/key/UtilTest.kt
  src/bindings/jna/kotlin/src/test/kotlin/org/libelektra/keySet/KeySetBuilderTest.kt
  src/bindings/jna/kotlin/src/test/kotlin/org/libelektra/keySet/KeySetJsonTest.kt
  src/bindings/jna/kotlin/src/test/kotlin/org/libelektra/keySet/KeySetSerializationTest.kt
  src/bindings/jna/kotlin/src/test/kotlin/org/libelektra/keySet/UtilTest.kt
  src/bindings/jna/settings.gradle
Labels: lang/java, cm2022s, project2022s, java

#4361 [CM T3] python: fullname property in docs
  doc/news/_preparation_next_release.md
  src/bindings/swig/python/examples/example_key.py
Labels: lang/python, cm2022s, needs review

#4305 [CM P0] Replace internal iterators
  doc/dev/README.md
  doc/dev/iterators.md
  doc/news/_preparation_next_release.md
  tests/linkchecker.whitelist
Labels: proposal, lang/markdown, cm2022s

#4363 [CM T3] plugin/length: warnings are now added when performing kdb get
  .idea/codeStyles/Project.xml
  doc/news/_preparation_next_release.md
  src/plugins/length/README.md
  src/plugins/length/length.c
  src/plugins/length/test_length.h
Labels: lang/c, cm2022s, needs review
