Repository ElektraInitiative/libelektra, pull requests merged in 2022-04, with the labels that each got.

#4310 [CM T1] Fix errors in tutorials for Cascading Lookups and Command-line Options
  doc/news/_preparation_next_release.md
  doc/tutorials/cascading.md
  doc/tutorials/command-line-options.md
Labels: ready to merge, lang/markdown, cm2022s

#4324 [CM T1] doc: Overhauls the GETSTARTED.md by adding a brief kdb introduction
  doc/GETSTARTED.md
  doc/news/_preparation_next_release.md
  tests/linkchecker.whitelist
Labels: lang/markdown, cm2022s

#4336 [CM T1] python binding: added unit tests for len, reversed, head and tail methods to keySet tests
  doc/news/_preparation_next_release.md
  src/bindings/swig/python/tests/test_keyset.py
Labels: ready to merge

#4315 [CM T1] Improve and extend the tutorial for writing specifications
  doc/news/_preparation_next_release.md
  doc/tutorials/java-kdb.md
  doc/tutorials/specification.md
  src/include/CMakeLists.txt
  src/include/kdbconfig.h.in
  src/plugins/ni/nickel-1.1.0/src/hash.c
  tests/shell/shell_recorder/tutorial_wrapper/CMakeLists.txt
Labels: lang/markdown, cm2022s
