Repository ElektraInitiative/libelektra, pull requests merged in 2022-12, with the labels that each got.

#4692 [FLOSS T1] Unify spelling of man page
  README.md
  doc/help/CMakeLists.txt
  doc/man/man1/kdb-run-website.1
  doc/news/2017-03-18_lcdproc.md
  doc/news/2018-08-18_0.8.24.md
  doc/news/2019-08-06_0.9.0.md
  doc/news/2019-11-26_0.9.1.md
  doc/news/2021-07-09_0.9.7.md
  doc/news/2022-03-10_0.9.9.md
  doc/news/_preparation_next_release.md
  doc/tutorials/java-plugins.md
  doc/tutorials/specification.md
  scripts/cmake/ElektraManPage.cmake
  scripts/cmake/Modules/LibAddMacros.cmake
  scripts/spelling.sed
  src/bindings/intercept/env/CMakeLists.txt
  src/include/kdbendian.h
  src/libs/CMakeLists.txt
  src/plugins/CMakeLists.txt
  src/plugins/journald/README.md
  src/tools/elektrad/CMakeLists.txt
  src/tools/fuse/src/elektra_fuse/elektra_util.py
  src/tools/hub-zeromq/CMakeLists.txt
  src/tools/pythongen/CMakeLists.txt
  src/tools/pythongen/template/template.man
  src/tools/qt-gui/CMakeLists.txt
  src/tools/webd/CMakeLists.txt
  src/tools/website/CMakeLists.txt
  src/tools/website/README.md
  src/tools/website/public/assets/translations/en.json
  src/tools/website/resources/structure.json.in
Labels: ready to merge, T1

#4609 [FLOSS H3] Doxygen: Update Doxyfile and CMake configuration
  doc/CMakeLists.txt
  doc/Doxyfile
  doc/news/_preparation_next_release.md
Labels: floss2022w, H3

#4733 [FLOSS H3] Linkchecker/doc
  doc/markdownlinkconverter/README.md
  doc/news/_preparation_next_release.md
Labels: documentation, floss2022w, H3

#4598 [FLOSS H3] Doxygen: Update Doxyfile with Doxygen 1.9.4
  doc/Doxyfile
  doc/news/_preparation_next_release.md
Labels: low priority, floss2022w, H3

#4720 [FLOSS H3] toml: fix silent failure on meta-key insertion
  doc/news/_preparation_next_release.md
  src/plugins/toml/testmod_toml.c
  src/plugins/toml/write.c
Labels: floss2022w, H3

#4710 [FLOSS T1] blockresolver possible out of bounds memory access
  doc/news/_preparation_next_release.md
  src/plugins/blockresolver/blockresolver/encoding.block
  src/plugins/blockresolver/testmod_blockresolver.c
Labels: ready to merge, floss2022w, T1

#4754 [FLOSS T2] Remove duplicated `TESTING.md` link from website
  doc/news/_preparation_next_release.md
  src/tools/website/resources/structure.json.in
Labels: floss2022w, T2

#4724 [FLOSS H3] yajl: fix silent failure on meta-key insertion
  doc/news/_preparation_next_release.md
  src/plugins/yajl/testmod_yajl.c
  src/plugins/yajl/yajl_gen.c
Labels: bug, lang/c, floss2022w, H3

#4711 [FLOSS T1] plugin: date: Fix rfc822 validation issue
  doc/news/_preparation_next_release.md
  src/plugins/date/date.c
  src/plugins/date/date.h
  src/plugins/date/testmod_date.c
Labels: bug, lang/c, floss2022w, T1

#4731 [FLOSS T2] Documentation: Update packaging instructions for Fedora
  doc/INSTALL.md
  doc/news/_preparation_next_release.md
Labels: floss2022w, T2

#4742 [FLOSS T2] Tutorials: Make namespaces tutorial verifiable
  doc/images/tutorial_namespaces_hierarchy.svg
  doc/news/_preparation_next_release.md
  doc/tutorials/namespaces.md
  tests/shell/shell_recorder/tutorial_wrapper/CMakeLists.txt
Labels: floss2022w, T2

#4746 [FLOSS T2] docs: fix spelling errors
  doc/KEYNAMES.md
  doc/contrib/copy_on_write.md
  doc/contrib/documentation.md
  doc/decisions/0_drafts/change_tracking.md
  doc/decisions/0_drafts/plugin_contract_function.md
  doc/decisions/2_in_progress/iterators.md
  doc/decisions/3_decided/header_include.md
  doc/decisions/3_decided/iterating_name_parts.md
  doc/dev/error-handling.md
  doc/dev/iterators.md
  doc/news/_preparation_next_release.md
  doc/tutorials/command-line-options.md
  doc/tutorials/highlevel-bindings.md
  doc/tutorials/notifications.md
Labels: floss2022w, T2

#4725 [FLOSS H3] csvstorage: fix silent failure on meta-key insertion
  doc/news/_preparation_next_release.md
  src/plugins/csvstorage/csvstorage.c
  src/plugins/csvstorage/testmod_csvstorage.c
Labels: floss2022w, H3

#4699 [FLOSS T1] Replace deprecated egrep
  doc/news/_preparation_next_release.md
  scripts/build/run_check_release_notes
  scripts/dev/copy-template
  scripts/dev/untidy-source
  src/bindings/jna/CMakeLists.txt
  tests/shell/check_kdb_internal_check.sh
  tests/shell/include_common.sh.in
  tests/shell/shell_recorder/tutorial_wrapper/markdown_shell_recorder.sh
Labels: floss2022w, T1

#4709 [FLOSS H3] Shell recorder: Fix test creation and add check if file exists
  doc/news/_preparation_next_release.md
  tests/shell/shell_recorder/CMakeLists.txt
  tests/shell/shell_recorder/shell_recorder.sh
Labels: ready to merge, floss2022w, H3

#4727 [FLOSS H3] Include mermaid-js in Doxygens configuration
  doc/Doxyfile
  doc/doxygen/footer.html
  doc/doxygen/header.html
  doc/images/hp.jpg
  doc/images/link_button_1.gif
  doc/images/logo/logo_color_doxygen.svg
  doc/images/mermaid/state.mmd
  doc/images/type-binary.png
  doc/images/type-extendedbinary.png
  doc/images/type-extendedstring.png
  doc/images/type-folder.png
  doc/images/type-link.png
  doc/images/type-string.png
  doc/man/man7/elektra-libs.7
  doc/news/_preparation_next_release.md
  src/libs/elektra/kdb.c
Labels: ready to merge, documentation, floss2022w, H3

#4774 [FLOSS T2] Improve structure of doc/tutorials/notifications.md
  doc/news/_preparation_next_release.md
  doc/tutorials/notifications.md
Labels: ready to merge, floss2022w, T2

#4775 [FLOSS T2] Update doc/tutorials/install-webui.md
  doc/news/_preparation_next_release.md
  doc/tutorials/install-webui.md
Labels: ready to merge, floss2022w, T2

#4767 [FLOSS T3] Update tag in scripts/docker/README.md
  doc/news/_preparation_next_release.md
  scripts/docker/README.md
Labels: ready to merge, documentation, T3

#4769 [FLOSS T3] scripts: Add scripts to setup pre-commit-hook script
  doc/CODING.md
  doc/news/_preparation_next_release.md
  scripts/dev/disable-pre-commit-hook
  scripts/dev/enable-pre-commit-hook
  scripts/dev/pre-commit-check-formatting
  scripts/dev/reformat-c
Labels: documentation, floss2022w, T3

#4680 [FLOSS H3] docs: harmonize spelling of Git and CMake/cmake
  README.md
  doc/API.md
  doc/BUILDSERVER.md
  doc/CODING.md
  doc/COMPILE.md
  doc/GETSTARTED.md
  doc/Git.md
  doc/README.md
  doc/TESTING.md
  doc/contrib/documentation.md
  doc/decisions/2_in_progress/simplify_api.md
  doc/decisions/3_decided/decision_process.md
  doc/decisions/5_implemented/cmake_plugins.md
  doc/dev/error-categorization.md
  doc/man/man7/elektra-plugins.7
  doc/news/2014-06-21_0.8.6.md
  doc/news/2014-09-02_0.8.8.md
  doc/news/2014-11-04_0.8.9.md
  doc/news/2015-04-03_0.8.11.md
  doc/news/2015-07-13_0.8.12.md
  doc/news/2016-02-16_0.8.15.md
  doc/news/2016-06-14_0.8.17.md
  doc/news/2016-09-17_0.8.18.md
  doc/news/2016-11-22_0.8.19.md
  doc/news/2017-03-18_lcdproc.md
  doc/news/2017-12-22_0.8.21.md
  doc/news/2018-05-13_0.8.23.md
  doc/news/2018-08-18_0.8.24.md
  doc/news/2019-02-26_0.8.26.md
  doc/news/2019-08-06_0.9.0.md
  doc/news/2020-10-30_0.9.3.md
  doc/news/2021-02-01_0.9.4.md
  doc/news/2021-06-07_0.9.6.md
  doc/news/2021-07-09_0.9.7.md
  doc/news/_preparation_next_release.md
  doc/todo/RELEASE.md
  doc/tutorials/cascading.md
  doc/tutorials/contributing-clion.md
  doc/tutorials/contributing-windows.md
  scripts/spelling.sed
  src/bindings/swig/lua/README.md
  src/plugins/README.md
  src/plugins/gitresolver/README.md
  src/tools/website/resources/structure.json.in
Labels: ready to merge, floss2022w, H3

#4718 [FLOSS H3] jna: whitelist plugin: add validation check on get
  doc/news/_preparation_next_release.md
  src/bindings/jna/plugins/whitelist/src/main/java/org/libelektra/plugin/WhitelistPlugin.java
Labels: lang/java, floss2022w, H3

#4634 [FLOSS H3] docs: extend check_doc.sh
  doc/contrib/README.md
  doc/news/_preparation_next_release.md
  doc/tutorials/README.md
  tests/shell/CMakeLists.txt
  tests/shell/check_doc.sh
Labels: ready to merge, documentation, floss2022w, H3

#4757 [FLOSS T2] Fix LaTeX rendering
  doc/man/man1/kdb-run-website.1
  doc/news/2014-07-28_0.8.7.md
  doc/news/_preparation_next_release.md
  doc/tutorials/language-bindings.md
  src/tools/website/README.md
Labels: floss2022w, T2

#4768 [FLOSS T3] docs: Improve CONTRIBUTING Documentation
  .github/CONTRIBUTING.md
  doc/news/_preparation_next_release.md
Labels: documentation, floss2022w, T3

#4749 [FLOSS T2] Add validation to run_all_tests_with_docker tutorial
  doc/news/_preparation_next_release.md
  doc/tutorials/run_all_tests_with_docker.md
  tests/shell/shell_recorder/tutorial_wrapper/CMakeLists.txt
Labels: floss2022w, T2

#4787 [FLOSS T3] Add plugin memleak tutorial
  doc/news/_preparation_next_release.md
  doc/tutorials/plugins.md
Labels: lang/markdown, documentation, floss2022w, T3

#4786 [FLOSS T3] Add README for contributing in Doxygen
  doc/CODING.md
  doc/doxygen/README.md
  doc/news/_preparation_next_release.md
Labels: ready to merge, floss2022w, T3

#4765 [FLOSS T3] Documentation: Improve use of gender
  doc/api_blueprints/snippet-sharing.apib
  doc/news/_preparation_next_release.md
  doc/tutorials/validation.md
  doc/usecases/snippet_sharing/UC_authenticate.md
  doc/usecases/snippet_sharing/UC_reset_password.md
  doc/usecases/snippet_sharing/distinction_use_cases.md
  src/libs/meta/meta.c
Labels: floss2022w, T3

#4756 [FLOSS T2] Restructure website documentation
  doc/news/_preparation_next_release.md
  doc/tutorials/README.md
  src/tools/website/resources/structure.json.in
Labels: floss2022w, T2
