Repository ElektraInitiative/libelektra, pull requests merged in 2022-06, with the labels that each got.

#4320 Todos
  doc/news/_preparation_next_release.md
  doc/todo/BINDINGS
  doc/todo/DOCUMENTATION
  doc/todo/PLUGINS
  doc/todo/TODO
  doc/todo/TOOLS
  scripts/reset
Labels: ready to merge

#4372 #4368 fixed boolean value handling (missing tests, release notes and …
  doc/news/_preparation_next_release.md
  src/bindings/jna/libelektra/src/main/java/org/libelektra/Key.java
  src/bindings/jna/libelektra/src/main/java/org/libelektra/ReadableKey.java
  src/bindings/jna/libelektra/src/test/java/org/libelektra/KeyTest.java
  src/bindings/jna/plugins/sorted/src/main/java/org/libelektra/plugin/SortedPlugin.java
  src/bindings/jna/plugins/whitelist/src/test/java/org/libelektra/plugin/WhitelistPluginTests.java
Labels: ready to merge

#4319 [CM T1] tutorial: add cleanup section to the specification tutorial
  doc/news/_preparation_next_release.md
  doc/tutorials/specification.md
Labels: documentation, cm2022s

#4374 [CM T3] Kotlin binding refinement: null values, restructure, find methods
  doc/news/_preparation_next_release.md
  src/bindings/jna/hello-kotlin/src/main/kotlin/HelloElektra.kt
  src/bindings/jna/libelektra-kotlin/README.md
  src/bindings/jna/libelektra-kotlin/src/main/kotlin/org/libelektra/dsl/KeyDSL.kt
  src/bindings/jna/libelektra-kotlin/src/main/kotlin/org/libelektra/dsl/KeySetDSL.kt
  src/bindings/jna/libelektra-kotlin/src/main/kotlin/org/libelektra/keyExt/SetExt.kt
  src/bindings/jna/libelektra-kotlin/src/main/kotlin/org/libelektra/keyExt/Util.kt
  src/bindings/jna/libelektra-kotlin/src/main/kotlin/org/libelektra/keySetExt/Util.kt
  src/bindings/jna/libelektra-kotlin/src/main/kotlin/org/libelektra/keySetExt/serialformat/KeySetEncoder.kt
  src/bindings/jna/libelektra-kotlin/src/test/kotlin/org/libelektra/key/SetKeyTest.kt
  src/bindings/jna/libelektra-kotlin/src/test/kotlin/org/libelektra/key/UtilTest.kt
  src/bindings/jna/libelektra-kotlin/src/test/kotlin/org/libelektra/keySet/KeySetEncodeDecodeTest.kt
  src/bindings/jna/libelektra-kotlin/src/test/kotlin/org/libelektra/keySet/KeySetSerializationTest.kt
  src/bindings/jna/libelektra-kotlin/src/test/kotlin/org/libelektra/keySet/UtilTest.kt
Labels: cm2022s, needs review

#4376 [CM T3] dependabot: add dependabot.yml [fixes #4277]
  .github/dependabot.yml
  doc/news/_preparation_next_release.md
Labels: ready to merge

#4362 [CM T3] removed mentions of VERBOSE and HAVE_STDIO_H
  doc/news/_preparation_next_release.md
  src/bindings/cpp/include/kdbcontext.hpp
  src/bindings/cpp/include/kdbvalue.hpp
  src/bindings/intercept/env/tests/test_fork.cpp
  src/libs/elektra/kdb.c
  src/libs/elektra/keyset.c
  src/libs/elektra/keyvalue.c
  src/libs/elektra/mount.c
  src/libs/elektra/plugin.c
  src/libs/elektra/split.c
  src/libs/elektra/trie.c
  src/plugins/curlget/curlget.c
  src/tools/qt-gui/src/treeviewmodel.cpp
Labels: lang/cpp, lang/c, cm2022s
