Repository ElektraInitiative/libelektra, pull requests merged in 2023-07, with the labels that each got.

#4776 [Use Cases] Add use cases for bindings
  doc/news/_preparation_next_release.md
  doc/usecases/bindings/README.md
  doc/usecases/bindings/UC_drop_in_application.md
  doc/usecases/bindings/UC_existing_application.md
  doc/usecases/bindings/UC_new_application.md
Labels: lang/markdown, documentation

#4967 [CI] Fix bugs that lead to errors on Cirrus jobs (esp. building PDF documentation)
  doc/news/_preparation_next_release.md
  scripts/docker/cirrus/arch/Dockerfile
  src/libs/elektra/keyname.c
Labels: continuous integration, documentation, needs review

#4968 Write functionality for the ODBC backend
  benchmarks/CMakeLists.txt
  benchmarks/README.md
  benchmarks/mountpoint.c
  doc/help/kdb-mountOdbc.md
  doc/man/man1/kdb-mountOdbc.1
  doc/news/_preparation_next_release.md
  doc/tutorials/odbc-backend.md
  src/include/kdbdiff.h
  src/include/kdbplugin.h
  src/include/kdbprivate.h
  src/libs/elektra/kdb.c
  src/libs/elektra/keyset.c
  src/libs/elektra/plugin.c
  src/libs/elektra/symbols.map
  src/plugins/backend_odbc/CMakeLists.txt
  src/plugins/backend_odbc/README.md
  src/plugins/backend_odbc/backend_odbc.c
  src/plugins/backend_odbc/backend_odbc.h
  src/plugins/backend_odbc/backend_odbc_general.c
  src/plugins/backend_odbc/backend_odbc_general.h
  src/plugins/backend_odbc/backend_odbc_get.c
  src/plugins/backend_odbc/backend_odbc_get.h
  src/plugins/backend_odbc/backend_odbc_helpers.c
  src/plugins/backend_odbc/backend_odbc_helpers.h
  src/plugins/backend_odbc/backend_odbc_set.c
  src/plugins/backend_odbc/backend_odbc_set.h
  src/plugins/backend_odbc/sampleDb/elektraDB.db
  src/plugins/backend_odbc/sampleDb/prepareDB.sql
  src/plugins/backend_odbc/testmod_backend_odbc.c
Labels: lang/cmake, lang/c, lang/markdown

#4972 Java Binding wrap up
  doc/news/_preparation_next_release.md
  src/bindings/jna/README.md
  src/bindings/jna/libelektra/README.md
  src/bindings/jna/libelektra/exception-hierarchy.png
  src/bindings/jna/libelektra/exception-hierarchy.pu
  src/bindings/jna/libelektra/key-type-hierarchy.png
  src/bindings/jna/libelektra/key-type-hierarchy.pu
  src/bindings/jna/libelektra/runtime-exception-hierarchy.png
  src/bindings/jna/libelektra/runtime-exception-hierarchy.pu
Labels: ready to merge

#4979 Plugins: Improve c plugin (doc, tests, refactor)
  doc/CONTRACT.ini
  doc/news/_preparation_next_release.md
  src/plugins/c/CMakeLists.txt
  src/plugins/c/README.md
  src/plugins/c/c.c
  src/plugins/c/c.h
  src/plugins/c/testmod_c.c
Labels: lang/c, lang/markdown, documentation, needs review
