Repository ElektraInitiative/libelektra, pull requests merged in 2023-05, with the labels that each got.

#4888 new spec
  doc/news/_preparation_next_release.md
  doc/tutorials/namespaces.md
  src/libs/elektra/kdb.c
  src/plugins/spec/CMakeLists.txt
  src/plugins/spec/README.md
  src/plugins/spec/arrayspec.c
  src/plugins/spec/arrayspec.h
  src/plugins/spec/matching.c
  src/plugins/spec/matching.h
  src/plugins/spec/spec.c
  src/plugins/spec/spec.h
  src/plugins/spec/testmod_spec.c
  tests/shell/external/example_codegen_menu.sh
Labels: ready to merge, lang/c

#4910 `Webd` and `elektrad` bulk kdb meta-set
  doc/news/_preparation_next_release.md
  doc/tutorials/install-webui.md
  src/tools/elektrad/helper_test.go
  src/tools/elektrad/meta_handler.go
  src/tools/elektrad/meta_handler_test.go
  src/tools/elektrad/router.go
  src/tools/webd/package-lock.json
  src/tools/webd/src/connector.js
  src/tools/webd/src/routes/instances.js
Labels: ready to merge

#4916 `Webd` & `elektrad` new request for bulk creation for configurations (kdb set)
  doc/news/_preparation_next_release.md
  src/tools/elektrad/helper_test.go
  src/tools/elektrad/kdb_handler.go
  src/tools/elektrad/kdb_handler_test.go
  src/tools/elektrad/router.go
  src/tools/webd/src/connector.js
  src/tools/webd/src/routes/instances.js
Labels: ready to merge

#4917 Remove info meta key
  doc/news/_preparation_next_release.md
  src/plugins/spec/README.md
  src/plugins/spec/spec.c
  src/plugins/spec/spec.h
  src/plugins/spec/testmod_spec.c
Labels: ready to merge

#4918 Add shell test case for parent array spec bug
  doc/news/_preparation_next_release.md
  tests/shell/external/example_codegen_econf_empty_array_spec.sh
Labels: ready to merge

#4919 Set new target name for so files (#3486)
  doc/dev/algorithm.md
  doc/help/elektra-bootstrapping.md
  doc/help/kdb-convert.md
  doc/help/kdb-editor.md
  doc/help/kdb-export.md
  doc/help/kdb-import.md
  doc/man/man1/kdb-convert.1
  doc/man/man1/kdb-editor.1
  doc/man/man1/kdb-export.1
  doc/man/man1/kdb-import.1
  doc/man/man7/elektra-bootstrapping.7
  doc/news/_preparation_next_release.md
  doc/tutorials/contributing-clion.md
  scripts/change-resolver-symlink.in
  scripts/change-storage-symlink.in
  scripts/cmake/Modules/LibAddPlugin.cmake
  scripts/cmake/Modules/PackagingFedora.cmake
  src/libs/loader/dl.c
  src/plugins/CMakeLists.txt
Labels: ready to merge

#4913 [Tutorial Spec dockerd + Spec Use-Cases + Specification]: Create specification for dockerd configuration file and use cases
  doc/news/_preparation_next_release.md
  doc/tutorials/README.md
  doc/tutorials/dockerd-specification.md
  doc/usecases/specification/array-specification.md
  doc/usecases/specification/enum-specification.md
  doc/usecases/specification/simple-specification.md
  doc/usecases/specification/underline-specification.md
  examples/spec/dockerd.ini
Labels: ready to merge

#4464 Binding/xfconf
  doc/news/_preparation_next_release.md
  scripts/CMakeLists.txt
  scripts/cmake/ElektraPackaging.cmake
  scripts/cmake/Modules/PackagingDebian.cmake
  scripts/cmake/Modules/PackagingFedora.cmake
  scripts/packaging/package.sh
  scripts/xfconf/CMakeLists.txt
  scripts/xfconf/xfconf-populate
  scripts/xfconf/xfconf-system-lib-replace.in
  scripts/xfconf/xfconf-system-lib-restore.in
  scripts/xfconf/xfconf-user-lib-replace.in
  src/bindings/CMakeLists.txt
  src/bindings/xfconf/CMakeLists.txt
  src/bindings/xfconf/README.md
  src/bindings/xfconf/elektra-xfconf-binding.c
  src/bindings/xfconf/elektra-xfconf-binding.h
  src/bindings/xfconf/elektra-xfconf-channel.c
  src/bindings/xfconf/elektra-xfconf-channel.h
  src/bindings/xfconf/elektra-xfconf-errors.c
  src/bindings/xfconf/elektra-xfconf-errors.h
  src/bindings/xfconf/elektra-xfconf-types.c
  src/bindings/xfconf/elektra-xfconf-types.h
  src/bindings/xfconf/elektra-xfconf-util.h
  src/bindings/xfconf/elektra-xfconf.c
  src/bindings/xfconf/elektra-xfconf.h
  src/plugins/xfconf/README.md
Labels: work in progress, lang/c
