Repository ElektraInitiative/libelektra, pull requests merged in 2023-06, with the labels that each got.

#4963 fix: remove metakeys from array keys correctly (#4961)
  doc/news/_preparation_next_release.md
  src/plugins/spec/spec.c
  src/plugins/spec/testmod_spec.c
Labels: lang/c

#4915 ODBC backend plugin
  .cirrus.yml
  doc/help/kdb-mount.md
  doc/help/kdb-mountOdbc.md
  doc/images/unixODBC.png
  doc/images/unixODBC.svg
  doc/man/man1/kdb-mount.1
  doc/man/man1/kdb-mountOdbc.1
  doc/man/man7/elektra-plugins.7
  doc/news/_preparation_next_release.md
  doc/tutorials/README.md
  doc/tutorials/odbc-backend.md
  scripts/docker/alpine/3.17/Dockerfile
  scripts/docker/alpine/3.17/release.Dockerfile
  scripts/docker/arch/Dockerfile
  scripts/docker/centos/stream8/Dockerfile
  scripts/docker/cirrus/arch/Dockerfile
  scripts/docker/cirrus/fedora/Dockerfile
  scripts/docker/debian/bullseye/Dockerfile
  scripts/docker/debian/buster/Dockerfile
  scripts/docker/debian/sid/Dockerfile
  scripts/docker/fedora/31/Dockerfile
  scripts/docker/fedora/32/Dockerfile
  scripts/docker/fedora/33/Dockerfile
  scripts/docker/fedora/34/Dockerfile
  scripts/docker/fedora/35/Dockerfile
  scripts/docker/fedora/36/Dockerfile
  scripts/docker/fedora/37/Dockerfile
  scripts/docker/jenkinsnode/Dockerfile
  scripts/docker/opensuse/15.3/Dockerfile
  scripts/docker/ubuntu/bionic/Dockerfile
  scripts/docker/ubuntu/focal/Dockerfile
  scripts/docker/ubuntu/jammy/Dockerfile
  scripts/docker/ubuntu/kinetic/Dockerfile
  src/bindings/cpp/include/key.hpp
  src/libs/elektra/kdb.c
  src/libs/elektra/keyname.c
  src/plugins/README.md
  src/plugins/backend/backend.c
  src/plugins/backend/backendprivate.h
  src/plugins/backend_odbc/CMakeLists.txt
  src/plugins/backend_odbc/README.md
  src/plugins/backend_odbc/backend_odbc.c
  src/plugins/backend_odbc/backend_odbc.h
  src/plugins/backend_odbc/backend_odbc_general.c
  src/plugins/backend_odbc/backend_odbc_general.h
  src/plugins/backend_odbc/backend_odbc_get.c
  src/plugins/backend_odbc/backend_odbc_get.h
  src/plugins/backend_odbc/backend_odbc_helpers.c
  src/plugins/backend_odbc/backend_odbc_helpers.h
  src/plugins/backend_odbc/sampleDb/elektraDB.db
  src/plugins/backend_odbc/sampleDb/prepareDB.sql
  src/plugins/backend_odbc/testmod_backend_odbc.c
  src/tools/kdb/factory.hpp
  src/tools/kdb/mountOdbc.cpp
  src/tools/kdb/mountOdbc.hpp
Labels: lang/cpp, lang/cmake, lang/c, lang/markdown

#4946 doc: add git bundle and tags to release docu
  doc/news/_preparation_next_release.md
  doc/todo/RELEASE.md
Labels: ready to merge, documentation
