Repository ElektraInitiative/libelektra, pull requests merged in 2023-01, with the labels that each got.

#4750 [FLOSS T2] tutorial: update array tutorial
  doc/news/_preparation_next_release.md
  doc/tutorials/arrays.md
Labels: floss2022w, T2

#4396 Plugin/xfconf
  .cirrus.yml
  .github/workflows/macOS.yml
  doc/man/man7/elektra-plugins.7
  doc/news/_preparation_next_release.md
  examples/codegen/econf/pkgconfig/Makefile
  examples/codegen/menu/pkgconfig/Makefile
  examples/codegen/tree/pkgconfig/Makefile
  examples/external/pkgconfig/Makefile
  examples/highlevel/pkgconfig/Makefile
  scripts/cmake/Modules/FindXfconf.cmake
  scripts/docker/cirrus/arch/Dockerfile
  scripts/docker/cirrus/fedora/Dockerfile
  scripts/docker/debian/bullseye/Dockerfile
  scripts/docker/debian/bullseye/release.Dockerfile
  scripts/docker/debian/buster/Dockerfile
  scripts/docker/debian/buster/release.Dockerfile
  scripts/docker/debian/sid/Dockerfile
  scripts/docker/fedora/31/Dockerfile
  scripts/docker/fedora/32/Dockerfile
  scripts/docker/fedora/33/Dockerfile
  scripts/docker/fedora/34/Dockerfile
  scripts/docker/fedora/35/Dockerfile
  scripts/docker/fedora/36/Dockerfile
  scripts/docker/fedora/37/Dockerfile
  scripts/docker/jenkinsnode/Dockerfile
  scripts/docker/opensuse/15.3/Dockerfile
  scripts/docker/opensuse/15.3/release.Dockerfile
  scripts/jenkins/Jenkinsfile
  src/plugins/README.md
  src/plugins/xfconf/CMakeLists.txt
  src/plugins/xfconf/README.md
  src/plugins/xfconf/testmod_xfconf.c
  src/plugins/xfconf/xfconf.c
  src/plugins/xfconf/xfconf.h
  tests/shell/check_kdb_internal_check.sh
  tests/shell/external/example.sh
  tests/shell/external/example_codegen_econf.sh
  tests/shell/external/example_codegen_menu.sh
  tests/shell/external/example_codegen_tree.sh
  tests/shell/external/example_highlevel.sh
  tests/shell/external/pythongen.sh
  tests/shell/include_common.sh.in
  tests/valgrind.suppression
Labels: ready to merge, lang/c

#4764 [FLOSS T3] docs: Improve Git Documentation
  doc/Git.md
  doc/news/_preparation_next_release.md
Labels: documentation, floss2022w, T3

#4705 [FLOSS H3] Testing: Add shellcheck testing script
  doc/news/_preparation_next_release.md
  doc/todo/TESTING
  tests/shell/check_shellcheck.sh
  tests/shell/check_shellcheck_ignorelist.txt
Labels: ready to merge, floss2022w, H3

#4726 GitHub actions: Update stale issue/PR action
  .github/workflows/stale.yml
  doc/news/_preparation_next_release.md
Labels: ready to merge

#4729 [FLOSS H3] mini: fix silent failure on meta-key insertion
  doc/news/_preparation_next_release.md
  src/plugins/mini/README.md
  src/plugins/mini/mini.c
  src/plugins/mini/testmod_mini.c
Labels: floss2022w, H3

#4734 [FLOSS H3] links: Replace tons of http with https
  CODE_OF_CONDUCT.md
  doc/AUTHORS.md
  doc/CODING.md
  doc/COMPILE.md
  doc/INSTALL.md
  doc/README.md
  doc/SECURITY.md
  doc/TESTING.md
  doc/VERSION.md
  doc/decisions/0b_rejected/elektra_web_pubsub.md
  doc/decisions/3_decided/library_split.md
  doc/decisions/5_implemented/error_codes.md
  doc/decisions/5_implemented/rest_api_documentation.md
  doc/man/man1/kdb-run-website.1
  doc/news/_preparation_next_release.md
  doc/todo/OPTIMIZE
  doc/tutorials/highlevel-bindings.md
  doc/tutorials/profiling.md
  doc/tutorials/python-kdb.md
  src/tools/website/README.md
  src/tools/website/public/vendor/asciinema/asciinema-player.js
  src/tools/website/resources/assets/skin/base/fonts/font-awesome/font-awesome.less
  src/tools/website/resources/assets/skin/base/fonts/font-awesome/mixins.less
  src/tools/website/resources/assets/skin/base/util/space.less
  src/tools/webui/README.md
  src/tools/webui/src/components/ErrorSnackbar.jsx
  tests/kdb/testkdb_highlevel.cpp
  tests/linkchecker.whitelist
  tests/shell/check_formatting.sh
Labels: documentation, floss2022w, H3

#4770 [FLOSS H3] Fixing deadlinks on the Website in the Availability Section
  doc/news/_preparation_next_release.md
  src/tools/website/public/assets/translations/en.json
Labels: floss2022w, H3

#4730 [FLOSS H3] Only let http links pass if whitelisted
  doc/news/_preparation_next_release.md
  scripts/link-checker
Labels: lang/shell, floss2022w, H3

#4623 [FLOSS PX] Elixir bindings
  doc/news/_preparation_next_release.md
  scripts/cmake/Modules/FindErlang.cmake
  scripts/docker/debian/bullseye/Dockerfile
  src/bindings/CMakeLists.txt
  src/bindings/README.md
  src/bindings/erl_nif/.gitignore
  src/bindings/erl_nif/CMakeLists.txt
  src/bindings/erl_nif/README.md
  src/bindings/erl_nif/elixir/.formatter.exs
  src/bindings/erl_nif/elixir/.gitignore
  src/bindings/erl_nif/elixir/CMakeLists.txt
  src/bindings/erl_nif/elixir/README.md
  src/bindings/erl_nif/elixir/lib/elektra/elektra.ex
  src/bindings/erl_nif/elixir/lib/elektra/kdb.ex
  src/bindings/erl_nif/elixir/lib/elektra/key.ex
  src/bindings/erl_nif/elixir/lib/elektra/key_set.ex
  src/bindings/erl_nif/elixir/lib/elektra/system.ex
  src/bindings/erl_nif/elixir/lib/nif_util/nif_resource.ex
  src/bindings/erl_nif/elixir/lib/nif_util/nif_util.ex
  src/bindings/erl_nif/elixir/mix.exs
  src/bindings/erl_nif/elixir/test/elektra/kdb_test.exs
  src/bindings/erl_nif/elixir/test/elektra/key_set_test.exs
  src/bindings/erl_nif/elixir/test/elektra/key_test.exs
  src/bindings/erl_nif/elixir/test/test_helper.exs
  src/bindings/erl_nif/lib/nif_kdb.c
Labels: floss2022w

#4648 [FLOSS H2] Implement network retries
  doc/news/_preparation_next_release.md
  src/plugins/network/README.md
  src/plugins/network/network.c
Labels: lang/c, floss2022w, H2

#4713 [FLOSS T1] desktop: implement unit tests
  doc/news/_preparation_next_release.md
  src/plugins/desktop/CMakeLists.txt
  src/plugins/desktop/testmod_desktop.c
Labels: lang/c, floss2022w, T1

#4831 tests: Add `memleak` labels to failing tests
  doc/news/_preparation_next_release.md
  doc/todo/TESTING
  src/bindings/erl_nif/elixir/CMakeLists.txt
  src/bindings/intercept/env/tests/CMakeLists.txt
Labels: ready to merge
